### ISSUE TITLE
[GEN] Migrate improvements from `intel/llvm` to `intel/intel-xpu-backend-for-triton`

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#1007]

**Comment by victor-eds** [comment]
Comparing GEN dialect at https://github.com/intel/llvm/tree/genx with our TritonGEN dialect. `barrier` and `sub_group_shuffle` are pretty much the same. ND-range operations differ, improvements aren't ported. However, there's no need to do this as #1236 will drop those operations to convert directly from `gpu` operations to `llvm` calls.

Thus, I would call this issue resolved.

**Comment by victor-eds** [comment]
Misc. improvements:
- https://github.com/intel/intel-xpu-backend-for-triton/pull/1267
- https://github.com/intel/intel-xpu-backend-for-triton/pull/1268 (present in GEN)
