### ISSUE TITLE
[UT][CI] Add Python 3.12 to daily validation matrix and / or to CI checks on PR merge

### ISSUE THREAD

**Issue by vlad-penkin** [intel/intel-xpu-backend-for-triton#1018]
Initial proposal is not to run full Python validation matrix (3.9, 3.10, 3.11, 3.12) for each PR but do it daily.

Few notes:
- Python validation matrix should match current PyTorch validation matrix
- Python support version matrix should follow PyTorch policy, more details [here](https://github.com/pytorch/pytorch/issues/120718)), which follows [NEP 29 policy](https://numpy.org/neps/nep-0029-deprecation_policy.html)

**Comment by vlad-penkin** [comment]
@etiotto, @whitneywhtsang, @pbchekin feel free to provide the feedback on the requirements.

**Comment by pbchekin** [comment]
Blocked by missing IPEX build and run time dependencies for Python 3.12:

* #1004 
* #1008

Also there is an old pinning for `transformers` that breaks E2E test with Python 3.12:

* #1019
