### ISSUE TITLE
Flaky test `language/test_libdevice.py::test_bessel[j0-bessel_j0-float64]`

### ISSUE THREAD

**Issue by pbchekin** [intel/intel-xpu-backend-for-triton#1033]
```
FAILED language/test_libdevice.py::test_bessel[j0-bessel_j0-float64] - AssertionError: Tensor-likes are not close!

Mismatched elements: 1 / 128 (0.8%)
Greatest absolute difference: 2.740302717935128e-07 at index (33,) (up to 1e-07 allowed)
Greatest relative difference: 2.547540389956526e-06 at index (33,) (up to 1e-07 allowed)
```

See https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/8942186494/job/24564209551
Restarting the workflow usually helps.

**Comment by anmyachev** [comment]
@pbchekin I looked a bit at previous CI runs, this test has been stable lately. I think we can close this issue, unless you have any recent CI runs in mind that had this problem.

**Comment by pbchekin** [comment]
Sure, let's close.
