### ISSUE TITLE
E2E accuracy regression: infra_error for huggingface-inference-amp_bf16-GoogleFnet

### ISSUE THREAD

**Issue by pbchekin** [intel/intel-xpu-backend-for-triton#1034]
infra_error for huggingface-inference-amp_bf16-GoogleFnet

```
loading model: 0it [00:00, ?it/s]WARNING:common:Model GoogleFnet supports float32 only
FFT WARNING: INPUT_STRIDES and OUTPUT_STRIDES are deprecated: please use FWD_STRIDES and BWD_STRIDES, instead.

FFT WARNING: INPUT_STRIDES and OUTPUT_STRIDES are deprecated: please use FWD_STRIDES and BWD_STRIDES, instead.

free(): invalid pointer

LIBXSMM_VERSION: main_stable-1.17-3651 (25693763)
LIBXSMM_TARGET: spr [Intel(R) Xeon(R) Platinum 8480+]
Registry and code: 13 MB
Command: /opt/hostedtoolcache/Python/3.10.14/x64/bin/python benchmarks/dynamo/huggingface.py --accuracy --amp -dxpu -n10 --no-skip --dashboard --inference --freezing --backend=inductor --timeout=4800 --output=/runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/inductor_log/huggingface/amp_bf16/inductor_huggingface_amp_bf16_inference_xpu_accuracy.csv --only=GoogleFnet
Uptime: 4.347735 s
ERROR
```

Potentially related to the switch to PTDB.

**Comment by vlad-penkin** [comment]
Issue is no longer reproducible.

Env:
- pytorch is built from source, top of the main trunk, commit_id - `9a8ab778d34bd24c5caceb340837483decc4c311`
- triton xpu is built from source, top of the main trunk, commit_id - `fe93a00ffe438e9ba8c8392c0b051b1662c810de`
- benchmark is built from source, top of the main trunk, commit_id - `d54ca9f80ead108c8797441681e219becaf963d8`
- torchaudio is built from source, top of the main trunk,  commit_id - `1980f8af5bcd0bb2ce51965cf79d8d4c25dad8a0`
- torchvision  is built from source, top of the main trunk,  commit_id - `10239873229e527f8b7e7b3340c40ee38bb1cfc4`
- PyTorch Dependency Bundle 0.5.0
- Latest Rolling Driver
