### ISSUE TITLE
[UT][E2E][CI] Capture GPU runtime parameters

### ISSUE THREAD

**Issue by vlad-penkin** [intel/intel-xpu-backend-for-triton#1036]
**Requirements**

# Capture runtime env parameter in reports:  

1. Diver version 
2. GPU device name
3. Agama version

# Implementation approach

Shell script which can be integrated in UT test runner script , GH UT and E2E workflows which saves captured parameters to the separated files. This ticket is part of the:
- #979 implemenation 

For each runtime env parameter new txt file in the reports folder should be created.

# Notes on how to get these information

## Driver version

```
apt info libigc1 | grep -oP 'Version: \K[^~]+' >libigc1_version.txt
apt info intel-level-zero-gpu  | grep -oP 'Version: \K[^~]+' >level-zero_version.txt
```

## GPU

` xpumcli discovery | grep "Device Name" | sed -n 's/.*Device Name: \(.*\)\s*|/\1/p' >gpu.txt`

## Agama

Capture base number

`apt info libigc1 | grep Version | sed 's/.*-\(.*\)~.*/\1/')`

**Comment by gshimansky** [comment]
Script to get these hardware details is implemented here https://github.com/intel/intel-xpu-backend-for-triton/pull/1053

**Comment by gshimansky** [comment]
PR merged, HW data should now be collected for e2e workloads.
