### ISSUE TITLE
[Upstream] Upstream the fix of the common issue in Triton GPU lowering the reduce op to SIMT LLVM.

### ISSUE THREAD

**Issue by chengjunlu** [intel/intel-xpu-backend-for-triton#1043]
This issue has been fixed in the down stream. 
https://github.com/intel/intel-xpu-backend-for-triton/pull/835
Need to upstream the fix to the upstream Triton.

**Comment by hwnam831** [comment]
The upstream reviewers refused to merge this implementation because the change only affects Intel GPUs.
Please see [triton#4120](https://github.com/triton-lang/triton/pull/4120).
