### ISSUE TITLE
Investigate performance of subgroup shuffles on PVC

### ISSUE THREAD

**Issue by victor-eds** [intel/intel-xpu-backend-for-triton#1045]
Investigate code generated by IGC for PVC `OpGroupNonUniformShuffle[""|Xor|Up|Down]` operations and whether this gives better performance than implementing shuffles by going through local memory. Check what Triton operations use shuffles to be lowered (reductions and scan?) and performance impact of this instructions vs local memory. Check if non-constant masks are ever used when lowering the aforementioned instructions and also check performance for the case of non-constant masks if required.

**Comment by FMarno** [comment]
The use of the WaveAll intrinsic removes the need for subgroup shuffles, making this ticket redundant. @whitneywhtsang or @etiotto Could one of please confirm you are happy to close this issue and we'll instead pursue the use of intrinsics.

**Comment by whitneywhtsang** [comment]
> The use of the WaveAll intrinsic removes the need for subgroup shuffles, making this ticket redundant. @whitneywhtsang or @etiotto Could one of please confirm you are happy to close this issue and we'll instead pursue the use of intrinsics.

I am fine with closing this issue.

**Comment by etiotto** [comment]
> The use of the WaveAll intrinsic removes the need for subgroup shuffles, making this ticket redundant. @whitneywhtsang or @etiotto Could one of please confirm you are happy to close this issue and we'll instead pursue the use of intrinsics.

I am fine closing it.
