### ISSUE TITLE
Improve design of passing device properties to Intel transformations

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#1047]
PyTorch sends Triton some device properties ([intel-xpu-backend-for-triton/third_party/intel/backend/compiler.py at llvm-target · intel/intel-xpu-backend-for-triton (github.com)](https://github.com/intel/intel-xpu-backend-for-triton/blob/llvm-target/third_party/intel/backend/compiler.py#L82)), we currently only pass `device_arch` to our transformations as pass option [intel-xpu-backend-for-triton/include/triton/Dialect/TritonIntelGPU/Transforms/Passes.td at llvm-target · intel/intel-xpu-backend-for-triton (github.com)](https://github.com/intel/intel-xpu-backend-for-triton/blob/llvm-target/include/triton/Dialect/TritonIntelGPU/Transforms/Passes.td#L30). More of these device properties will be needed in Intel transformations. For example, there will be device properties to determine if 2d prefetch/read/write, dpas are available. May not be very scalable to pass more and more pass option to each pass. 

This issue is to determine if there can be a better design have these information available to Intel transformations. Maybe a way to let the pass to query the information? Store the information in a base class? Store the information in the IR?

**Comment by FMarno** [comment]
Do you have some examples of the properties that will be interesting?

I think that storing the device arch as a module attribute makes most sense, and is already in place, though I'm not sure if the information is used. [ConvertTritonToTritonGPU](https://github.com/intel/intel-xpu-backend-for-triton/blob/69b19ece96e4e0cbb0143b4c23902e9710060113/include/triton/Conversion/TritonToTritonGPU/Passes.td#L31) has an `target` option which would have something like `cuda:sm_80` for the Nvidia backend. Maybe we just need to ensure the value there is PVC or ATS and that the information is used instead of the `device_arch` option. I'll give that a shot and feedback.

**Comment by whitneywhtsang** [comment]
We will need to store more information on top of device arch, like if 2d prefetch/read/write, dpas are available. 
For example, rewrite tensor pass will need to know if 2d read/write is available to perform corresponding transformation. 
Should we store all those information as module attribute, or should we create an equivalent operator as https://mlir.llvm.org/docs/Dialects/SPIR-V/#target-environment in the GEN dialect?

**Comment by FMarno** [comment]
I don't really see any benefit to creating a system like the SPIR-V target environment. I think the solution of having extra attributes on the module op would be simple and also fit the requirements. It's probably also important to remember that there will be subsequent devices to PVC, with either different or similar semantics, and to leave space open for them.
I would suggest we add an attribute to the module for each enabled feature, so the existence of the attribute signals that the feature is present. for example:
```
module attributes { triton_gpu.pvc_dpas_enabled, triton_gpu.pvc_2d_block_read_enabled } {...}
```
signals that DPAS and 2d block read are available but not prefetch or block write. The "pvc" prefix will hopefully help avoid confusion in the future if there are similarly named features for the device of the time.
What do you think?
