### ISSUE TITLE
Avoid post-processing generated LLVM IR

### ISSUE THREAD

**Issue by etiotto** [intel/intel-xpu-backend-for-triton#1077]
Currently is not possible to generate metadata in the (MLIR) LLVM dialect. Therefore, to attach max group size, required workgroup size,...  metadata to a triton kernel we first generate `passthrough` attributes for the kernel function, and then post-process the generated LLVM IR to 'transfer' specific function attributes to metadata. Here is the code that 'transfers' attributes to metadata (from `amendLLVM`):

  ```
    // Attach required metadata to the kernel.
  using namespace mlir::triton;
  SmallVector<llvm::StringLiteral> genAttrs{
      TritonGEN::TritonGENDialect::getMaxWorkGroupSizeAttrName(),
      TritonGEN::TritonGENDialect::getReqdWorkGroupSizeAttrName(),
      TritonGEN::TritonGENDialect::getReqdSubGroupSizeAttrName()};

  for (llvm::StringLiteral genAttr : genAttrs) {
    if (!kernel->hasFnAttribute(genAttr))
      continue;

    Attribute fnAttr = kernel->getFnAttribute(genAttr);
    assert(fnAttr.isStringAttribute() && "Expecting a string attribute");
    attachMetadata(fnAttr.getKindAsString().split('.').second,
                   fnAttr.getValueAsString(), kernel);
    kernel->removeFnAttr(genAttr);
  }
  ```

It would be nice if we could remove the need for post-processing the generate LLVM IR.

**Comment by victor-eds** [comment]
Thanks!
