### ISSUE TITLE
[Performance] Support to load the column major matrix B for the DPAS.

### ISSUE THREAD

**Issue by chengjunlu** [intel/intel-xpu-backend-for-triton#1089]
To improve the performance of flash attention. We need to support to load column major matrix B with 2D load instruction.

One flash attention kernel with the column major matrix B Triton kernel is here:
https://github.com/intel/intel-xpu-backend-for-triton/blob/1e4fb6497c1e2c55b738a842d05f14ae995e07c9/python/triton/ops/flash_attention.py#L41

**Comment by vlad-penkin** [comment]
@LiyangLingIntel to confirm that this is a duplicate

**Comment by LiyangLingIntel** [comment]
Close this one for duplicate with https://github.com/intel/intel-xpu-backend-for-triton/issues/965
