### ISSUE TITLE
Fix `LinearLayoutConversions` test failures

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#1100]
To reproduce remove the following lines from `unittest/Dialect/TritonGPU/CMakeLists.txt`:
```
# FIXME: Fail on XPU.
return()
```

`LinearLayoutConversions` unit tests are added in 751ba68f364779f18b7135a759083da922586348. 
The lines above are added in https://github.com/intel/intel-xpu-backend-for-triton/pull/1098 to temporarily disable the tests.

```
cd python/build/cmake.linux-x86_64-cpython-3.9
ctest .
```

**Comment by chengjunlu** [comment]
This issue has already been fixed at Triton main trunk.
[990bb719f043ffb7155d7e38b1d8ddc5ffd374e4](https://github.com/openai/triton/commit/990bb719f043ffb7155d7e38b1d8ddc5ffd374e4)

The order of expression evaluation order does matter.

**Comment by chengjunlu** [comment]
By merge the latest Triton code solve this issue:
https://github.com/intel/intel-xpu-backend-for-triton/pull/1101.

**Comment by whitneywhtsang** [comment]
Two more failures to resolve when enabling linear layout:
```
FAILED operators/test_matmul.py::test_op[128-256-64-1-8-3-256-512-160-True-True-float32-float32-None-True-None-None] - AssertionError: Tensor-likes are not close!
FAILED operators/test_matmul.py::test_op[128-256-64-1-8-3-256-512-160-True-False-float32-float32-None-True-None-None] - AssertionError: Tensor-likes are not close!
```

To reproduce:
```
--- a/third_party/intel/lib/TritonIntelGPUToLLVM/Utility.h
+++ b/third_party/intel/lib/TritonIntelGPUToLLVM/Utility.h
@@ -510,10 +510,7 @@ emitOffsetForLayout(Attribute layout, RankedTensorType type) {
 inline SmallVector<SmallVector<Value>>
 emitIndices(Location loc, RewriterBase &rewriter, const TargetInfoBase &target,
             Attribute layout, RankedTensorType type, bool withCTAOffset,
-            bool allowLL = false) {
-  // TODO(jlebar): LLs are disabled for now due to bugs found on AMD and A100
-  // GPUs.  Enable again wth allowLL = true above.
-
+            bool allowLL = true) {
```

**Comment by chengjunlu** [comment]
I created a new issue to track the new issue found. https://github.com/intel/intel-xpu-backend-for-triton/issues/1232

The original issue has been fixed.
