### ISSUE TITLE
[#6 Attention Performance] extend attention support for Causal = True

### ISSUE THREAD

**Issue by Dewei-Wang-sh** [intel/intel-xpu-backend-for-triton#1102]

**Comment by jopperm** [comment]
Update: I'm actively working on this. What I've found out so far is that activating causal masking affects the propagation of layout information in the kernel function. There are now two dependent loops, and the current block's indices are evaluated in the computation, so we need to support additional operations (`tt.make_range`, `arith.select` and `arith.cmpi`) related to the mask computation.

**Comment by jopperm** [comment]
Update: Still WIP. Locally, I have extended the `perf-attn` branch enough to reach LLVM-IR generation, though there are a couple of illegal instruction being created, which I believe originate from the TTGIR-level.

**Comment by jopperm** [comment]
Update: Still WIP. I'm investigating how to handle "row vectors" (e.g. `tensor<1x64>`) correctly.

**Comment by jopperm** [comment]
WIP.

**Comment by jopperm** [comment]
Update: PR is up, still working on tests.

**Comment by jopperm** [comment]
Update: The linked PRs are under review.

**Comment by jopperm** [comment]
Update (for 9/9/24): Two outstanding PRs to land, then I need to check if E2E execution works on `llvm-target`.

**Comment by jopperm** [comment]
Update: Unchanged, still investigating

**Comment by jopperm** [comment]
Update: Still working on this.

**Comment by jopperm** [comment]
Update: I can run all benchmarks configs from `flash_attention_fwd_benchmark.py` locally, but CI hits a compiler error. Investigating.

**Comment by whitneywhtsang** [comment]
> Update: I can run all benchmarks configs from `flash_attention_fwd_benchmark.py` locally, but CI hits a compiler error. Investigating.

Please ensure `TRITON_INTEL_ENABLE_INSTR_SCHED=1` is exported when testing locally.
