### ISSUE TITLE
[#7 Attention Performance] compare triton optimizations to XeTLA counterpart optimization

### ISSUE THREAD

**Issue by Dewei-Wang-sh** [intel/intel-xpu-backend-for-triton#1103]
so that we know what optimization we are lacking or different.

**Comment by quintinwang5** [comment]
https://intel-my.sharepoint.com/:p:/p/quintin_wang/EUo2pGQAswFDow_mVOolSEIBzeVEa-QpvS9NPBURcqJt6Q?e=8nYtps
