### ISSUE TITLE
[#6 GEMM Performance] enable stream K for gemm

### ISSUE THREAD

**Issue by Dewei-Wang-sh** [intel/intel-xpu-backend-for-triton#1104]
enable feature- streamK or splitK

**Comment by LiyangLingIntel** [comment]
A draft version of GEMM stream K kernel is placed here [10-experimental-block-pointer-streamk.py](https://github.com/intel/intel-xpu-backend-for-triton/blob/liyang/gemm-stream-k/python/tutorials/10-experimental-block-pointer-streamk.py).
It can produce correct results on the fallback path. To measure and get the best performance, it needs to backport a series of features including atomic operations support to block pointer path.

**Comment by LiyangLingIntel** [comment]
For the Split-K kernel, I think we can reuse https://github.com/triton-lang/kernels/blob/main/kernels/matmul.py with minor changes.

**Comment by LiyangLingIntel** [comment]
> A draft version of GEMM stream K kernel is placed here [10-experimental-block-pointer-streamk.py](https://github.com/intel/intel-xpu-backend-for-triton/blob/liyang/gemm-stream-k/python/tutorials/10-experimental-block-pointer-streamk.py). It can produce correct results on the fallback path. To measure and get the best performance, it needs to backport a series of features including atomic operations support to block pointer path.

After deeper investigation into this task, to support Atomic Op in the BlockPtr Path, we have to support operations with tensor of pointers and include more blocked layouts with potential layout conversion. This is not considered in previous BlockPtr path design. After offline discussion with @Dewei-Wang-sh, we plan to separate this task to two:
1. For this task #1104: implemented StreamK kernel with block pointer, which is submitted in PR https://github.com/intel/intel-xpu-backend-for-triton/pull/1564
2. Add Atomic support to BlockPtr path and get 90% perf data for StreamK to XeTLA: https://github.com/intel/intel-xpu-backend-for-triton/issues/1575
