### ISSUE TITLE
Unskipping test_flash_attention.py breaks regular runs

### ISSUE THREAD

**Issue by leshikus** [intel/intel-xpu-backend-for-triton#1109]
The commit https://github.com/intel/intel-xpu-backend-for-triton/commit/e47fd9537aeb313cd048393ac50d71b25993ec56 enables several tests, this breaks conda basekit run.

See the log at
https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/9056251421/job/24878516034

**Comment by whitneywhtsang** [comment]
Those `test_flash_attention` tests are enabled by 1e4fb6497c1e2c55b738a842d05f14ae995e07c9 and not e47fd9537aeb313cd048393ac50d71b25993ec56.
@leshikus Are you sure the failures are caused by e47fd9537aeb313cd048393ac50d71b25993ec56?

**Comment by leshikus** [comment]
Whitney, probably you are correct. Both commits happen at the same day, I've just start noticing failures

**Comment by leshikus** [comment]
@whitneywhtsang thank you for the help with the owner

**Comment by etiotto** [comment]
@leshikus they pass without using the conda env. so can you explain what is the difference the conda env. introduces ?

**Comment by leshikus** [comment]
@etiotto the conda env means the different environment, namely, different libraries and different library paths; in some cases when a compiler is called and the problems can happen due to different header resolution, but this particular problem looks more like a linking problem to me

**Comment by vlad-penkin** [comment]
@leshikus can we close this ticket?

**Comment by whitneywhtsang** [comment]
`test_flash_attention.py` no longer exists, closing this issue.
