### ISSUE TITLE
[Upstream] Upstream the threads_per_warp changes in #414

### ISSUE THREAD

**Issue by chengjunlu** [intel/intel-xpu-backend-for-triton#1135]
Upstream the changes in https://github.com/intel/intel-xpu-backend-for-triton/pull/414

**Comment by whitneywhtsang** [comment]
FYI https://triton-lang.slack.com/archives/C01LY4FJL56/p1715880227996969.

**Comment by vlad-penkin** [comment]
@etiotto and @whitneywhtsang based on above mentioned Slack comments what is our course of actions for resolving this ticket? Can we close it?

**Comment by whitneywhtsang** [comment]
It is unlikely we can upstream the part that we specify `threads_per_warp` in kernel launch, but there are still other parts in #414 which we should attempt to upstream.
