### ISSUE TITLE
[#8 GEMM Performance] compare triton optimizations to XeTLA/openCL optimization

### ISSUE THREAD

**Issue by Dewei-Wang-sh** [intel/intel-xpu-backend-for-triton#1154]
Shape(m*k*n)
4096\*4096\*4096
8192\*8192\*8192
1024\*28672\*8192
3072\*4096\*3072

**Comment by LiyangLingIntel** [comment]
Summarize the difference gap with examples to slides [Gemm_diff_to_XETLA_SIMT](https://intel-my.sharepoint.com/:p:/r/personal/liyang_ling_intel_com/Documents/Documents/DSE/Gemm_diff_to_XETLA_SIMT.pptm?d=w39f80018375d4b97925f793f2c41060b&csf=1&web=1&e=gKC1CB)
