### ISSUE TITLE
[Performance] Requirements to IGC to export more GenISA intrinsic for performance

### ISSUE THREAD

**Issue by chengjunlu** [intel/intel-xpu-backend-for-triton#1171]
There are useful intrinsic in GenISA which is good for performance.

- WaveAll
https://github.com/intel/intel-graphics-compiler/blob/f31f7b83b202426b1aedaaa60e768d230f2441d1/IGC/GenISAIntrinsics/Intrinsic_definitions.py#L659

It can help Triton to express the horizontal simple reduce operation across the lanes in the warp.

- The horizontal reduce with WaveAll. ( sum on fp32)

```MLIR

%493 = llvm.mlir.constant(0 : i32) : i32
%494 = llvm.mlir.constant(0 : i8) : i8
%495 = llvm.call @llvm.genx.GenISA.WaveAll.f32(%492, %494, %493) : (f32, i8, i32) -> f32
```

- The horizontal reduce with ShuffleXor.

```MLIR

%466 = llvm.mlir.constant(16 : i32) : i32
%467 = llvm.call @_Z21sub_group_shuffle_xorfj(%408, %466) {passthrough = ["convergent"]} : (f32, i32) -> f32
%468 = llvm.fadd %408, %467  : f32
%469 = llvm.mlir.constant(8 : i32) : i32
%470 = llvm.call @_Z21sub_group_shuffle_xorfj(%468, %469) {passthrough = ["convergent"]} : (f32, i32) -> f32
%471 = llvm.fadd %468, %470  : f32
%472 = llvm.mlir.constant(4 : i32) : i32
%473 = llvm.call @_Z21sub_group_shuffle_xorfj(%471, %472) {passthrough = ["convergent"]} : (f32, i32) -> f32
%474 = llvm.fadd %471, %473  : f32
%475 = llvm.mlir.constant(2 : i32) : i32
%476 = llvm.call @_Z21sub_group_shuffle_xorfj(%474, %475) {passthrough = ["convergent"]} : (f32, i32) -> f32
%477 = llvm.fadd %474, %476  : f32
%478 = llvm.mlir.constant(1 : i32) : i32
%479 = llvm.call @_Z21sub_group_shuffle_xorfj(%477, %478) {passthrough = ["convergent"]} : (f32, i32) -> f32
%480 = llvm.fadd %477, %479  : f32
```

The IGC will materialize the WaveAll without the heavy register movement by ShuffleXor.
```LLVM
(W)     add (16|M0)              r20.0<1>:f    r16.0<1;1,0>:f    r18.0<1;1,0>:f   {Compacted,F@1}    // $148
(W)     add (8|M0)               r22.0<1>:f    r20.0<1;1,0>:f    r21.0<1;1,0>:f   {Compacted,F@1}    // $149 R{} IR{}{E:5,E:5,},  {BC=1}
(W)     mov (4|M0)               r23.0<1>:ud   r22.4<1;1,0>:ud                  {F@1}                // $150
(W)     add (4|M0)               r24.0<1>:f    r22.0<1;1,0>:f    r23.0<1;1,0>:f   {I@1}              // $150
(W)     add (1|M0)               r25.0<1>:f    r24.0<0;1,0>:f    r24.2<0;1,0>:f   {Compacted,F@1}    // $151
```

**Comment by chengjunlu** [comment]
It improves some kernel performance which requires the horizontal reduce with a large sub-group-size.

**Comment by chengjunlu** [comment]
It seems we need to use this one if we want to partially reduce the value in cluster lanes.
https://github.com/intel/intel-graphics-compiler/blob/d829f78121092808b121658031ab26b2ec3ff960/IGC/GenISAIntrinsics/Intrinsic_definitions.py#L675

**Comment by chengjunlu** [comment]
Fixed the bug in the integration of the WaveOp to reduce lowering.

We can get the correct result for now.

We need to use the WaveAll or WaveCluster depends on the lanes number to reduce.

**Comment by whitneywhtsang** [comment]
Can you try to use `work_group_reduce_add` defined in https://registry.khronos.org/OpenCL/sdk/3.0/docs/man/html/workGroupFunctions.html instead of `llvm.genx.GenISA.WaveAll`?

**Comment by whitneywhtsang** [comment]
Communicated to IGC team on reduction with interleave stride. Awaiting scoping from IGC team.

**Comment by whitneywhtsang** [comment]
OCL built-ins are now used for subgroup reduce in Triton, instead of WaveAll and WaveClustered GenISA intrinsic. 
A separate internal ticket is opened to track the effort to add interleave stride support.
