### ISSUE TITLE
Fix `test_assert` failures with `InternelLinkage`

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#1176]
Upstream commit https://github.com/triton-lang/triton/commit/708814624b1fde6271eda76b081dd35e4a0dc6c6 marked non declaration library functions with internal linkage. It causes `test_subprocess.py::test_assert` to fail at LLVM opt O3 pipeline, they pass at LLVM opt O0 pipeline.

This issue is to remove the workaround at
https://github.com/intel/intel-xpu-backend-for-triton/blob/323baad84ba35710e80904c7fbe92c009d61ae3a/python/src/llvm.cc#L450
```
          // FIXME: Temporary workaround to avoid marking SPIR_FUNC functions
          // with InternalLinkage, which causes test_subprocess.py::test_assert
          // to fail.
          if (fn.getCallingConv() == CallingConv::SPIR_FUNC)
            continue;
```

**Comment by hwnam831** [comment]
The static linkage is optimizing the device library functions (e.g. __devicelib_assert_fail). Function inlining and dead argument elimination is breaking the functionality. The bug is reported to IGC.
