### ISSUE TITLE
[GEN] Use cache control attribute for 2D block read OCL lowering

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#1233]

**Comment by sommerlukas** [comment]
@whitneywhtsang Can you provide some additional details on this task please?

Should it apply in the experimental path or on the fallback path?

Does the 2D block read already use cache control or should this be added from scratch?

**Comment by victor-eds** [comment]
Update: Testing with latest IGC locally. Cache controls are being lost at some point. Looking into it.

**Comment by whitneywhtsang** [comment]
> Update: Testing with latest IGC locally. Cache controls are being lost at some point. Looking into it. Looks like this is not our problem, but a bug (probably in the translator).

Potentially fixed by https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2599.

**Comment by victor-eds** [comment]
Above PR not merged yet. Tests run with local build of the translator passed.
