### ISSUE TITLE
Enable FP32 to BF16 conversion lowering for vectors

### ISSUE THREAD

**Issue by jopperm** [intel/intel-xpu-backend-for-triton#1266]
The lowering pipeline currently maps
```mlir
arith.truncf %0: tensor<8x16xf32> to tensor<8x16xbf16>
```
to
```mlir
llvm.fptrunc %100 : vector<8xf32> to vector<8xbf16>
```
which the SPIR-V translator mistakenly maps to
```
call spir_func <8 x half> @_Z13convert_half8Dv8_f(<8 x float> %200)
```

We already have relevant [code](https://github.com/intel/intel-xpu-backend-for-triton/blob/0099fc0767d97a0740edeb3a4c4940fa8a367944/third_party/intel/lib/TritonIntelGPUToLLVM/ElementwiseOpToLLVM.cpp#L1304) for the "manual" conversion, though this needs to be extended to call the correct builtins for vector types. We should also consider switching to the corresponding OpenCL builtins: https://registry.khronos.org/OpenCL/extensions/intel/cl_intel_bfloat16_conversions.html#_new_opencl_c_functions

**Comment by FMarno** [comment]
Is this related to #1282?

**Comment by victor-eds** [comment]
Update: PR ready to merge. @jopperm confirmed this fixes integration tests where he found the error.
