### ISSUE TITLE
Enable the large 2D load for dot operands

### ISSUE THREAD

**Issue by vlad-penkin** [intel/intel-xpu-backend-for-triton#1323]

**Comment by chengjunlu** [comment]
The code is going to be submitted in several PRs:
[Add repCluster field to the DPAS layout.](https://github.com/intel/intel-xpu-backend-for-triton/pull/1480/commits/2ea04f388c3aafd34c894ad0c856e60cb6c5ca54)
[SharedToDotOperandDPAS.cpp changes to support repCluster.](https://github.com/intel/intel-xpu-backend-for-triton/pull/1480/commits/4cd065addcb5bf497e9b77b659f700bf153b6c24)
[ConvertLayoutOpToLLVM.cpp changes to support repCluster DPAS layout c…](https://github.com/intel/intel-xpu-backend-for-triton/pull/1480/commits/0b5fe1295259e298efb91816a2eb0c78658deddf)
[Utility.h changes to support repCluster in Dot layout emitOffset/emit…](https://github.com/intel/intel-xpu-backend-for-triton/pull/1480/commits/04c87193b9312599f7c382e5b219869ea2111512)
[DPAS.cpp changes to support repCluster in DPAS layout.](https://github.com/intel/intel-xpu-backend-for-triton/pull/1480/commits/dda8dccc05c66188acae64572c4a8597091c11b7)
[Enable the large 2D load.](https://github.com/intel/intel-xpu-backend-for-triton/pull/1480/commits/2fc220d22be2866cb5293f5db01e0957446d02d6)
[Support repetition cluster in 2D store.](https://github.com/intel/intel-xpu-backend-for-triton/pull/1480/commits/10e92f9a7ae5b4f7bf48bd1d27069f53c4ecf5b2)
[Use the cluster size > 1 in accelerate matmul.](https://github.com/intel/intel-xpu-backend-for-triton/pull/1480/commits/d6cb4615c1ecc14a11b3a1442253b20c03f3a36c)
[unit test case changes for repCluster](https://github.com/intel/intel-xpu-backend-for-triton/pull/1480/commits/cb6770162d4a368b47e41723de37d72d37665b0b)
