### ISSUE TITLE
[PT2.3] resnet50 dynamo perf regression up to 99%

### ISSUE THREAD

**Issue by xiaowangintel** [intel/intel-xpu-backend-for-triton#1347]
Hi, team, we got perf regression of resnet50 training with dynamo for pytorch2.3 on pvc. And, we found the pref regression caused by low perf triton kernel. And we found that the costs time for all triton kernel on regression are longer than normal. Detail information you can read https://jira.devtools.intel.com/browse/PYTORCHDGQ-4519?filter=-1
Debug log as below :

normal perf log:
![image](https://github.com/intel/intel-xpu-backend-for-triton/assets/109140002/fe13572f-0a7a-41dc-9fdc-0f785e9493f2)
![image](https://github.com/intel/intel-xpu-backend-for-triton/assets/109140002/3a7054a5-2747-4398-8809-c7f984e6d4f4)

regression log:
![image](https://github.com/intel/intel-xpu-backend-for-triton/assets/109140002/c42f8e1d-de0e-4375-b2be-66ea4c0284fa)
![image](https://github.com/intel/intel-xpu-backend-for-triton/assets/109140002/ff851ebd-8183-483d-8a20-2a91c902e3f3)

BKC:
1. cd https://github.com/intel-innersource/frameworks.ai.pytorch.gpu-models/tree/master/resnet50
2.  copy imagnet dataset(Consult val team)
3. python main.py -a resnet50 -b 128 --xpu 0 $dataset --num-iterations 20 --bf16 1 --dynamo --optimize

**Comment by riverliuintel** [comment]
@xiaowangintel  please triage which Triton kernel causes the performance regression and then submit.
