### ISSUE TITLE
~600 of the Triton tests are failing

### ISSUE THREAD

**Issue by aregm** [intel/intel-xpu-backend-for-triton#139]
https://github.com/openai/triton/tree/main/python/test/unit need to pass 100%

In order to complete this task we need to complete the following work items:
- #152
- #153
- #154 
- #155 
- #156 
- #157 
- #158 
- #159 
- #160 
- #161 
- #164 
- #167
- #191
- #205 
- #206 
- #212
- #213
- #251
- #253
- #255
- #256
- #257
- #261
- #291
- #311
- #312
- #377 
- #381 
- #435
- #500 
- #506
- #513
- #514
- #597 
- #598
- #601

**Comment by aregm** [comment]
Currently, around 10% of tests fail on the branch https://github.com/intel-sandbox/triton-dse. While it is being merged to the public branch, @tdeng5 can you please start triaging the failing tests into buckets and opening issues on them, so we can start working?

**Comment by etiotto** [comment]
@aregm I have already opened issues to track the work required for this large work item. I have added to the description links to the various work items that collectively resolve this one.

**Comment by tdeng5** [comment]
A task was created to collect the UT fails status: https://github.com/intel/intel-xpu-backend-for-triton/issues/223

**Comment by etiotto** [comment]
Assigning @whitneywhtsang  and myself as lead for this work item. We will distribute subtasks as needed while bringing the rest of the team up to speed.

**Comment by vlad-penkin** [comment]
@etiotto i suggest to close this ticket and just track the remaining open tickets.
