### ISSUE TITLE
[Pytorch Upstream] Pytorch UT (test/test_multiprocessing_spawn.py:SpawnTest.test_terminate_signal) regression introduced by triton

### ISSUE THREAD

**Issue by etaf** [intel/intel-xpu-backend-for-triton#1408]
Recently we tried to upgrade triton to resovle the two E2E model bfloat16 accuracy issue (https://github.com/intel/torch-xpu-ops/issues/408, https://github.com/intel/torch-xpu-ops/issues/414)  , but when upgrade triton from aac14a3b93f11d781d1d5ebc5400b15ae8df5185 to 4240f1c0400eeed9c06ba312545d9214aefee360 , the Pytorch UT  (test/test_multiprocessing_spawn.py:SpawnTest.test_terminate_signal) failed.
I've also tried the latest commit in llvm-target branch, also failed.

The root cause is the same with this OpenAI triton issue: https://github.com/triton-lang/triton/issues/4129
And it's resolved by expliciting export an env var ` TRITON_DISABLE_PYTHON_STACKTRACE` in PR https://github.com/triton-lang/triton/pull/4130 . However this is still a regression, It changed the default beheavior. So I'm asking which is the right way to do it, fixing this regression, or if we have to add this environment variable when running Pytorch UT. Since it changes Pytorch's behavior (raises exception when receive SIGABRT), I'd probably be more inclined to talk to OpenAI triton about fixing this regression.

### To reproduce:

1. Build stock pytorch.

2. python test/test_multiprocessing_spawn.py -k SpawnTest.test_terminate_signal

Nothing related to other envrionment.

**Comment by alexbaden** [comment]
We will investigate, I would add the environment variable for now - presumably upstream PyTorch will have to add it as well. Or, you could update to a commit just before the problematic commit was synced from upstream - https://github.com/triton-lang/triton/commit/0c5d1db1a58bcd24a8303bb9191f73905f1686fc

**Comment by etaf** [comment]
@alexbaden the latest commmit just before the problematic commit was synced from upstream - https://github.com/triton-lang/triton/commit/0c5d1db1a58bcd24a8303bb9191f73905f1686fc can not resolve the two E2E model bfloat16 accuracy issue. .Anyway, I'll use the TRITON_DISABLE_PYTHON_STACKTRACE  first.

**Comment by alexbaden** [comment]
Should be fixed in our repo w/ 0ef1848949d5008a053cf556e181012bcc6166bc
