### ISSUE TITLE
[UT] Wrong cases calculation when in TEST_UNSKIP mode

### ISSUE THREAD

**Issue by AshburnLee** [intel/intel-xpu-backend-for-triton#1412]
Request from https://github.com/intel/intel-xpu-backend-for-triton/pull/1345#:~:text=edited-,In%20both%20modes%2C%20it%20must%20be%20the%20same%20total%20number%20of,this%20PR%20and%20I%27ll%20solve%20pass_rate.py%20bug%20in%20another%20PR%3F,-Merge%20state

**Comment by vlad-penkin** [comment]
@AshburnLee is this issue fixed?

**Comment by AshburnLee** [comment]
> @AshburnLee is this issue fixed?

Will fix in my current PR https://github.com/intel/intel-xpu-backend-for-triton/pull/1345, no need to track in a new issue
