### ISSUE TITLE
[RAISE-BP] Add support for `tt.broadcast` increasing tensor rank

### ISSUE THREAD

**Issue by victor-eds** [intel/intel-xpu-backend-for-triton#1429]
#1428 adds support for `tt.broadcast` operations between tensor types of the same rank. Increasing ranks is not yet supported. Extend pass to support this flavor of `tt.broadcast` operations as `tt.addptr` inputs, e.g.:

```
tt.broadcast %in : tensor<512xf32> -> tensor<2x512xf32>
```

**Comment by mfrancepillois** [comment]
PR open and partially approved.
