### ISSUE TITLE
[RAISE-BP] Conditionaly enable `-triton-raise-block-pointer` pass in the pipeline

### ISSUE THREAD

**Issue by victor-eds** [intel/intel-xpu-backend-for-triton#1430]
Conditionally enable `-triton-raise-block-pointer` in the pipeline for evaluation, e.g., if `TRITON_RAISE_BLOCK_POINTER` env variable is set. This will enable both functional and performance evaluation.

In case bugs are found when the pass is enabled, create follow up issues to fix these.

**Comment by mfrancepillois** [comment]
Picked the task recently. Work in progress.

**Comment by mfrancepillois** [comment]
Draft PR open. Wait for more stable pass before activating this pass by default.

**Comment by mfrancepillois** [comment]
Draft PR open. Wait for more stable pass before activating this pass by default.

**Comment by mfrancepillois** [comment]
Draft PR open. Still waiting for more stable pass before activating this pass by default.

**Comment by mfrancepillois** [comment]
Draft PR open. Still waiting for more stable pass before activating this pass by default.

**Comment by mfrancepillois** [comment]
Draft PR open. Still waiting for more stable pass before activating this pass by default.

**Comment by mfrancepillois** [comment]
Draft PR open. Still waiting for more stable pass before activating this pass by default.

**Comment by mfrancepillois** [comment]
The pass would probably not reach the stability required to be activated by default soon.
The associated PR has been closed. IMO, the issue could also be closed. Activation of the pass will be reconsidered in the future depending on the evolution of this pass.

**Comment by victor-eds** [comment]
Closing as per:

> The pass would probably not reach the stability required to be activated by default soon. The associated PR has been closed. IMO, the issue could also be closed. Activation of the pass will be reconsidered in the future depending on the evolution of this pass.
