### ISSUE TITLE
[RAISE-BP] Handle `scf.for`

### ISSUE THREAD

**Issue by victor-eds** [intel/intel-xpu-backend-for-triton#1433]
We currently handle `tt.load`, `tt.store` and `tt.addptr` in the pass (and operands to `tt.addptr`). Handle `scf.for` too. Take inspiration from `triton-shared`.

How this is to be handled is part of the ticket itself. No previous investigation, so missing context here.

**Comment by mfrancepillois** [comment]
If load/store ops in a `for` loop are translated from unstructured to structured load/store, the loop must be rewritten and the list of args must be extended to include new args related to block pointers.
e.g.
`
scf.for (%tensor_of_ptr) {
    %data = tt.load %tensor_of_ptr
    // more operations to update %tensor_of_ptr
}
`
should be rewritten as follow:
`
scf.for (%base_ptr, %stride, %offset) {
    %tensor_of_ptr = tt.make_block_ptr(%base_ptr, %stride, %offset)
    %data = tt.load %tensor_of_ptr
    // more operations to update %offset
}
`

This issue aims to extend the `raise-block-ptr` pass to support cases where load and store operations are contained in a `scf::forOp` loop.

**Comment by mfrancepillois** [comment]
Work in progress

**Comment by mfrancepillois** [comment]
PR approved by Codeplay. Waiting for Intel approval.
