### ISSUE TITLE
[RAISE-BP] Add support for `arith.remsi|remui` as `tt.addptr` input

### ISSUE THREAD

**Issue by victor-eds** [intel/intel-xpu-backend-for-triton#1436]
`arith.remsi|remui` should be handled as `tt.addptr` inputs as `triton-shared` does. This would require high level of modification of the pass, as there are cases we are not handling because we do not care about this (see `triton-shared` pass).

We may first want to do an evaluation of how common this case is in our benchmark suite before putting the effort.

Take inspiration from `triton-shared` if we decide going for it or reject this issue otherwise.

**Comment by mfrancepillois** [comment]
PR in review.

**Comment by mfrancepillois** [comment]
PR in review. Need to investigate how to smartly handle address modulo (see https://github.com/intel/intel-xpu-backend-for-triton/pull/1570#discussion_r1668350718 ), as it is required to enable real use cases.

**Comment by mfrancepillois** [comment]
Work in progress. We need to find a safe solution for handling modulos.

**Comment by mfrancepillois** [comment]
Work in progress. We need to find a safe solution for handling modulos.

**Comment by mfrancepillois** [comment]
Issue https://github.com/intel/intel-xpu-backend-for-triton/issues/1784 has been created to address the modulo handling issue.
The PR associated to this issue is just waiting for approval.
