### ISSUE TITLE
Add switches to conda workflow runs

### ISSUE THREAD

**Issue by leshikus** [intel/intel-xpu-backend-for-triton#1469]
Create switches for conda workflow runs:

> Runner label, keep empty for default
> Install Intel PyTorch Extension
> PyTorch ref, keep empty for default
> Upload test reports
> Ignore test errors
> Custom run name

**Comment by vlad-penkin** [comment]
@leshikus is this issue fixed?

cc: @pbchekin

**Comment by leshikus** [comment]
I'm still working on it.

**Comment by pbchekin** [comment]
All inputs have been added to conda-test.
