### ISSUE TITLE
Conversion code for `triton_gpu.async_wait` 

### ISSUE THREAD

**Issue by etiotto** [intel/intel-xpu-backend-for-triton#147]
When the target is NVIDIA, the `triton_gpu.async_wait` operation is lowered to the following inline asm:
```
%2 = "llvm.inline_asm"() {asm_dialect = 0 : i64, asm_string = "cp.async.wait_group 0x4;", constraints = "", has_side_effects, operand_attrs = []} : () -> !llvm.void
```
We need to support for the equivalent operation of [cp.async.wait_group](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#data-movement-and-conversion-instructions)

The `cp.async.wait_group` instruction waits for completion of prior asynchronous copy operations. The syntax is:
```
cp.async.wait_group N;
```
The instruction will cause the executing thread to wait till only N or fewer of the most recent cp.async-groups are pending and all the prior cp.async-groups committed by the executing threads are complete. For example, when N is 0, the executing thread waits on all the prior cp.async-groups to complete. Operand N is an integer constant.

**Comment by vlad-penkin** [comment]
@etiotto can we close this ticket?

**Comment by etiotto** [comment]
yes
