### ISSUE TITLE
Use Triton kernel driver library for `SPIRVRunner`

### ISSUE THREAD

**Issue by alexbaden** [intel/intel-xpu-backend-for-triton#1472]
Currently we duplicate generated runner code from `driver.py` in the `SPIRVRunner`. It would be interesting to try and use the generated code from the `.so` file, linking the library and calling the kernel code from within it. This would avoid nearly all code duplication between the runner and the Triton runtime.

**Comment by kballeda** [comment]
This issue reflects on re-using the code for - "sycl_kernel_launcher" function from drivery.py as part of SPIRVRunner. 

driver.py:
https://github.com/intel/intel-xpu-backend-for-triton/blob/d76446a8fc1478d42a82562362709a182db2f1be/third_party/intel/backend/driver.py#L310 

SPIRVRunner Reference: 
https://github.com/intel/intel-xpu-backend-for-triton/blob/d76446a8fc1478d42a82562362709a182db2f1be/utils/SPIRVRunner/SPIRVRunner.cpp#L183 

Essentially the entry points for kernel arguments are coming **python c++ interface bindings** in drivery.py whereas as part of **SPIRVRunner we deserialize the JSON** information related to kernel arguments. Currently this PR - #2258 handles the serialization/de-serialization process and following is the modified interface of sycl_kernel_launcher. 

https://github.com/intel/intel-xpu-backend-for-triton/blob/5805c71a91270d6ab9c0361d3be046894dbea92f/utils/SPIRVRunner/SPIRVRunner.cpp#L225

Made some investigation on sycl_kernel_launch export status as part of driver.py. By default it is not exported global. Removing static keyword would enable it to be exposed to global scope and this step required for set_scalar_args function as well. 

```

intel-xpu-backend-for-triton$ nm -D __triton_launcher.so | grep sycl_kernel_launch
00000000000035a0 T _Z18sycl_kernel_launchjjjiiiRN4sycl3_V15queueERNS0_6kernelEPviiS5_iiS5_iiS5_ii
```

I had written a test function to check if sycl_kernel_launch can be used with dummy args data, 

```
intel-xpu-backend-for-triton$ ./myfunc 
Cannot open library: ./__triton_launcher.so: undefined symbol: PyExc_ValueError
intel-xpu-backend-for-triton$ nm -D __triton_launcher.so | grep PyExc_ValueError
                 U PyExc_ValueError
```

Following are my observations: 

1. Modify driver.py source to globally expose the sycl_kernel_launch by removing static or export "C". 
2. PyExc_Value is coming from a different .so file that needs to be figured out and linked 
3.  We need to find a way to set our deserialized structure from SPIRVRunner  to sycl_kernel_launch() c++ function that takes kernelArguments in python syntax - `{',' + ', '.join(f"ptr_info{i}.dev_ptr" if ty[0]=="*" else f"_arg{i}" for i, ty in signature.items()) if len(signature) > 0 else ''}`  as part of .so

@alexbaden: This needs changes as part of driver.py and we could easily sync sycl_kernel_launch as its only job is to setup the kernel launch parameters (data driven) and launch kernel, not expecting drastic modifications. Any thoughts on this?

**Comment by alexbaden** [comment]
Let's start by looking at how we can refactor the launch code in `driver.py` to separate out the SYCL-only parts. PyTorch AOT Inductor will also be using SYCL launch code for running Triton kernels outside of Triton: https://github.com/pytorch/pytorch/pull/135318/files#diff-2bbc58fcef7d498ae6d81ce8751f411d60ce5c4e8da9aa8dd95ccd29b64a1ba8 
Perhaps we can find some commonality between AOT Inductor needs, SPIRV Runner needs, and Triton needs?

**Comment by kballeda** [comment]
@alexbaden - Thanks for your pointers. Can you please share pointers on AOT inductor. Also, as the scope of this git issue widens @vlad-penkin it's good to move this issue to next iteration.

**Comment by alexbaden** [comment]
The pointer to the AOT inductor code is in the link above. 

This is a narrowing of the scope of this issue, not an expansion. If you want to make a new issue for the narrower scope, please feel free.

**Comment by kballeda** [comment]
> The pointer to the AOT inductor code is in the link above.
> 
> This is a narrowing of the scope of this issue, not an expansion. If you want to make a new issue for the narrower scope, please feel free.

@alexbaden  Sure will do that, thanks for clarification. I am looking for a wiki page about AOT.

**Comment by kballeda** [comment]
> The pointer to the AOT inductor code is in the link above.
> 
> This is a narrowing of the scope of this issue, not an expansion. If you want to make a new issue for the narrower scope, please feel free.

As per the investigation and narrowed scope, this new ticket is filed https://github.com/intel/intel-xpu-backend-for-triton/issues/2395 to investigate commonality in each of the flows and refactor the driver.py accordingly.
