### ISSUE TITLE
[Security][CI] Add regular Bandit scan to the intel specific Python code

### ISSUE THREAD

**Issue by vlad-penkin** [intel/intel-xpu-backend-for-triton#1476]
Ideally we should run it against each PR

**Comment by AshburnLee** [comment]
Are we plan to check ALL python files in the Repo or just those added/modified in the current change?
I plan to check python files added/modified in the current change, and for modified python files I'll only check changed part instead of the all file.

Are we agree on this?

**Comment by AshburnLee** [comment]
I think we have to decide this at the first place:
https://github.com/intel/intel-xpu-backend-for-triton/pull/1878#discussion_r1718159251

**Comment by AshburnLee** [comment]
As discussed with Pavel, I decide to this in 2 steps:
1. [wip] Nightly scan focuses on scanning downstream files with a reasonable bandit configuration and upload the report: https://github.com/intel/intel-xpu-backend-for-triton/pull/1878
2. [hold] Define a more strict configuration and enable Bandit in pre-commit against each PR

**Comment by AshburnLee** [comment]
Update：
[done] Nightly scan focuses on scanning downstream files with a reasonable bandit configuration and upload the report: https://github.com/intel/intel-xpu-backend-for-triton/pull/1878
[wip] remove 'assert' in related python code
[wip] investigate xml related issues
[hold] Define a more strict configuration and enable Bandit in pre-commit against each PR
