### ISSUE TITLE
[RAISE-BP] Addressed dimensions coming from non-folded arithmetic operations in `dimHasModulo`

### ISSUE THREAD

**Issue by victor-eds** [intel/intel-xpu-backend-for-triton#1482]
#1481 introduced `dimHasModulo`, which may not work if the defining operation is not `arith.constant`. Try to address this issue.

Note our current implementation may generate:
```
%c0 = arith.constant 0 : i64
%c1 = arith.constant 1 : i64
%0 = arith.muli %c0, %c1 : i64
```

**Comment by mfrancepillois** [comment]
PR in review.

**Comment by mfrancepillois** [comment]
PR in review.

**Comment by mfrancepillois** [comment]
Work in progress. We need to find a safe solution for handling modulos.

**Comment by mfrancepillois** [comment]
Issue https://github.com/intel/intel-xpu-backend-for-triton/issues/1784 has been created to address the modulo handling issue.
The PR associated to this issue is just waiting for approval.
