### ISSUE TITLE
[CI]: Enhance basic integration tests

### ISSUE THREAD

**Issue by etiotto** [intel/intel-xpu-backend-for-triton#149]
Work item https://github.com/intel/intel-xpu-backend-for-triton/issues/144 establishes the base integration tests (CI) for the Triton compiler generating LLVM IR. This work item has the goal to enhance CI to make it closer to the CI system utilized upstream. 

As inspiration for this work item we should analyze the following workloads and determine whether we want to adopt them as part of CI:
  - https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/7179062821/job/19582991867?pr=137
  - https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/7179062815/job/19550417230?pr=137

**Comment by vlad-penkin** [comment]
Blocked by #139

**Comment by vlad-penkin** [comment]
This ticket consists of two parts, which are currently tracked separately. Closing as a duplicate.

The UT part of this ticket is tracked here:
- #471 

The E2E UT part of this ticket is tracked here:
- #419
