### ISSUE TITLE
[FE]: Use SYCL runtime rather than L0 in Triton FE/driver

### ISSUE THREAD

**Issue by etiotto** [intel/intel-xpu-backend-for-triton#150]
Rewrite the Triton FE code we have ported to use the SYCL runtime rather than the L0 runtime.

**Comment by etiotto** [comment]
@pengtu here is the work item for Sabuchi?

**Comment by whitneywhtsang** [comment]
Reopen to track the remaining cleanup work.

**Comment by vlad-penkin** [comment]
@whitneywhtsang closing this ticket. New issue have been created for the remaining cleanup work:
- #472 

Please provide more information in the new ticket on what needs to be done.

**Comment by whitneywhtsang** [comment]
> @whitneywhtsang closing this ticket. New issue have been created for the remaining cleanup work:
> 
> * [[FE]: Use SYCL runtime - remaining cleanup work #472](https://github.com/intel/intel-xpu-backend-for-triton/issues/472)
> 
> Please provide more information on what needs to be done in the new ticket .

Closed the new issue after linking the two cleanup PRs.
