### ISSUE TITLE
[PyTorch] Update PyTorch and IPEX commit pin to PyTorch 2.3 

### ISSUE THREAD

**Issue by LiyangLingIntel** [intel/intel-xpu-backend-for-triton#1519]
Current IPEX has moved to PyTorch 2.3, current CI PyTorch and IPEX commits still pin to PT 2.1 which is no longer maintained.
Triton should update the CI commit pin and co corresponding changes.

**Comment by LiyangLingIntel** [comment]
These features should be backported to PT 2.3
* [Check extension supportance via `ext_oneapi_supports_cl_extension`](https://github.com/intel/intel-extension-for-pytorch/commit/e66d1aa4992a74d7d8eb1b2056af095851eb8b24)
* [Add device architecture to DeviceInfo](https://github.com/intel/intel-extension-for-pytorch/commit/e22924d77b478e1c4c37d36861e36a6b05b9274c)

**Comment by vlad-penkin** [comment]
@LiyangLingIntel we switching to the upstream PyTorch 2.4. No plans to support PyTorch 2.3 and corresponding IPEX version.

CC: @aregm
