### ISSUE TITLE
[CI] Sending emails after a workflow is done 

### ISSUE THREAD

**Issue by AshburnLee** [intel/intel-xpu-backend-for-triton#1555]
Do we need a feature as the title described?
For example, when workflows like `E2E accuracy` OR `E2E performance` are done, sending a email to team members. In order to inform teams with the status of the workflow and the artifacts and URL.
@whitneywhtsang mentioned it, @pbchekin @vlad-penkin any thoughts?

**Comment by whitneywhtsang** [comment]
Instead of always sending emails, I prefer to get notified only if the results are unexpected.

**Comment by pbchekin** [comment]
I don't think we need this right now.

**Comment by AshburnLee** [comment]
@pbchekin As you mentioned in the discussion, I assume this monitoring using Grafana alerting is planned to do, so I reopen this issue tracking that.
