### ISSUE TITLE
[PyTorch Upstream] do_bench functionaliy error

### ISSUE THREAD

**Issue by etaf** [intel/intel-xpu-backend-for-triton#1563]
Hi, we found two implementation issues in triton's `do_bench`  when  enabling max-autotune feature in Pytorch.

1. `do_bench` should return the number of `ms` , but currently is `ns`.
 https://github.com/intel/intel-xpu-backend-for-triton/blob/1b2f15840e0d70eec50d84c7a0575cb835524def/python/triton/testing.py#L12-L21
2. In `do_bench` , if `USE_WALL_TIME`, there should be a `synchronize()` between start/end time record, But currently is not.
https://github.com/intel/intel-xpu-backend-for-triton/blob/1b2f15840e0d70eec50d84c7a0575cb835524def/python/triton/testing.py#L139-L148

**Comment by etaf** [comment]
@alexbaden  can you help to check?

**Comment by whitneywhtsang** [comment]
@etaf Please verify. Do you also need this change to be backported to the release branch?

**Comment by etaf** [comment]
@whitneywhtsang Sorry for my late update, thanks for your work, and currently no need to backport to the release branch.
