### ISSUE TITLE
Request PyTorch team to port device properties to the PyTorch main branch

### ISSUE THREAD

**Issue by LiyangLingIntel** [intel/intel-xpu-backend-for-triton#1576]
Triton current device properties query depends on the old PyTorch 2.1 dev branch [dev/triton-test-3.0](https://github.com/intel/intel-extension-for-pytorch/commits/dev/triton-test-3.0/). 
```python
# list of device properties which are not ported
[
"dpcpp_dev_architecture",
"cl_intel_subgroup_matrix_multiply_accumulate",
"cl_intel_subgroup_matrix_multiply_accumulate_tensor_float32",
"cl_intel_subgroup_2d_block_io"
]
```
Which are included in these 2 commits:
* [Check extension supportance via ext_oneapi_supports_cl_extension](https://github.com/intel/intel-extension-for-pytorch/commit/e66d1aa4992a74d7d8eb1b2056af095851eb8b24)
* [Add device architecture to DeviceInfo](https://github.com/intel/intel-extension-for-pytorch/commit/e22924d77b478e1c4c37d36861e36a6b05b9274c)

Before moving to PyTorch 2.4, we need to request PyTorch team help to port these properties to Stock PyTorch.

**Comment by vlad-penkin** [comment]
@riverliuintel a clarification - @LiyangLingIntel was referring to the PyTorch main branch, not PyTorch 2.4 release branch.

**Comment by ZzEeKkAa** [comment]
I believe that [Add device architecture to DeviceInfo](https://github.com/intel/intel-extension-for-pytorch/commit/e22924d77b478e1c4c37d36861e36a6b05b9274c) was ported at https://github.com/pytorch/pytorch/pull/129675

**Comment by LiyangLingIntel** [comment]
> I believe that [Add device architecture to DeviceInfo](https://github.com/intel/intel-extension-for-pytorch/commit/e22924d77b478e1c4c37d36861e36a6b05b9274c) was ported at [pytorch/pytorch#129675](https://github.com/pytorch/pytorch/pull/129675)

Thanks for porting the `device_arch` to upstream. 
So we have these 3 to be upstream:
```python
[
"cl_intel_subgroup_matrix_multiply_accumulate",
"cl_intel_subgroup_matrix_multiply_accumulate_tensor_float32",
"cl_intel_subgroup_2d_block_io",
]
```

**Comment by riverliuintel** [comment]
Assign to Yu, guangye to check whether there is any dependency on current PyTorch bundle.

**Comment by ZzEeKkAa** [comment]
I've been playing around cl extension so this may be a good start point: https://github.com/ZzEeKkAa/pytorch/commit/8a093e63153095f8b7f9665b5471df54e55b1174

**Comment by guangyey** [comment]
@ZzEeKkAa Thanks for your ideas, I have submitted a PR https://github.com/pytorch/pytorch/pull/131738
Currently, we are going to support the ABI=0 build for PyTorch XPU, see https://github.com/pytorch/pytorch/pull/130110
But I found that `ext_oneapi_supports_cl_extension` seems not a ABI-netural API. We have to postpone https://github.com/pytorch/pytorch/pull/131738 which depends on compiler 2025.0 or newer.

**Comment by YarShev** [comment]
@guangyey, am I correct that we can't move from IPEX usage to upstream pytorch until compiler 2025.0 is out?

**Comment by guangyey** [comment]
Yes, you are right. By the way, I hear that the [fix](https://github.com/intel/llvm/pull/13212) has been merged into 2024.1. Perhaps, we can land https://github.com/pytorch/pytorch/pull/131738 early.

**Comment by riverliuintel** [comment]
This stock PyTorch PR merge should depends on PyTorch bundle 0.5.3 public release and upgrade in PyTorch CI/CD. @guangyey  check with Chuanqi on CI/CD progress. I think the general date should be in WW34

**Comment by guangyey** [comment]
> This stock PyTorch PR merge should depends on PyTorch bundle 0.5.3 public release and upgrade in PyTorch CI/CD. @guangyey check with Chuanqi on CI/CD progress. I think the general date should be in WW34

OK.

**Comment by vlad-penkin** [comment]
PyTorch bundle 0.5.3 was publicly released on 8/12, Are we still on track to merge this PR within a week?

**Comment by ZzEeKkAa** [comment]
@vlad-penkin I suppose this particular may be closed, since https://github.com/pytorch/pytorch/pull/131738 was merged and architecture use was eliminated.
