### ISSUE TITLE
Verify Agama Rolling & LTS with PTDB 0.5.2

### ISSUE THREAD

**Issue by pbchekin** [intel/intel-xpu-backend-for-triton#1630]

**Comment by AshburnLee** [comment]
I'll find machines then for Rolling & LTS do the following:
1. Run standard workflow to verify if there are FAILED cases in the current scope.
2. Run only skiplist to verify if there are PASSED cases.

**Comment by AshburnLee** [comment]
There are FAILED cases on Rolling with PTDB 0.5.2:
106 in Language test, 9 in Regression test:
```
FAILED language/test_core.py::test_noinline[shared] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-64-64-64-4-False-False-none-tf32-float32-float32-1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-16-16-16-4-False-False-chain-dot-tf32-float32-float32-1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-64-64-64-4-False-False-trans-tf32-float32-float32-1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-64-64-64-4-False-False-add-matrix-tf32-float32-float32-1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-32-128-64-4-True-True-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-128-256-32-8-True-True-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-64-64-64-4-False-False-add-rows-tf32-float32-float32-1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-32-128-64-4-True-True-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-128-256-32-8-True-True-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-64-64-64-4-False-False-add-cols-tf32-float32-float32-1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-32-128-64-4-True-False-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-128-256-32-8-True-False-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-64-64-64-4-False-False-softmax-tf32-float32-float32-1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-32-128-64-4-True-False-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-128-256-32-8-True-False-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-64-64-64-4-False-False-chain-dot-tf32-float32-float32-1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-32-32-32-4-False-False-none-tf32-float32-float32-1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-128-256-32-8-False-True-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-32-128-64-4-False-True-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-32-128-64-4-False-True-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-64-64-32-4-False-True-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-128-256-32-8-False-True-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-32-32-32-4-False-False-trans-tf32-float32-float32-1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-32-32-32-4-False-False-add-matrix-tf32-float32-float32-1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-128-256-32-8-False-False-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-32-128-64-4-False-False-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-64-64-32-4-False-False-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-32-128-64-4-False-False-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-64-64-32-4-False-False-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-128-256-32-8-False-False-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-32-32-32-4-False-False-add-rows-tf32-float32-float32-1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-128-128-64-4-True-True-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-32-32-32-4-False-False-add-cols-tf32-float32-float32-1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-128-16-32-4-True-True-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-32-32-128-16-True-True-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-128-128-64-4-True-True-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-32-32-128-16-True-True-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-128-16-32-4-True-True-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-32-32-32-4-False-False-softmax-tf32-float32-float32-1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-128-16-32-4-True-False-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-32-32-32-4-False-False-chain-dot-tf32-float32-float32-1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-128-128-64-4-True-False-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-128-128-64-4-True-False-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-32-32-128-16-True-False-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-128-16-32-4-True-False-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-32-32-128-16-True-False-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-16-16-16-4-False-False-none-tf32-float32-float32-1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_join_with_mma - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-128-16-32-4-False-True-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-16-16-16-4-False-False-trans-tf32-float32-float32-1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-128-128-64-4-False-True-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-32-32-128-16-False-True-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-128-128-64-4-False-True-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-128-16-32-4-False-True-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-16-16-16-4-False-False-add-matrix-tf32-float32-float32-1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-32-32-128-16-False-True-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-128-16-32-4-False-False-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-16-16-16-4-False-False-add-rows-tf32-float32-float32-1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-128-128-64-4-False-False-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-32-32-128-16-False-False-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-128-16-32-4-False-False-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-128-128-64-4-False-False-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-16-16-16-4-False-False-add-cols-tf32-float32-float32-1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-32-32-128-16-False-False-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-64-128-128-4-True-False-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000011
FAILED language/test_core.py::test_dot[1-16-16-16-4-False-False-softmax-tf32-float32-float32-1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-64-128-128-4-True-True-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-64-128-128-4-True-False-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000011
FAILED language/test_core.py::test_dot[1-128-128-64-2-True-True-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000011
FAILED language/test_core.py::test_dot[1-64-128-128-4-True-True-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-128-128-64-2-True-True-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000011
FAILED language/test_core.py::test_dot_without_load[float32] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_masked_load_shared_memory[dtype2] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-64-128-128-4-False-True-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-128-128-64-2-False-False-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-128-128-64-2-True-False-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-64-128-128-4-False-True-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-128-128-64-2-False-False-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-128-128-64-2-True-False-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-64-128-128-4-False-False-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-128-128-64-2-False-True-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-64-128-128-2-True-True-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-64-128-128-4-False-False-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-128-128-64-2-False-True-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-64-128-128-2-True-True-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-32-128-64-2-True-True-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-32-128-64-2-True-True-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-64-128-128-2-True-False-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000011
FAILED language/test_core.py::test_dot[1-64-128-128-2-True-False-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000011
FAILED language/test_core.py::test_dot[1-32-128-64-2-True-False-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-32-128-64-2-True-False-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-64-128-128-2-False-True-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-64-128-128-2-False-True-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-32-128-64-2-False-True-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-32-128-64-2-False-True-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-64-128-128-2-False-False-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000011
FAILED language/test_core.py::test_dot[1-64-128-128-2-False-False-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000011
FAILED language/test_core.py::test_dot[1-32-128-64-2-False-False-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-32-128-64-2-False-False-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot_mulbroadcasted[float32] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-64-64-32-4-True-True-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-64-64-32-4-True-True-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-64-64-32-4-True-False-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-64-64-32-4-True-False-none-tf32-float32-float32-1_1] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED language/test_core.py::test_dot[1-64-64-32-4-False-True-none-tf32-float32-float32-1_0] - RuntimeError: Triton Error [ZE]: 0x78000018
```
FAILED test_cast_matmul.py::test_cast_matmul[128-128-128-float32-float64-float32] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED test_cast_matmul.py::test_cast_matmul[128-128-128-float64-float32-float32] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED test_cast_matmul.py::test_cast_matmul[1280-768-1024-float32-float64-float32] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED test_cast_matmul.py::test_cast_matmul[1280-768-1024-float64-float32-float32] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED test_functional_regressions.py::test_iv_dependent_matmul[pre_load] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED test_functional_regressions.py::test_iv_dependent_matmul[post_load] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED test_functional_regressions.py::test_iv_dependent_matmul[post_pre_mixed] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED test_functional_regressions.py::test_iv_dependent_matmul[post_load_two_iters] - RuntimeError: Triton Error [ZE]: 0x78000018
FAILED test_functional_regressions.py::test_iv_dependent_matmul[post_load_three_iters] - RuntimeError: Triton Error [ZE]: 0x78000018
```

```

**Comment by pbchekin** [comment]
> * No FAILED cases on **Rolling Agama 881(jupyterhub) with PTDB 0.5.2**

Please also validate with Agama 914.32 (in the newly added jupyterhub session).

**Comment by pbchekin** [comment]
> * **110** FAILED in Language test on **LTS Agama 803 (fox125) with PTDB 0.5.2** `RuntimeError: Triton Error [ZE]: 0x70000004`

Looks like at least some of the failed tests are in the lts skip list, for example:

> language/test_core.py::test_dot[1-64-128-128-4-False-True-none-tf32-float16-float32-1_0]

https://github.com/intel/intel-xpu-backend-for-triton/blob/llvm-target/scripts/skiplist/lts/language.txt#L94

Please re-validate with the lts skip list, or check if all failed tests are in the lts skip list.

**Comment by AshburnLee** [comment]
> 110 FAILED in Language test on LTS Agama 803 (fox125) with PTDB 0.5.2
Sorry, when on LTS, skiplist should have been specified before execution. So:
`TRITON_TEST_SKIPLIST_DIR=/PATH/TO/skiplist/lts ./scripts/test-triton.sh --ignoer-errors` 
There are no FAILED cases.

**Comment by AshburnLee** [comment]
> Please also validate with Agama 914.32 (in the newly added jupyterhub session).



<details>  
<summary>106 FAILED cases</summary>
FAILED language/test_core.py::test_noinline[shared] <br/>
FAILED language/test_core.py::test_join_with_mma <br/>
FAILED language/test_core.py::test_dot[1-16-16-16-4-False-False-add-cols-tf32-float32-float32-1] <br/>
FAILED language/test_core.py::test_dot[1-16-16-16-4-False-False-softmax-tf32-float32-float32-1] <br/>
FAILED language/test_core.py::test_dot[1-64-64-64-4-False-False-add-matrix-tf32-float32-float32-1] <br/>
FAILED language/test_core.py::test_dot[1-16-16-16-4-False-False-chain-dot-tf32-float32-float32-1] <br/>
FAILED language/test_core.py::test_dot[1-64-64-64-4-False-False-add-rows-tf32-float32-float32-1] <br/>
FAILED language/test_core.py::test_dot[1-64-64-32-4-False-False-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-64-64-32-4-False-False-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-64-64-64-4-False-False-none-tf32-float32-float32-1] <br/>
FAILED language/test_core.py::test_dot[1-32-32-128-16-True-True-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-32-32-128-16-True-True-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-64-64-64-4-False-False-add-cols-tf32-float32-float32-1] <br/>
FAILED language/test_core.py::test_dot[1-128-256-32-8-True-True-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-128-256-32-8-True-True-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-64-64-64-4-False-False-trans-tf32-float32-float32-1] <br/>
FAILED language/test_core.py::test_dot[1-32-32-128-16-True-False-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-32-32-128-16-True-False-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-64-64-64-4-False-False-softmax-tf32-float32-float32-1] <br/>
FAILED language/test_core.py::test_dot[1-128-256-32-8-True-False-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-128-256-32-8-True-False-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot_without_load[float32] <br/>
FAILED language/test_core.py::test_dot[1-32-32-128-16-False-True-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-32-32-128-16-False-True-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-64-128-128-4-True-True-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-32-32-128-16-False-False-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-64-128-128-4-True-True-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-32-32-128-16-False-False-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-64-64-64-4-False-False-chain-dot-tf32-float32-float32-1] <br/>
FAILED language/test_core.py::test_dot[1-128-256-32-8-False-True-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-128-256-32-8-False-True-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-32-32-32-4-False-False-none-tf32-float32-float32-1] <br/>
FAILED language/test_core.py::test_masked_load_shared_memory[dtype2] <br/>
FAILED language/test_core.py::test_dot[1-32-32-32-4-False-False-trans-tf32-float32-float32-1] <br/>
FAILED language/test_core.py::test_dot[1-128-256-32-8-False-False-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-128-256-32-8-False-False-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-32-32-32-4-False-False-add-matrix-tf32-float32-float32-1] <br/>
FAILED language/test_core.py::test_dot[1-128-16-32-4-True-True-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-64-128-128-4-True-False-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-64-128-128-4-True-False-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-128-16-32-4-True-True-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-32-32-32-4-False-False-add-rows-tf32-float32-float32-1] <br/>
FAILED language/test_core.py::test_dot[1-128-16-32-4-True-False-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-128-16-32-4-True-False-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-32-32-32-4-False-False-add-cols-tf32-float32-float32-1] <br/>
FAILED language/test_core.py::test_dot[1-128-16-32-4-False-True-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-32-32-32-4-False-False-softmax-tf32-float32-float32-1] <br/>
FAILED language/test_core.py::test_dot[1-128-16-32-4-False-True-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-32-32-32-4-False-False-chain-dot-tf32-float32-float32-1] <br/>
FAILED language/test_core.py::test_dot[1-128-16-32-4-False-False-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-128-16-32-4-False-False-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-16-16-16-4-False-False-none-tf32-float32-float32-1] <br/>
FAILED language/test_core.py::test_dot[1-16-16-16-4-False-False-trans-tf32-float32-float32-1] <br/>
FAILED language/test_core.py::test_dot[1-64-128-128-4-False-True-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-64-128-128-4-False-True-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-32-128-64-4-True-True-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-32-128-64-4-True-True-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-16-16-16-4-False-False-add-matrix-tf32-float32-float32-1] <br/>
FAILED language/test_core.py::test_dot[1-16-16-16-4-False-False-add-rows-tf32-float32-float32-1] <br/>
FAILED language/test_core.py::test_dot[1-128-128-64-2-True-True-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-128-128-64-2-True-True-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-32-128-64-4-True-False-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-32-128-64-4-True-False-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-32-128-64-4-False-True-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-32-128-64-4-False-True-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-32-128-64-4-False-False-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-32-128-64-4-False-False-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-64-128-128-4-False-False-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-64-128-128-4-False-False-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-32-128-64-2-True-True-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-32-128-64-2-True-True-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-128-128-64-4-True-True-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-128-128-64-4-True-True-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-32-128-64-2-True-False-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-32-128-64-2-True-False-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-128-128-64-4-True-False-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-128-128-64-4-True-False-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-32-128-64-2-False-True-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-32-128-64-2-False-True-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-128-128-64-2-True-False-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-128-128-64-2-True-False-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-32-128-64-2-False-False-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-32-128-64-2-False-False-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-64-64-32-4-True-True-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-64-64-32-4-True-True-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-128-128-64-4-False-True-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-128-128-64-4-False-True-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-64-64-32-4-True-False-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-64-64-32-4-True-False-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-64-64-32-4-False-True-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-64-64-32-4-False-True-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-128-128-64-4-False-False-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-128-128-64-4-False-False-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-128-128-64-2-False-True-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-128-128-64-2-False-True-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-128-128-64-2-False-False-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-128-128-64-2-False-False-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-64-128-128-2-True-True-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-64-128-128-2-True-True-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-64-128-128-2-True-False-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-64-128-128-2-True-False-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-64-128-128-2-False-True-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-64-128-128-2-False-True-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot[1-64-128-128-2-False-False-none-tf32-float32-float32-1_0] <br/>
FAILED language/test_core.py::test_dot[1-64-128-128-2-False-False-none-tf32-float32-float32-1_1] <br/>
FAILED language/test_core.py::test_dot_mulbroadcasted[float32]
</details>

**Comment by AshburnLee** [comment]
One question:

I found in a Jupyterhub session, when I switch to root user to install PTDB 0.5.2, `ls /opt/intel/oneapi/logs` still returns `v=0.5.1`.
Is there another way of verifying the PTDB version? When I re-install PTDB 0.5.2, it told me, PTDB 0.5.2 is already installed. 

If it is indeed PTDB 0.5.2, Rolling Agama 881/Agama 914.32 with PTDB 0.5.2 will be re-validate.

**Comment by pbchekin** [comment]
CI runners have been updated to use PTDB 0.5.2 in #1644. No new failed tests with Agama 914.32 and PTDB 0.5.2.

**Comment by pbchekin** [comment]
> we might need to verify the cases in skiplists only

I don't think it is really needed. After big updates like the recent one, just use your "enable unskip" mode to see if there are tests that no longer fail and update the skip lists respectively.
