### ISSUE TITLE
[Performance] The LLVM post optimization pass remove the GenISA prefetching operation by accident.

### ISSUE THREAD

**Issue by chengjunlu** [intel/intel-xpu-backend-for-triton#1633]
The LLVM post optimization passes remove the GenISA prefetching operation by accident.

This pass removes the prefetching operations:
```
Running pass: EarlyCSEPass on matmul_kernel_with_block_pointers (1145 instructions)
Running analysis: TargetLibraryAnalysis on matmul_kernel_with_block_pointers
; *** IR Dump After EarlyCSEPass on matmul_kernel_with_block_pointers ***
```

**Comment by chengjunlu** [comment]
Quick work around it by using the GenISA signature generated by the GenISA library. The prefetching operation is not removed then.

The signature from the GenISA library:
```
llvm.func @llvm.genx.GenISA.LSC2DBlockPrefetch(i64, i32, i32, i32, i32, i32, i32, i32, i32, i32, i1, i1, i32) attributes {passthrough = ["nounwind"]} loc(#loc1)
```

The signature generated in TritonGen lowering:
```
llvm.func spir_funccc @llvm.genx.GenISA.LSC2DBlockPrefetch.isVoid(i64, i32, i32, i32, i32, i32, i32, i32, i32, i32, i1, i1, i32) attributes {passthrough = ["nounwind", "willreturn", ["memory", "21"]]} loc(#loc)
```

By comparing the two signature, it seems the memory effect impacts the optimization.
After removing the memory effect attribute, the prefetching operation is preserved.

A quick work around is to remove the memory effect attribute.

**Comment by LiyangLingIntel** [comment]
Fix to this issue is added in https://github.com/intel/intel-xpu-backend-for-triton/pull/1634/commits/1192d9fe59c89be00d1c141e21faba76d879458d.
It works in my local test, please help take a look.

**Comment by whitneywhtsang** [comment]
Low priority because we plan to depreciate GenISA usage. And the problem doesn't exist for OpenCL 2D block prefetch.
