### ISSUE TITLE
How to make oneccl work in this custom pytorch/ipex version?

### ISSUE THREAD

**Issue by narendrachaudhary51** [intel/intel-xpu-backend-for-triton#1642]
This codebase requires us to install custom ipex and torch. However, I also need to install oneccl bindings for pytorch and run distributed code. (https://github.com/intel/torch-ccl)

I tried installing torch-ccl from source as mentioned in the repo. However, I got a bug in simple all reduce code. How do you use torch-ccl with your custom pytorch/ipex?

[error_log.txt](https://github.com/user-attachments/files/16263742/error_log.txt)

**Comment by vlad-penkin** [comment]
@narendrachaudhary51 we are switching to the upstream PyTorch. The ETA for completion is next two weeks. In the meantime you try to build upstream pytorch from the top of main trunk.
