### ISSUE TITLE
Assertion error in Triton/XeTLA benchmark

### ISSUE THREAD

**Issue by pbchekin** [intel/intel-xpu-backend-for-triton#1647]
```
python: /runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/third_party/intel/lib/TritonIntelGPUToLLVM/Utility.h:113: mlir::Value mlir::LLVM::intel::getSharedMemoryBase(mlir::Location, mlir::ConversionPatternRewriter&, mlir::Operation*): Assertion `op->hasAttr("allocation.offset")' failed.
...
/runner/_work/_temp/673946f5-6b4d-405f-9edf-bfa8c094c243.sh: line 2: 66330 Aborted                 (core dumped) python fused_softmax.py --reports $REPORTS
```

https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/9982726573/job/27589014198#step:16:25

Note that the yesterday's run was successful, so there is a recent commit that broke the benchmark.

**Comment by ESI-SYD** [comment]
I can run successfully in x1(Agama 914.32 PTDB 0.5.2) based on latest commit

**Comment by pbchekin** [comment]
CI also works with the latest commit: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/9995978002

**Comment by whitneywhtsang** [comment]
@ESI-SYD Start to fail again, please take a look. https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10054870453

**Comment by chengjunlu** [comment]
The issue has been work around in PR #1695 .

We need to investigate the root cause of this issue and fix it properly as high priority.

**Comment by pbchekin** [comment]
Another failure in the last nightly run: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10135461177/job/28036030570

**Comment by pbchekin** [comment]
Also in E2E performance workflows: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10129183788/job/28008945266#step:29:625

**Comment by ESI-SYD** [comment]
@pbchekin We have checked these workflows that have experienced failures, and they have one thing in common, which is the use of cached trtion instead of build from source
Can we replace the cache on the top of LLVM target?

**Comment by pbchekin** [comment]
> @pbchekin We have checked these workflows that have experienced failures, and they have one thing in common, which is the use of cached trtion instead of build from source Can we replace the cache on the top of LLVM target to expose more [details](https://github.com/intel/intel-xpu-backend-for-triton/blob/llvm-target/third_party/intel/lib/TritonIntelGPUToLLVM/Utility.h#L108) if crash happens?

As far as i understand, we use cache for Triton wheels and we use commit id as a cache key. So for each new commit in llvm-target you have a new Triton wheel.

**Comment by pbchekin** [comment]
@ESI-SYD potentially you can remove using Triton cached wheels for Triton/XeTLA benchmark and check if that helps. We also can disable cache for E2E workflow, if that helps.
