### ISSUE TITLE
Port and run Triton tutorials 

### ISSUE THREAD

**Issue by etiotto** [intel/intel-xpu-backend-for-triton#166]
We are currently running only the first 3 tutorial tests and we need to enable all the remaining tutorial tests:

![image](https://github.com/intel/intel-xpu-backend-for-triton/assets/56368199/774c3971-4f29-4b5d-92eb-fe0a5228d970)

As part of this investigation we might discover missing functionality or expose functional issues in the current implementation. Separate work items may be added to track compiler work required to complete this task.

**Comment by vlad-penkin** [comment]
This is an umbrella ticket to track issues related to the tutorials. Current open issues are:

- #338
- #339
- #340

**Comment by etiotto** [comment]
All tutorials have been ported. Workload sizes have been reduced because `tl.dot` is lowered using a loop containing scalar instructions, we should increase the problem sizes once `tl.dot` is lowered to use DPAS instructions.
