### ISSUE TITLE
Port and run operator tests

### ISSUE THREAD

**Issue by etiotto** [intel/intel-xpu-backend-for-triton#167]
We need to run the python operator tests:

![image](https://github.com/intel/intel-xpu-backend-for-triton/assets/56368199/3eb376fd-b5d6-4f2e-8d52-0d93fc153a79)

As part of this investigation we might discover missing functionality or expose functional issues in the current implementation. Separate work items may be added to track compiler work required to complete this task.

**Comment by etiotto** [comment]
@ESI-SYD I know you have opened issues to track remaining failing operator tests. Could you please also list them here so that it is easy to find them. Then go ahead an close the issue.

**Comment by ESI-SYD** [comment]
#251
#252 
#253
#254
#255
#256
#257
