### ISSUE TITLE
[CI] Automate SPIRV-LLVM-Translator version update Part2/2

### ISSUE THREAD

**Issue by AshburnLee** [intel/intel-xpu-backend-for-triton#1673]
Part 2 focused on raising PRs in an automate way that update the SPIRV-LLVM-Translator commit id obtained from https://github.com/intel/intel-xpu-backend-for-triton/issues/1672.

**Comment by AshburnLee** [comment]
Update:

The key components of this task are:
1. [done] Automate create PR.  
2. [wip] Find the target PR that is previously raised by this workflow
    i. [unacceptable] Pass artifact that contains the target PR id from run to run in the same workflow. I have experimented via `actions/download-artifact` & `actions/upload-artifact`. Unfortunately, artifacts cannot be passed from run to run in the same workflow. This is not how the Github Workflow works.
    ii. [wip] Use commands that find the target PR

**Comment by AshburnLee** [comment]
Update:

- Implementation is done, in review.
- PR create PRs by a bot automatically, In order to trigger the cid update in a regular base, at the end of the review, I will change the trigger to
  ```yml
      workflow_dispatch:
         schedule:
  ```

**Comment by AshburnLee** [comment]
Update:

- Fix CI not being triggered

**Comment by anmyachev** [comment]
> Update:
> 
> * Fix CI not being triggered
> 
> Automate PR: #1760, CI triggered

@AshburnLee should then the issue be closed?

**Comment by AshburnLee** [comment]
> > Update:
> > 
> > * Fix CI not being triggered
> > 
> > Automate PR: [#1760](https://github.com/intel/intel-xpu-backend-for-triton/pull/1760), CI triggered
> 
> [@AshburnLee](https://github.com/AshburnLee) should then the issue be closed?

Yes, issue will be closed once https://github.com/intel/intel-xpu-backend-for-triton/pull/1715 is merged.
