### ISSUE TITLE
[Profiler] Verify if Triton SYCL event based profiler still works with PyTorch upstream

### ISSUE THREAD

**Issue by LiyangLingIntel** [intel/intel-xpu-backend-for-triton#1685]
From PyTorch team, using SYCL event to get kernel execution time should be supported in the Stock PyTorch. It's covered in SYCL runtime.
We need to verify it and see can we keep using the legacy way to do performance profiling. So that it won't block Triton switch to Stock PyTorch.

**Comment by LiyangLingIntel** [comment]
If not, we have to think about other way mentioned in https://github.com/intel/intel-xpu-backend-for-triton/issues/1145 which would need much more efforts.

**Comment by LiyangLingIntel** [comment]
From [device_activity_tracing](https://github.com/intel-innersource/applications.analyzers.profilingtoolsinterfaces.sdk/blob/master/chapters/device_activity_tracing/DPCXX.md#how-to-use), to use SYCL `event_profiling` with stock PyTorch, we have to initialize SYCL queue with `sycl::property::queue::enable_profiling()`. 
For the best E2E performance consideration, PyTorch upstreaming do not enable this feature. [XPUStream.cpp#L101-L111](https://github.com/pytorch/pytorch/blob/e9db1b059733a02e1fb726d22a0489471044ad98/c10/xpu/XPUStream.cpp#L101-L111).
FYI. @vlad-penkin @whitneywhtsang 

From @chengjunlu , as replacements, we have two option:
1. Use the Kineto, the same as PyTorch XPU.
2. Enable Proton, https://github.com/intel/intel-xpu-backend-for-triton/issues/1145

Please help decide which way Intel Triton should choose. Otherwise, it will block Triton moving to Stock PyTorch.

**Comment by LiyangLingIntel** [comment]
Also, Triton Autotune relies on `torch.xpu.Event.elapsed_time` to get kernel execution time, which is not implemented in [pytorch/aten/src/ATen/xpu/XPUEvent.h](https://github.com/pytorch/pytorch/blob/e782918b8eeffc465acff40f0c55c8d80bc20ce2/aten/src/ATen/xpu/XPUEvent.h#L131-L145). 
Without this Triton Autotune will fail to work.

**Comment by YarShev** [comment]
I guess @alexbaden is working on something related to this in https://github.com/pytorch/pytorch/pull/126456.

**Comment by whitneywhtsang** [comment]
While waiting for `torch.xpu.Event.elapsed_time` to be supported, we can experience to use `Kineto`, assuming that it requires much less time than `Proton` to work. We can change the `do_bench` used by Triton Autotune to the modified version as well to unblock us.

**Comment by LiyangLingIntel** [comment]
Based on the offline discussion.
SYCL `event_profiling` is expected to be added back in PyTorch 2.5 after PyTorch team resolve the high overhead issue.
So Triton with PT2.4, we will apply the required changes in CL/local machine when building PyTorch from source.

On the other hand, it's still worthy to try enable Kineto in Triton. It would not take as much effort as Proton. We should check if Kineto can provide the same performance data as the legacy profiler.

**Comment by LiyangLingIntel** [comment]
> Based on the offline discussion. SYCL `event_profiling` is expected to be added back in PyTorch 2.5 after PyTorch team resolve the high overhead issue. So Triton with PT2.4, we will apply the required changes in CL/local machine when building PyTorch from source.
> 
> On the other hand, it's still worthy to try enable Kineto in Triton. It would not take as much effort as Proton. We should check if Kineto can provide the same performance data as the legacy profiler.

The patch for using `elapse_time` Upstream PyTorch is here [Support elapsed_time in XPUEvent](https://github.com/pytorch/pytorch/pull/126456). We should include it in the PR to apply before building the upstream PyTorch, so that we can use Triton Autotune and legacy profiler as we did.

PR https://github.com/intel/intel-xpu-backend-for-triton/issues/1145 tracks the task that enables Kineto in Triton.

**Comment by whitneywhtsang** [comment]
> PR https://github.com/intel/intel-xpu-backend-for-triton/issues/1145 tracks the task that enables Kineto in Triton.

It is tracked in https://github.com/intel/intel-xpu-backend-for-triton/issues/1066.

**Comment by LiyangLingIntel** [comment]
> > PR [#1145](https://github.com/intel/intel-xpu-backend-for-triton/issues/1145) tracks the task that enables Kineto in Triton.
> 
> It is tracked in [#1066](https://github.com/intel/intel-xpu-backend-for-triton/issues/1066).

Updated comment message, thanks.
