### ISSUE TITLE
Proposals to improve top-level readme install instructions

### ISSUE THREAD

**Issue by dvrogozh** [intel/intel-xpu-backend-for-triton#1692]
I am trying XPU flavored triton and would like to bring to your attention few issues I observe with the project's build process. Project diverged user setup experience from original Triton by introducing `scripts/compile-triton.sh`. Compare to original [instruction](https://github.com/triton-lang/triton/tree/d0bea6a18b214c49fe40b6c32c59ae3ee55c8241?tab=readme-ov-file#install-from-source). With that in mind:

1. User experience divergence is bad in general and I suggest to revert back with some modifications (see #1693). If you see some issues with Triton's instructions - better to address them and try contribute back to Triton. If you need some advanced setup features, then adding new script is fine, but don't substitute instruction with it - extend (see #1693).
1. `compile-triton.sh --venv` is not well described from my perspective. It internally creates undocumented virtual environment. Not clear how users are supposed to find it out.
1. I wonder if  `--venv` is useful at the first place. I am used to create external environment myself, sourcing it and then installing multiple projects in it. In this way original Triton instruction is good since it describes how to create virtual environment in clearly visible and editable form. Having this hidden in the script is an issue for me. I might be missing some usage with the `--venv` though... Let me know...
1. `compile-triton.sh` fails with external virtual environment. See #1691 for proposed fix.
1. `compile-triton.sh` may create undocumented folders/files outside working tree. Partially that's inherited from Triton - it creates `.triton` folder. Our script also adds `../packages` folder and creates a symlink to it from `$HOME` folder. To me that's a big no-go with such a script. It gives huge risk to pollute the system going forward. I suggest `packages` and its symlink should be removed completely and `.triton` folder documented.
1. I see that XPU triton version misses a note in build tips section. It would be nice to pull it in: "Set TRITON_HOME=/some/path to change the location of the .triton directory where Triton's cache is located and downloads are stored during the build. By default, this is the user's home directory. It can be changed anytime."
1. Overall, I propose to minimize differences in user experience vs. upstream Triton. There might be other places in readme requiring review and sync.

**Comment by pbchekin** [comment]
> compile-triton.sh --venv is not well described from my perspective. It internally creates undocumented virtual environment. Not clear how users are supposed to find it out.

Agree, In my opinion, this script should not create/manage virtual environments.

**Comment by pbchekin** [comment]
> Overall, I propose to minimize differences in user experience vs. upstream Triton. There might be other places in readme requiring review and sync.

Note that most of the users will not build Triton from sources, they will install it from pypi or use pre-built wheels. The script is intended to be used by developers.
