### ISSUE TITLE
Make the llvm-target branch use the Triton plugin infrastructure 

### ISSUE THREAD

**Issue by etiotto** [intel/intel-xpu-backend-for-triton#170]
The code in the `llvm-target` branch is a fork of the OpenAI Triton code with modifications in several files. The structure of the project mirrors the structure of the AMD port. This work item objective is to make the project use the Triton plugin infrastructure. The work is similar to what is required for the AMD port, which is also a fork, so we should determine whether we can use the same mechanism.

**Comment by chengjunlu** [comment]
Will keep the both ways as well for Intel.

When Intel XPU backend is built as a plug-in, We'd have to re-configure the CMake build configuration in the root CMakeLists.txt of Intel XPU backend repo. That is because some targets has the same name but different source codes. Like: target TritonGPUToLLVM. Unlike to AMD, the Intel related codes are only in Intel XPU backend while the public Triton has the AMD codes.

**Comment by etiotto** [comment]
> Will keep the both ways as well for Intel.
> 
Yes agree. 

> When Intel XPU backend is built as a plug-in, We'd have to re-configure the CMake build configuration in the root CMakeLists.txt of Intel XPU backend repo. That is because some targets has the same name but different source codes. Like: target TritonGPUToLLVM. Unlike to AMD, the Intel related codes are only in Intel XPU backend while the public Triton has the AMD codes.
> 

OK. We need to be able to change any file that OpenAI has in our fork (until OpeNAI let us upstream changes in common files). If you post a PR we can iterate on the actual code changes.

> The Intel XPU backend LLVM will support the latest Triton plugin infrastructure. (Triton version > 2.2). For the Triton version <= 2.2, we still use the SPIRV target in the main branch now.
> 
> Is that Ok?

Yes. I think that is fine. The LLVM target can be used for new version of Triton only.

**Comment by aregm** [comment]
@chengjunlu - what's the status here?

**Comment by chengjunlu** [comment]
> @chengjunlu - what's the status here?

The final code change will be ready in this week.

It supports to build the Intel XPU backend llvm-target branch as a 3p plug-in as well as to build the Intel XPU backend along.

**Comment by vlad-penkin** [comment]
@etiotto is this ticket still valid?
