### ISSUE TITLE
GEMM Block-pointer Path

### ISSUE THREAD

**Issue by Dewei-Wang-sh** [intel/intel-xpu-backend-for-triton#171]
get triton gemm perf 80% of oneDNN/XeTLA utilizing genISA/vc-intrinsics.
the lowering pipeline would be "triton -> tritongpu -> optimized/simplified tritongpu  => llvm/spirv".

this serves as an umbrella issue including
 - #406
 - #407 
 - #408
 - #612
 - #613

**Comment by Dewei-Wang-sh** [comment]
the ultimate goal is to make gemm4Kx4Kx4K perf up to 80% of XeTLA.
will begin with simple cases though.
since the dpas size on PVC is 8x16 = 8x16 * 16x16
the first test cases is listed below:
## matmul.8x16x1024.mlir
// total 8x16x1024
//              it has 1 workgroup. each workgroup caculates a [8x16 = 8x1024 * 1024x16] block
// each work-group has 1  subgroup. each  subgroup caculates a [8x16 = 8x1024 * 1024x16] block
## matmul.16x32x1024.mlir
// total 16x32x1024
//              it has 4 workgroup. each workgroup caculates a [ 8x16 = 8x1024 * 1024x16] block
// each work-group has 1  subgroup. each  subgroup caculates a [ 8x16 = 8x1024 * 1024x16] block
## matmul.16x32x1024.numWarps4.mlir
// total 16x32x1024
//              it has 1 workgroup. each workgroup caculates a [16x32 = 16x1024 * 1024x32] block
// each work-group has 4  subgroup. each  subgroup caculates a [ 8x16 = 8x1024 * 1024x16] block

**Comment by etiotto** [comment]
IS this work item intended to show MLIR code snippets as examples or is it going to be used to modify the Triton compiler (backend) ?

**Comment by Dewei-Wang-sh** [comment]
> Is this work item intended to show MLIR code snippets as examples or is it going to be used to modify the Triton compiler (backend) ?
> 
> Also, I understand that in order to use SIMD codegen we need to have additional information in the Triton source, information conveyed by Triton blocked pointers. Therefore in the absence of blocked pointers the codegen for `tt.dot` would follow the SIMT model. Please confirm.

yes Ettor, your are right, the simd path aims to support cases with block pointer, the traditional tensor of pointers will stay as is.
I'm going to add a few more passes to make triton-> tritongpu  to a form that is suitable for mapping to vc-intrinsics.
and the above test serves as a start point.

**Comment by Dewei-Wang-sh** [comment]
12/25/2023:  add tritongpu/xegpu/spirv test cases for simple gemm
https://github.com/intel/intel-xpu-backend-for-triton/compare/main...gemm_simd

**Comment by Dewei-Wang-sh** [comment]
1/8/2024: add ttg2spirv(vc-Intrinsics)lowering; update test; fix ttg/spirv running error
now it can run from ttg source and get correct result.

**Comment by Dewei-Wang-sh** [comment]
1/15/2024:  add necessary triton patches
    add triton ops; add end2end test
    add pass tritongpu-distribute-to-warps

**Comment by Dewei-Wang-sh** [comment]
1/23/2024: **bug fix, gemm_256x256x1024 can run correctly**

**Comment by Dewei-Wang-sh** [comment]
02/07/2024: refactor the pass tritongpu-match-target-size, fix bugs, now gemm_256x256x1024 can run correctly.

**Comment by etiotto** [comment]
@Dewei-Wang-sh would you mind sharing the code for this feature in a draft PR. IS OK to work on a draft PR even if the code is not in its final form. Having a draft PR helps to geta preview of the direction the work is going and is a good way to gather early feedback.

**Comment by Dewei-Wang-sh** [comment]
> @Dewei-Wang-sh would you mind sharing the code for this feature in a draft PR. IS OK to work on a draft PR even if the code is not in its final form. Having a draft PR helps to geta preview of the direction the work is going and is a good way to gather early feedback.

sure, let port the code to the llvm-target branch

**Comment by Dewei-Wang-sh** [comment]
02/26/2024: go from a handwritten optimized tritongpu IR and lowering to spirv, now it can reach ~290TFlops for a 4k*4k*4k*f16 gemm.

**Comment by Dewei-Wang-sh** [comment]
03/04/2024:  **add a pass convert-triton-to-tritongpu-warp**
Convert Triton to TritonGPU with a blocked layout(warp distribute annotation)

**Comment by Dewei-Wang-sh** [comment]
all the sub-issues closed with pr merged
