### ISSUE TITLE
[Research] Use gcc or clang instead of dpc++ to compile Triton kernel launcher

### ISSUE THREAD

**Issue by vlad-penkin** [intel/intel-xpu-backend-for-triton#1718]
Currently Triton needs dpc++ to compile Triton kernel launcher due to SYCL code presence:
- https://github.com/intel/intel-xpu-backend-for-triton/blob/ccc0b53bd86114b0fe6d9e8d56f24ffed0a987c1/third_party/intel/backend/driver.py#L274

We need to investigate whether it's possible to make changes to the kernel launcher code to support gcc or clang compilation.

Kernel launcher compilation can't be moved to to the Triton build stage due to the Triton upstream compilation requirement - it should be buildable with gcc or clang.

**Comment by pbchekin** [comment]
Note that if dpc++ is not required, then we don't need extra compiler, since triton has llvm (not an executable binary but linked as a library as far as i understand).

**Comment by etiotto** [comment]
@vlad-penkin please let me know if the current facilities I explained above are sufficient for the PyTorch team.

**Comment by vlad-penkin** [comment]
@etiotto thanks for the update! Have you been able to compile Triton Kernel launcher with gcc and clang by just adding path to SYCL runtime binaries and header files?
