### ISSUE TITLE
[PyTorch Upstream] XPU mode - NotImplementedError: The operator 'aten::__lshift__.Scalar'

### ISSUE THREAD

**Issue by YarShev** [intel/intel-xpu-backend-for-triton#1780]
`language/test_core.py::test_abs_fp8[in_dtype2]` is failing because of https://github.com/intel/torch-xpu-ops/issues/570. Let's mark it as xfail so we can enable it straight away once `aten::__lshift__.Scalar` is implemented.

**Comment by YarShev** [comment]
@vlad-penkin, I was trying to set `PYTORCH_ENABLE_XPU_FALLBACK=1` like this `os.environ["PYTORCH_ENABLE_XPU_FALLBACK"] = "1"` inside the test but it is still failing with the error `NotImplementedError: The operator 'aten::__lshift__.Scalar' ...`. Looks like the env var is not detected globally. Is this expected behavior or does it look like an issue in pytorch/torch_xpu_ops?

**Comment by YarShev** [comment]
Even without using pytest a simple repro is failing. I wonder if this is really an issue in pytorch/torch_xpu_ops? cc @whitneywhtsang

<details>

```python
import os
import triton
import triton.language as tl
import torch
import re

def torch_dtype_name(dtype) -> str:
    if isinstance(dtype, triton.language.dtype):
        return dtype.name
    elif isinstance(dtype, torch.dtype):
        # 'torch.int64' -> 'int64'
        m = re.match(r'^torch\.(\w+)$', str(dtype))
        return m.group(1)
    else:
        raise TypeError(f'not a triton or torch dtype: {type(dtype)}')

def convert_float_to_float32(fp: torch.tensor, dtype=None):
    if not dtype:
        dtype = getattr(tl, torch_dtype_name(fp.dtype))

    fp = fp.view(getattr(torch, f"int{dtype.primitive_bitwidth}"))
    exp_width = dtype.primitive_bitwidth - dtype.fp_mantissa_width - 1
    exp_bias = dtype.exponent_bias
    sign = ((fp >> (dtype.primitive_bitwidth - 1)) & 0x01).int()
    exp = ((fp >> dtype.fp_mantissa_width) & ((1 << exp_width) - 1)).int()
    frac = (fp & ((1 << dtype.fp_mantissa_width) - 1)).int()

    output = torch.where(
        exp == 0,
        # subnormal
        ((-1.0)**sign) * (2.0**(1 - exp_bias)) * (frac / (2.0**dtype.fp_mantissa_width)),
        # normal
        ((-1.0)**sign) * (2.0**(exp - exp_bias)) * (1.0 + frac / (2.0**dtype.fp_mantissa_width))).float()

    extended_exp = (
        (1 << (tl.float32.primitive_bitwidth - tl.float32.fp_mantissa_width - 1)) - 1) << tl.float32.fp_mantissa_width
    # special cases, exp is 0b11..1
    if dtype in [tl.float8e4nv, tl.float8e4b15]:
        # float8e4m3nv does not have infinities
        output[fp == 0b01111111] = torch.nan
        output[fp == 0b11111111] = torch.nan
    else:
        output = torch.where(exp == (1 << exp_width) - 1,
                             ((sign << (tl.float32.primitive_bitwidth - 1)) | extended_exp
                              | (frac << (tl.float32.fp_mantissa_width - dtype.fp_mantissa_width)))  #
                             .view(torch.float32), output)
    return output

def test_abs_fp8():
    in_dtype = tl.float8e5
    os.environ["PYTORCH_ENABLE_XPU_FALLBACK"] = "True"

    @triton.jit
    def abs_kernel(X, Z, SIZE: tl.constexpr):
        off = tl.arange(0, SIZE)
        x = tl.load(X + off)
        z = tl.abs(x)
        tl.store(Z + off, z)

    f8_tensor = torch.tensor(range(-128, 128), dtype=torch.int8, device="xpu")
    # f32_to_f8 doesn't handle nan, so we make sure f8_tensor doesn't contain any nan
    all_exp_ones = (f8_tensor & 0b01111100) == 128 - 2**in_dtype.fp_mantissa_width
    f8_tensor[all_exp_ones] = 0
    f8 = triton.reinterpret(f8_tensor, in_dtype)
    n_elements = f8_tensor.numel()
    out_f8 = torch.empty_like(f8_tensor)
    abs_kernel[(1, )](f8, triton.reinterpret(out_f8, in_dtype), n_elements)

    f32_tensor = convert_float_to_float32(f8_tensor, in_dtype)
    expect = f32_tensor.abs()
    actual_f8 = convert_float_to_float32(out_f8, in_dtype)
    torch.testing.assert_close(actual_f8, expect, equal_nan=True)

test_abs_fp8()
```

</details>

**Comment by anmyachev** [comment]
> @vlad-penkin, I was trying to set `PYTORCH_ENABLE_XPU_FALLBACK=1` like this `os.environ["PYTORCH_ENABLE_XPU_FALLBACK"] = "1"` inside the test but it is still failing with the error `NotImplementedError: The operator 'aten::__lshift__.Scalar' ...`. Looks like the env var is not detected globally. Is this expected behavior or does it look like an issue in pytorch/torch_xpu_ops?

@YarShev did you apply the patch https://github.com/intel/torch-xpu-ops/pull/684?

**Comment by YarShev** [comment]
@anmyachev, thanks! After applying this patch the repro works. However, it is interesting why the repro was passing without the patch if I set the env var globally (e.g., when running the repro). @vlad-penkin, since the patch is not going to be merged, maybe we should keep the test as xfailed?

**Comment by vlad-penkin** [comment]
@YarShev patch will be eventually merged. We apply it for building pytorch nightly wheels. Please discard the pull request.

**Comment by ZzEeKkAa** [comment]
BTW, there is a proper implementation, that can be used https://github.com/intel/torch-xpu-ops/pull/688 . I did not test it but will update status ASAP.

**Comment by vlad-penkin** [comment]
We expect that PyTorch Team will bump torch-xpu-ops commit id within next two weeks.

**Comment by ZzEeKkAa** [comment]
Should be resolved with https://github.com/pytorch/pytorch/pull/133850 merge

**Comment by anmyachev** [comment]
Reminder to revert:
https://github.com/intel/intel-xpu-backend-for-triton/blob/fb2194388bd50ed02ed29d51a558b2a76deea48f/.github/workflows/build-test-reusable.yml#L169-L172
