### ISSUE TITLE
[Upstream] LinearLayout conversion interface

### ISSUE THREAD

**Issue by hwnam831** [intel/intel-xpu-backend-for-triton#1785]
Upstream Triton requires integrating all MMA layouts inside the original TritonGPU IR to implement LinearLayout conversion.
We need to design an interface that enables implementing LinearLayout conversion under third_party and upstream the

**Comment by hwnam831** [comment]
Currently marked blocked because this has dependency to the issue #1874 .
Once #1875 is merged, I'll begin upstreaming the changes.

**Comment by etiotto** [comment]
Upstream PR: https://github.com/triton-lang/triton/pull/4525
