### ISSUE TITLE
[CI] A robot github account and the personal access token associated﻿ with it is needed.

### ISSUE THREAD

**Issue by AshburnLee** [intel/intel-xpu-backend-for-triton#1786]
We are having a robot raising PR in a regular base: https://github.com/intel/intel-xpu-backend-for-triton/actions/workflows/auto-update-translator-cid.yml, it uses PAT(personal access token) from my account, which I think is not a good practice.

So do we have a robot Github account in TritonXPU? If we do, a PAT associated﻿ with this account is needed.

**Comment by pbchekin** [comment]
Done, replaced with the secret for glados-intel, service account.
