### ISSUE TITLE
[Upstream] Upstream the bug fix in the DecomposeConvertLayout.cpp

### ISSUE THREAD

**Issue by chengjunlu** [intel/intel-xpu-backend-for-triton#1796]
Upstream the fixes in the https://github.com/intel/intel-xpu-backend-for-triton/pull/1761

**Comment by anmyachev** [comment]
@chengjunlu It seems that `LocalAllocOp` and `LocalLoadOp` are already incorporated in the general Triton conversions. However, the `addAttrs` functions are still being utilized, which is the only noticeable difference. Do these changes still need to be upstreamed?

https://github.com/intel/intel-xpu-backend-for-triton/blob/fad249653ef2846505fcf9d69165f9c8f217c001/lib/Conversion/TritonGPUToLLVM/DecomposeUnsupportedConversions.cpp#L107-L113

**Comment by chengjunlu** [comment]
> @chengjunlu It seems that `LocalAllocOp` and `LocalLoadOp` are already incorporated in the general Triton conversions. However, the `addAttrs` functions are still being utilized, which is the only noticeable difference. Do these changes still need to be upstreamed?
> 
> https://github.com/intel/intel-xpu-backend-for-triton/blob/fad249653ef2846505fcf9d69165f9c8f217c001/lib/Conversion/TritonGPUToLLVM/DecomposeUnsupportedConversions.cpp#L107-L113

Thanks for the information. I think there is no useful attributes for the convert layout operation so far.

I think we can close this issue as the upstream has been changed.
