### ISSUE TITLE
compile-pytorch-ipex.sh doesn't patch upstream pytorch and use pinned revision

### ISSUE THREAD

**Issue by gshimansky** [intel/intel-xpu-backend-for-triton#1823]
Script compile-pytorch-ipex.sh when building upstream version of pytorch doesn't use the same patches as CI workflow https://github.com/intel/intel-xpu-backend-for-triton/blob/llvm-target/.github/actions/setup-pytorch/action.yml#L95-L97 and it doesn't checkout pinned revision from https://github.com/intel/intel-xpu-backend-for-triton/blob/llvm-target/.github/pins/pytorch-upstream.txt.

**Comment by pbchekin** [comment]
Partly fixed in #1824. Still need to add support for pinned version since

```
./compile-pytorch-ipex.sh --pytorch --upstream-pytorch --source
```

builds only PyTorch main.
