### ISSUE TITLE
PyTorch 2.4 on A770: Required aspect fp64 is not supported on the device

### ISSUE THREAD

**Issue by pbchekin** [intel/intel-xpu-backend-for-triton#1840]
600 tests fail with PyTorch 2.4 on A770, for example:

```
FAILED language/test_standard.py::test_maximum_minium[maximum-bfloat16] - RuntimeError: Required aspect fp64 is not supported on the device
```

https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10330161539/job/28598819656

**Comment by pbchekin** [comment]
> This issue no longer exists on PyTorch main.

What do we do with PyTorch 2.4?

**Comment by anmyachev** [comment]
I can confirm that changes from https://github.com/intel/torch-xpu-ops/pull/511 fixes the problem if they applied on top of https://github.com/intel/torch-xpu-ops/commit/97d692eb8c4b3afab17700a2fd918adcea0cba45 commit (that used by pytorch v2.4.1-rc1). To do this, one will also need to update the commit used in PyTorch (in `caffe2/CMakeLists.txt`).

@fengyuan14 is it possible to backport this PR for pytorch 2.4?

**Comment by anmyachev** [comment]
> I can confirm that changes from [intel/torch-xpu-ops#511](https://github.com/intel/torch-xpu-ops/pull/511) fixes the problem if they applied on top of [intel/torch-xpu-ops@97d692e](https://github.com/intel/torch-xpu-ops/commit/97d692eb8c4b3afab17700a2fd918adcea0cba45) commit (that used by pytorch v2.4.1-rc1). To do this, one will also need to update the commit used in PyTorch (in `caffe2/CMakeLists.txt`).
> 
> @fengyuan14 is it possible to backport this PR for pytorch 2.4?

@Stonepia maybe you know if it is possible to port such changes?

**Comment by Stonepia** [comment]
AFAIK, pytorch 2.4 is code frozen. You can see the roadmap at:
https://dev-discuss.pytorch.org/t/pytorch-release-2-4-0-call-for-features/2051

So I don't think it is possible to backport to 2.4 (officially).

As for XPU backend support, I think we are committed to support on PT2.5, so how about you skip PT2.4 and use the latest PyTorch (PT2.5)? The PyTorch 2.5 roadmap is at https://dev-discuss.pytorch.org/t/pytorch-release-2-5-0-call-for-features/2339 , it will contain the fp64 emulation.

**Comment by 54108** [comment]
for the nightly build torch-2.6.0.dev20241212+xpu still have the same problem of "RuntimeError: Required aspect fp64 is not supported on the device".

I set up my environment follow this instruction[https://www.intel.com/content/www/us/en/developer/articles/tool/pytorch-prerequisites-for-intel-gpu/2-5.html](url)

**Comment by Stonepia** [comment]
Hi @54108 ,  thanks for the question!
That issue should have been fixed in https://github.com/intel/torch-xpu-ops/issues/628. Could you provide a simple reproducer step and submit the issue in https://github.com/intel/torch-xpu-ops/issues ? We will take a look.

**Comment by Y-T-G** [comment]
Quick hack for this issue is to add this before your code:

```python
import torch
torch.Tensor.double = torch.Tensor.float
torch.float64 = torch.float32
```
