### ISSUE TITLE
[Upstream] Try to upstream the supporting of the nested layout slice->dot->mma without LinearLayout

### ISSUE THREAD

**Issue by chengjunlu** [intel/intel-xpu-backend-for-triton#1843]
The changes to the common TritonGPU dialect in the PR https://github.com/intel/intel-xpu-backend-for-triton/pull/1782

**Comment by chengjunlu** [comment]
Since we have supported the conversion to LinearLayout of the DPAS layout, we are not going to upstream the changes in legacy layout interface which is going to be rejected most likely.

The proper way is to support the conversion from dot layout to LinearLayout in upstream which is not supported yet.

@etiotto , @whitneywhtsang , Should we upstream the code to Triton or should we wait upstream to finish that?

**Comment by whitneywhtsang** [comment]
Since we already have the change, we can attend to upstream it (assuming the cost is low) with a comment in the description that the change is not needed when dot layout to linear layout conversion is supported, and ask when do they plan to support it. WDYT @etiotto @chengjunlu

**Comment by chengjunlu** [comment]
> Since we already have the change, we can attend to upstream it (assuming the cost is low) with a comment in the description that the change is not needed when dot layout to linear layout conversion is supported, and ask when do they plan to support it. WDYT [@etiotto](https://github.com/etiotto) [@chengjunlu](https://github.com/chengjunlu)

Make sense. I will create the PR to upstream the changes and request for comments.

**Comment by chengjunlu** [comment]
Created an RFC to the public Triton:
https://github.com/triton-lang/triton/pull/4598

**Comment by chengjunlu** [comment]
The PR has been rejected.

We need to keep the changes in the down stream and remove those changes in the public common code.

**Comment by chengjunlu** [comment]
The DotOp layout to LL has been supported in upstream Triton. And the code has been merged to Intel XPU downstream repo. We can close this JIRA because there is no need to support the nested layout in legacy path any more.

**Comment by whitneywhtsang** [comment]
Can we remove the changes we made in PR https://github.com/intel/intel-xpu-backend-for-triton/pull/1782 then?

**Comment by chengjunlu** [comment]
> Can we remove the changes we made in PR #1782 then?

We can track the clean up task in this issue https://github.com/intel/intel-xpu-backend-for-triton/issues/2030.

We can clean up our local logic after replacing the `intel::emitIndices` when we fully reuses this file `include/triton/Conversion/TritonGPUToLLVM/Utility.h`
