### ISSUE TITLE
[CI] Change regular E2E CI defaults from IPEX/PT test proxies to upstream PyTorch

### ISSUE THREAD

**Issue by vlad-penkin** [intel/intel-xpu-backend-for-triton#1851]

**Comment by pbchekin** [comment]
Done, we run E2E accuracy and performance tests daily for PyTorch 2.4:
* https://github.com/intel/intel-xpu-backend-for-triton/actions/workflows/e2e-accuracy.yml
* https://github.com/intel/intel-xpu-backend-for-triton/actions/workflows/e2e-performance.yml
