### ISSUE TITLE
[UT and Tutorials] Deprecate `import intel_extension_for_pytorch` in python/test/** and python/tutorials

### ISSUE THREAD

**Issue by vlad-penkin** [intel/intel-xpu-backend-for-triton#1854]

**Comment by vlad-penkin** [comment]
As per offline conversation with @pbchekin changes in UT's and Tutorials needs to be done at the same time.

Closing

- #1853

as duplicate.

**Comment by whitneywhtsang** [comment]
Still need to deprecate upstream for `python/test/backend/third_party_backends/test_xpu_backend.py`.

**Comment by whitneywhtsang** [comment]
Done in https://github.com/triton-lang/triton/pull/4616, merged in https://github.com/intel/intel-xpu-backend-for-triton/pull/2081.
