### ISSUE TITLE
Generic LinearLayout conversion interface.

### ISSUE THREAD

**Issue by hwnam831** [intel/intel-xpu-backend-for-triton#1874]
Currently, our DPAS->LL conversion code is outside upstream's `toLinearLayout` function, so that we have to manually detect and call our `DPAStoLinearLayout` whenever DPAS->LL conversion is needed.
We need to create a generic interface that allows implementing LinearLayout conversion outside the upstream code.

**Comment by hwnam831** [comment]
We will try upstream first (#1785) and proceed once the upstream accepts the change.

**Comment by whitneywhtsang** [comment]
Changes merged in https://github.com/intel/intel-xpu-backend-for-triton/pull/1942.
