### ISSUE TITLE
Unhandled parameter attribute 'tt.constancy' and 'tt.contiguity'

### ISSUE THREAD

**Issue by anmyachev** [intel/intel-xpu-backend-for-triton#1899]
Such messages can be seen in the CI: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10422253663/job/28866333683

Should we fix it?

**Comment by whitneywhtsang** [comment]
The simplest solution is to remove it like https://github.com/intel/intel-xpu-backend-for-triton/blob/llvm-target/third_party/intel/lib/TritonIntelGPUToLLVM/TritonGPUToLLVM.cpp#L131.

**Comment by whitneywhtsang** [comment]
It is not observed upstream, as below is only enabled under env var `MLIR_ENABLE_DIAGNOSTICS` upstream.
```
             context->getDiagEngine().registerHandler([](Diagnostic &diag) {
               llvm::outs() << diag << "\n";
               return success();
             });
```
