### ISSUE TITLE
[Local builds] Changes to `--fake-ipex` option (no-op IPEX) in `scripts/compile-pytorch-ipex.sh`

### ISSUE THREAD

**Issue by vlad-penkin** [intel/intel-xpu-backend-for-triton#1912]

**Comment by anmyachev** [comment]
We already have `--fake-ipex` flag for this but it works only with one more flag: `--ipex`. I can do by analogy as in https://github.com/intel/intel-xpu-backend-for-triton/pull/1906 so that using `--fake-ipex` would be enough.

**Comment by vlad-penkin** [comment]
@anmyachev thanks for the update. 

We need to implement two changes:

1. Version should be `2.4.0+dummy_no-op`
2. This option should be part of the `--upstream-pytorch` option
