### ISSUE TITLE
Add an analysis function for inst schedule pass

### ISSUE THREAD

**Issue by LiyangLingIntel** [intel/intel-xpu-backend-for-triton#1920]
Current Instruction Schecule pass is controlled by environment variable `TRITON_INTEL_ENABLE_INSTR_SCHED`.
To remove it we still need a extra analysis function for like register pressure based on given patterns. So that we can make decision automatically whether enable instruction scheduling in the lowering pipeline or not.

**Comment by whitneywhtsang** [comment]
Given that IGC is able to get most of the performance gain from instruction scheduling, IMO we can close this issue.

**Comment by LiyangLingIntel** [comment]
Yes, I think we can close this issue after we verify the performance gain with  the new published IGC version.

**Comment by whitneywhtsang** [comment]
Awaiting agama 996.
