### ISSUE TITLE
E2E AlbertForMaskedLM test failed on A770 and PyTorch main

### ISSUE THREAD

**Issue by anmyachev** [intel/intel-xpu-backend-for-triton#1921]
CI run with this error: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10386186049/job/28756916039

Error: `RuntimeError: Kernel is incompatible with all devices in devs`

**Comment by alexbaden** [comment]
Have you tried running with `ONEAPI_DEVICE_SELECTOR`? (https://intel.github.io/llvm-docs/EnvironmentVariables.html) 

There are multiple devices on A770 machine:
```
-
~ » sycl-ls                                                                                                                             
[opencl:acc:0] Intel(R) FPGA Emulation Platform for OpenCL(TM), Intel(R) FPGA Emulation Device OpenCL 1.2  [2024.17.8.0.02_180502.xmain-hotfix]
[opencl:cpu:1] Intel(R) OpenCL, Intel(R) Core(TM) i7-14700K OpenCL 3.0 (Build 0) [2024.17.8.0.02_180502.xmain-hotfix]
[opencl:gpu:2] Intel(R) OpenCL Graphics, Intel(R) Arc(TM) A770 Graphics OpenCL 3.0 NEO  [24.26.30049.10]
[opencl:gpu:3] Intel(R) OpenCL Graphics, Intel(R) Arc(TM) A770 Graphics OpenCL 3.0 NEO  [24.26.30049.10]
[opencl:gpu:4] Intel(R) OpenCL Graphics, Intel(R) UHD Graphics 770 OpenCL 3.0 NEO  [24.26.30049.10]
[ext_oneapi_level_zero:gpu:0] Intel(R) Level-Zero, Intel(R) Arc(TM) A770 Graphics 1.3 [1.3.30049]
[ext_oneapi_level_zero:gpu:1] Intel(R) Level-Zero, Intel(R) Arc(TM) A770 Graphics 1.3 [1.3.30049]
[ext_oneapi_level_zero:gpu:2] Intel(R) Level-Zero, Intel(R) UHD Graphics 770 1.3 [1.3.30049]
```
I wonder if we're pulling the wrong device (the error message seems to hint at requiring compatibility for a feature across all devices)

**Comment by anmyachev** [comment]
@alexbaden No, but I tried to call `inductor_xpu_test.sh` with `xpu 1` and `xpu 2`. Doesn't this do the same thing (use a device with a different index)? `ZE_AFFINITY_MASK` is used inside this script.
