### ISSUE TITLE
Use live range analysis in "ScheduleLoad"

### ISSUE THREAD

**Issue by etiotto** [intel/intel-xpu-backend-for-triton#1930]
Currently the advanced codegen path uses the transformation in "ScheduleLoad.cpp" to move loads for the operands of a `tt.dot` operation closer to the operation. This reduces the live range of the loaded SSA value(s) and facilitate instruction scheduling in IGC.

Once we have a live range analysis we can use it to determine the region(s) in the loop that have the largest number of overlapping live ranges and use that information to heuristically move the loads described above closer to their uses.

**Comment by etiotto** [comment]
@whitneywhtsang now that IGC has improved scheduling I wonder whether this work item is still needed. If the performance of GEMM/FA  (advanced path)  is already on par with the ScheduleLoad pass removed from  Triton (and the new IGC) then it is not. What is the perf. like ?

**Comment by whitneywhtsang** [comment]
> @whitneywhtsang now that IGC has improved scheduling I wonder whether this work item is still needed. If the performance of GEMM/FA (advanced path) is already on par with the ScheduleLoad pass removed from Triton (and the new IGC) then it is not. What is the perf. like ?

FA performance is not yet on par with IGC optimization, but it can get most of the performance.
GEMM performance has no impact.

Z | H | N_CTX | D_HEAD | avg_tflops
-- | -- | -- | -- | -- 
4 | 48 | 1024 | 64 | 99.4%
32 | 32 | 512 | 64 | 99.8%
16 | 32 | 1024 | 64 | 95.8%
8 | 32 | 2048 | 64 | 95.8%
4 | 32 | 4096 | 64 | 97.2%
2 | 32 | 8192 | 64 | 98.1%
1 | 32 | 16384 | 64 | 99.2%
