### ISSUE TITLE
[IPEX deprecation] Process to update upstream Pytorch pin and automation around it

### ISSUE THREAD

**Issue by vlad-penkin** [intel/intel-xpu-backend-for-triton#1933]
Run validation worklfow for latest commit in main branch, which will include:

 - UT + Tutorials validation matrix -  Supported Python versions `x` Driver Streams (Rolling, LTS)  
 - Inductor for all supported Python versions on Rolling
 - E2E Accuracy LTS and Rolling for selected Python version
 - Benchmarks  for selected Python version

Workflow run frequency 

- Monday and Wednesday or ad-hoc

Tracking 

- manually via GH issues We'll start from manual check and consider automation later

Baseline comparison with current UT/Tutorials and E2E results 

- We'll start from manual check and consider automation later

**Comment by pbchekin** [comment]
> Inductor for all supported Python versions on Rolling

Only one Python is fine. Also inductor tests can be a gateway for other tests: execute it first, then if successful execute rest of the tests.

**Comment by kwasd** [comment]
Done 3 of 4, but still need #1905 to schedule benchmarks for selected Python version.

**Comment by kwasd** [comment]
> > Inductor for all supported Python versions on Rolling
> 
> Only one Python is fine. Also inductor tests can be a gateway for other tests: execute it first, then if successful execute rest of the tests.

See https://github.com/intel/intel-xpu-backend-for-triton/pull/2161

**Comment by kwasd** [comment]
Example https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10769983032

**Comment by kwasd** [comment]
Will continue in #2172
