### ISSUE TITLE
[Softmax] benchmark is broken after cleanups

### ISSUE THREAD

**Issue by Egor-Krivov** [intel/intel-xpu-backend-for-triton#1934]
After this PR softmax benchmarks are failing.
https://github.com/intel/intel-xpu-backend-for-triton/pull/1884

Right before the merge softmax passes: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10457594475/job/28957570456
Right after the merge softmax fails: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10457592847

**Comment by alexbaden** [comment]
I need to update `benchmark_driver.py`. Will have a PR shortly.
