### ISSUE TITLE
[OCL interface] The OCL interface miss some 2D load variants which is used in Triton

### ISSUE THREAD

**Issue by chengjunlu** [intel/intel-xpu-backend-for-triton#1941]
New 2D load variants are used in FP8 load. https://github.com/intel/intel-xpu-backend-for-triton/commit/5f088429c8aeb0082c262d812945c2b4e7b86233

- 8b, 8 row, 16 column, 4 blocks, 2D load. GenISA signature `llvm.genx.GenISA.LSC2DBlockRead.v32i8`

New transpose 2D load variants are used in flash attention.

- 32b, 32 row, 8 column, 1 block, transposed 2D load. GenISA signature  `llvm.genx.GenISA.LSC2DBlockRead.v16i32`

We are using the GENISA if it is not exist in OCL interface for now. 
Need to summary the new requirements and file JIRA to IGC to track.

**Comment by vlad-penkin** [comment]
@chengjunlu, @whitneywhtsang could you please file the ticket and share it's number with me offline.

**Comment by whitneywhtsang** [comment]
> @chengjunlu, @whitneywhtsang could you please file the ticket and share it's number with me offline.

Yes, we are still preparing the content for the ticket.

**Comment by chengjunlu** [comment]
IGC team has confirmed that they are working on the task to support general 2D load interface thru the SPIRV Intel Block IO extension.

**Comment by whitneywhtsang** [comment]
This task is completed.
