### ISSUE TITLE
Unable to get elapsed_time after applying patch

### ISSUE THREAD

**Issue by jgtong** [intel/intel-xpu-backend-for-triton#1974]
Greetings:

I have an issue in trying to obtain the elapsed time when running triton kernels on the Intel 1550 Max GPU when using the `upstream-pytorch` source code. The warning message I see is the following:

`WARNING:root:Wall time is used instead of elapsed_time (not supported). The timing measurements could be innacurate.`

I successfully applied the patch from `scripts/patch-pytorch.sh` into the cloned `pytorch` directory, along with doing a clean build in the `intel-xpu-backend-for-triton` directory. 

Here are the steps that I did to reproduce the warning message:

1. `source /path/to/oneapi/setvars.sh --force` (This already contains the `pti` package)
2. `git clean -fdx` of the `pytorch` dir
3. Applied patch using `scripts/patch-pytorch.sh` in `pytorch` dir
4. `git clean -fdx` of the `intel-xpu-backend-for-triton`
5. Built triton using `scripts/compile-triton.sh --venv`
6. `source .venv/bin/activate` to activate the environment
7. Build pytorch using `scripts/compile-pytorch-ipex.sh --venv --source --upstream-pytorch`

My HW/SW config is the following:
CPU: Intel Xeon 8469
GPU: Intel GPU Max 1550
OS: Ubuntu 22.04.4 LTS
GPU Driver: 950.13
oneAPI 2024.2.1

Can anyone help us?

**Comment by vlad-penkin** [comment]
@jgtong 

1. Upstream Pytorch and Triton works only with the PyTorch Dependency Bundle, regular BaseKit 2024.x is not supported. Please install PTDB 0.5.3 and matching PTI - - [PyTorch Dependency bundle](https://www.intel.com/content/www/us/en/developer/articles/tool/pytorch-prerequisites-for-intel-gpu/2-5.html#inpage-nav-1-1)
 
2. There is no need to run separately `scripts/patch-pytorch.sh` and use '--source' option to run `compile-pytorch-ipex.sh`

Could you please check whether the issue is reproducible with the PTBD, pytorch and triton clean builds.

**Comment by jgtong** [comment]
> @jgtong
> 
>     1. Upstream Pytorch and Triton works only with the PyTorch Dependency Bundle, regular BaseKit 2024.x is not supported. Please install PTDB 0.5.3 and matching PTI - - [PyTorch Dependency bundle](https://www.intel.com/content/www/us/en/developer/articles/tool/pytorch-prerequisites-for-intel-gpu/2-5.html#inpage-nav-1-1)
> 
>     2. There is no need to run separately `scripts/patch-pytorch.sh` and use '--source' option to run `compile-pytorch-ipex.sh`
> 
> 
> Could you please check whether the issue is reproducible with the PTBD, pytorch and triton clean builds.

Thank you @vlad-penkin for your promptness. I will try out these instructions and report back to you on the results.

**Comment by jgtong** [comment]
@vlad-penkin 

Thanks for your advice. I was able to get elapsed time from my triton kernels
