### ISSUE TITLE
[benchmarks] Enable TorchBench benchmark suite

### ISSUE THREAD

**Issue by vlad-penkin** [intel/intel-xpu-backend-for-triton#199]

**Comment by etiotto** [comment]
@vlad-penkin can we clarify in the description what this work item entails ? I see that in Triton (https://github.com/openai/triton/blob/main/.github/workflows/torch-inductor-tests.yml) we have this:

```
 ./.github/workflows/torch-inductor/scripts/install_torchinductor.sh torchbench
  ./.github/workflows/torch-inductor/scripts/run_torchinductor_perf.sh torchbench
```

Is that what you have in mind for this work item?

@alexbaden your opinion please.

**Comment by vlad-penkin** [comment]
@etiotto this is first part of the issue scope, second is to start running this benchmark suite regularly.

@alexbaden could you please update this issue and provide more details in description?

**Comment by ESI-SYD** [comment]
Hi, I think we may address some block issues firstly to enable E2E test in llvm-target. You can get some explanation from https://github.com/intel/intel-xpu-backend-for-triton/issues/224

**Comment by tdeng5** [comment]
PyTorch team will provide a workable version to match current Triton master API.

**Comment by alexbaden** [comment]
When?

**Comment by alexbaden** [comment]
@tdeng5 I am reassigning this issue to you and your team since they have been working closely with IPEX on benchmark enabling. If you can produce a list of benchmarks that do not run and create an issue for each, I would be happy to help with resolving the discovered issues once all benchmark suites have been run.

**Comment by tdeng5** [comment]
TorchBench benchmark suite can run now, for the failed models, we are filing issues to track them one by one.

![image](https://github.com/intel/intel-xpu-backend-for-triton/assets/963815/ebd50afc-add9-4ed8-af4d-b6d33aae5e31)
