### ISSUE TITLE
Add `pylint` to the pre-commit checks

### ISSUE THREAD

**Issue by vlad-penkin** [intel/intel-xpu-backend-for-triton#2001]
@pbchekin, @ZzEeKkAa  feel free to provide your recommendations on the `pylint` config.

**Comment by pbchekin** [comment]
First, we need to enable `ruff`, which is used in upstream, for our code (`benchmarks`, `third_party/intel`).

**Comment by pbchekin** [comment]
Enabling `ruff` for `benchmarks` in #2009.

**Comment by anmyachev** [comment]
Why add `pylint` if we are going to use `ruff`?

**Comment by pbchekin** [comment]
> Why add `pylint` if we are going to use `ruff`?

If ruff has enough checks, then we will use ruff only: i will run pylint after enabling ruff and check if pylint finds other issues.

**Comment by pbchekin** [comment]
We will enable pylint in addition to ruff and will gradually enable the following checks:
* missing-module-docstring
* missing-function-docstring
* invalid-name (Argument name doesn't conform to snake_case naming style)
* wrong-import-order

and others. Initially most of the checks will be disabled, we will fix enable them in steps and fix the existing code.

**Comment by pbchekin** [comment]
Blocked by #2016.
