### ISSUE TITLE
[GEMM] Improve shapes with performance <95% of XeTLA

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#2024]
Shapes need to investigate what features are missing on default path from advanced path:
- [ ] 1, 2048, 2048, 2048
- [ ] 1, 8192, 8192, 8192

Shapes that need to come up with new performance opportunities:
- [x] 4096, 8, 128, 16384 #2434

Shapes need to productize environment variables: https://github.com/intel/intel-xpu-backend-for-triton/issues/1972
- [x] 1, 1024, 1024, 1024 #2822
- [ ] 1, 8192, 16384, 4096 #2796 #2435

Streamk:
- [ ] 1, 3072, 4096, 3072 #2368

Variance?:
- [x] 1, 4096, 4096, 4096
- [x] 1, 512, 32768, 8192

**Comment by etiotto** [comment]
@whitneywhtsang  can you link to this umbrella issue the issues for improving the different shapes please.

**Comment by whitneywhtsang** [comment]
> @whitneywhtsang can you link to this umbrella issue the issues for improving the different shapes please.

I need to create them first ;)

**Comment by etiotto** [comment]
I would say we need to focus only on the lowest performance (improving those shapes may improve performance for other shapes that are also on the low side).

**Comment by whitneywhtsang** [comment]
One issue is created per section described in the description of this issue.

**Comment by whitneywhtsang** [comment]
2024-11-29:
![Screenshot 2024-11-29 121131](https://github.com/user-attachments/assets/ae2d3eff-baf8-4ca8-abd1-6fcc07f4834c)

**Comment by whitneywhtsang** [comment]
2024-12-01:
![Screenshot 2024-12-01 171659](https://github.com/user-attachments/assets/ad5759ea-0982-4548-9f7f-8171defe2e1c)

**Comment by whitneywhtsang** [comment]
2024-12-02:
![Screenshot 2024-12-02 093350](https://github.com/user-attachments/assets/27819f35-5a91-4d9e-8cad-df44e82e5060)

**Comment by whitneywhtsang** [comment]
All shapes can get >95%, sometimes the results are <95% due to variances.
