### ISSUE TITLE
Fix and enable tests in `test_subprocess.py`

### ISSUE THREAD

**Issue by etiotto** [intel/intel-xpu-backend-for-triton#205]
Add `test_subprocess.py` to CI and `test-triton.sh`.

**Comment by whitneywhtsang** [comment]
@pengtu `test_subprocess.py` is related to features that you worked on (assert, print), can you please take a look at this issue?

**Comment by etiotto** [comment]
I have a PR to fix `tl.print` and I will publish shortly another PR that enables test_subprocess.py (which calls the print and assert related tests in print_helper.py and assert_helper.py).

**Comment by etiotto** [comment]
With PRs #292 and #303 we can now pass most print relates tests in `test_subprocess.py`. There are some tests that do not work yet, namely:
  - `test_print` with arg "device_print_large"
  - `test_assert` with arg "device_assert", "assert", "no_debug", "double_assert"
  - `test_assert_nested`

**Comment by etiotto** [comment]
We can close this work item. The functional problems discovered are tracked by issues listed in https://github.com/intel/intel-xpu-backend-for-triton/issues/205#issuecomment-1899360646
