### ISSUE TITLE
Can I use the Triton on Intel CPUs through the intel-xpu-backend-for-triton project?

### ISSUE THREAD

**Issue by Mark3123** [intel/intel-xpu-backend-for-triton#2062]
Can I use the Triton on Intel CPUs through the intel-xpu-backend-for-triton project? I'm currently very interested in using it on Intel CPUs.

**Comment by vlad-penkin** [comment]
@ienkovich, could you please elaborate on the current status of the [Triton CPU initiative](https://github.com/triton-lang/triton-cpu) and provide more information?

**Comment by etiotto** [comment]
@Mark3123 this github repo does not contain the CPU BE for Triton. That project is maintained separately in https://github.com/triton-lang/triton-cpu at least for the time being.

**Comment by Mark3123** [comment]
@etiotto thank you.
