### ISSUE TITLE
Upstream changes in Ops.cpp

### ISSUE THREAD

**Issue by etiotto** [intel/intel-xpu-backend-for-triton#2065]
PR #2064 removed changes in `ops.cpp` to make it common with the upstream code. To get that change back we need to upstream it to OpenAI. The Change is:

![image](https://github.com/user-attachments/assets/c6b01883-8e62-48c8-95f4-20d337f82881)

**Comment by chengjunlu** [comment]
Upstream PR is under review:
https://github.com/triton-lang/triton/pull/4630

**Comment by chengjunlu** [comment]
Close this issue as the PR has been merged.

**Comment by whitneywhtsang** [comment]
Merged in https://github.com/intel/intel-xpu-backend-for-triton/pull/2120.
