### ISSUE TITLE
Upstream changes in `LinearLayoutConversion.cpp`

### ISSUE THREAD

**Issue by etiotto** [intel/intel-xpu-backend-for-triton#2066]
PR # 2064 removed changes in `LineraLayoutConversion.cpp`. These changes should be upstreamed to the Triton OpenAI repo.

![image](https://github.com/user-attachments/assets/9159a610-c33e-4c78-85f7-b151a0ab6814)
![image](https://github.com/user-attachments/assets/fe1b586e-b5b1-42e7-8004-cf7bceb7f4f7)

**Comment by etiotto** [comment]
@whitneywhtsang can @hwnam831  work on this ?

**Comment by whitneywhtsang** [comment]
> @whitneywhtsang can @hwnam831 work on this ?

@hwnam831 finished his work term, and is back to school.

**Comment by etiotto** [comment]
Upstream PR https://github.com/triton-lang/triton/pull/4617

**Comment by whitneywhtsang** [comment]
Merged in https://github.com/intel/intel-xpu-backend-for-triton/pull/2081.
