### ISSUE TITLE
[test_typeconvert_upcast]: Fails to run correctly on PVC

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#213]
The end-to-end core test `test_typeconvert_upcast` in `test_conversions.py` fails to run correctly on a PVC when source type is "float8e4nv" or when source type is "float8e5" and dst type is "bfloat16".

**Comment by kurapov-peter** [comment]
This is a funny one. I checked fp8e5 to bf16. So apparently there are two problems here: we incorrectly upcast zeroes to `0x38000000` and there is exactly a `800000` discrepancy for each 128th element.

**Comment by kurapov-peter** [comment]
So to clarify the initial assessment. Basically this is not even a bug. The implementations for those casts just don't handle subnormal values. The solution is simply to add it.

**Comment by kurapov-peter** [comment]
Also, I think what we should do long term is expose the convert instruction in genx and lower to a genx op instead of providing an implementation (or go the same way as openai and insert inline assembly).
