### ISSUE TITLE
Some configuration of the XeTLA kernel in the GEMM benchmark are not best optimal.

### ISSUE THREAD

**Issue by chengjunlu** [intel/intel-xpu-backend-for-triton#2137]
Some configuration of the XeTLA kernel in the GEMM benchmark are not best optimal. Need to re-confirm the XeTLA's configuration to get the best performance.

E.G:
https://github.com/intel/intel-xpu-backend-for-triton/blob/84c74ed4cc52423d0205b407f66b4af7832605a3/benchmarks/xetla_kernel/gemm/gemm_config.hpp#L563

**Comment by ESI-SYD** [comment]
These configs come from xelta' repo, used in Triton demo comparison.
https://github.com/intel/xetla/blob/benchmark/tests/integration/gemm/bf16/common.hpp
https://github.com/intel/xetla/blob/benchmark/tests/integration/gemm/bf16/habana_tests.hpp

**Comment by chengjunlu** [comment]
I think those configuration are functionality test rather than performance test.
We need to manually chose the better configuration for now. There is no auto-tune suit for XeTLA kernel. Is there?

**Comment by ESI-SYD** [comment]
They are for perf benchmark purpose.
Origin form this [branch](https://github.com/intel-innersource/libraries.gpu.xetla/tree/jiaxing/collecting_perf/tests/integration/gemm/bf16) , tuned and tested by XeTLA team, as reference for triton demo, ported in our benchmark.

But I agree that some cfg maybe not best optimal. Actually we have updated cfg for 1024x28672x8192 and typo fix during Triton demo [preparation.](https://github.com/intel/intel-xpu-backend-for-triton/blob/triton_perf_poc/python/tutorials/performance_collection.md) I'm not sure if there is auto-tune suit for xetla.
