### ISSUE TITLE
Compile and run OpenAI Triton on NV machine

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#214]
Please document your steps and any difficulties you encountered.

**Comment by prathams417** [comment]
[Compile-Triton-RTX6000.md](https://github.com/intel/intel-xpu-backend-for-triton/files/13879093/Compile-Triton-RTX6000.md)

**Comment by etiotto** [comment]
@prathams417 thanks for documenting the steps to compiler and test Triton on a NV GPU. Can you please add the documentation to the https://github.com/intel/intel-xpu-backend-for-triton/wiki, then we can close this work item. Thanks.

**Comment by prathams417** [comment]
https://github.com/intel/intel-xpu-backend-for-triton/wiki/Compile-and-run-OpenAI-Triton-on-NV-machine-from-scratch
