### ISSUE TITLE
Benchmark flash attention is failed in CI

### ISSUE THREAD

**Issue by anmyachev** [intel/intel-xpu-backend-for-triton#2144]
I see strange things in the output like: `/llvm/bin/mlir-tblgen: Permission denied`

https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10729525320

cc @pbchekin

**Comment by pbchekin** [comment]
This job still uses the old branch `perf_attn`, which needs to be merged to the default branch. I think it is blocked by #1909.

**Comment by whitneywhtsang** [comment]
Resolved by https://github.com/intel/intel-xpu-backend-for-triton/pull/2157.
