### ISSUE TITLE
Torch inductor tests failed for PyTorch main

### ISSUE THREAD

**Issue by pbchekin** [intel/intel-xpu-backend-for-triton#2206]
Workflow run: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10807633001/job/29978846091
PyTorch commit id: 443c01539390a59e012ed5ef7e81f5b04a7c3603

One of the errors:

```
=========================== short test summary info ============================
FAILED [0.0056s] inductor/test_triton_kernels.py::KernelTests::test_layout_constraint_needs_fixed_stride_order - AssertionError: Torch not compiled with CUDA enabled
```

**Comment by alexbaden** [comment]
Should be fixed by https://github.com/pytorch/pytorch/pull/135779 
I think we can wait for it to be merged then update the pin again.

**Comment by pbchekin** [comment]
Fixed.
