### ISSUE TITLE
Create a private branch, include the latest Triton and SPIR-V path Triton backend source code.

### ISSUE THREAD

**Issue by tdeng5** [intel/intel-xpu-backend-for-triton#222]
# Issue Description

For PyTorch upstreaming support, provide a private branch, include the latest Triton and SPIR-V path Triton backend source code.

Why not use llvm-path code?
A: the requirement is urgent, and the llvm-path is not mature as spirv-path impl ( spirv-path code and successfully run UT and E2E). will switch to llvm-path in the future.

# Code Example

# System Info
- OS:
- PyTorch:
  
- Intel Extension For Pytorch:
  
- LLVM Version.
  
- Triton Version:
  
- Intel® XPU Backend for Triton*:

**Comment by LiyangLingIntel** [comment]
Based on the situation that intel pytorch upstreaming and triton upstream refactoring, there are 2 triton fork branches.
1. [triton-fork/release/2.2.x](https://github.com/intel/intel-xpu-backend-for-triton/commits/triton-fork/release/2.2.x): this is based on e28a256d71 which is the [commit pin](https://github.com/pytorch/pytorch/blob/75818adcf74e8139ac98c8e30e93283ac1317120/.ci/docker/ci_commit_pins/triton.txt) used in current Pytorch main branch
2. [triton-fork/spirv-path](https://github.com/intel/intel-xpu-backend-for-triton/commits/triton-fork/spirv-path/): this is for the potential case that pytorch update its triton pin to a refactored one. There is a WIP PR [#115881](https://github.com/pytorch/pytorch/pull/115881) for this case. This fork branch pick 073f53297a as base referring to this PR.

**Comment by vlad-penkin** [comment]
@LiyangLingIntel can we close this issue?

**Comment by LiyangLingIntel** [comment]
Close this issue as this task is done.
