### ISSUE TITLE
Track UT gaps for LLVM-path vs SPIRV-path.

### ISSUE THREAD

**Issue by tdeng5** [intel/intel-xpu-backend-for-triton#223]
# Issue Description

 Collect the latest UT report for both LLVM-path and SPIRV-path, check the failed cases. High priority for fixing those bugs which failed in LLVM-path while pass in SPIRV-path.

# Code Example

# System Info
- OS:
- PyTorch:
  
- Intel Extension For Pytorch:
  
- LLVM Version.
  
- Triton Version:
  
- Intel® XPU Backend for Triton*:

**Comment by ESI-SYD** [comment]
## UT Status in main branch [SPIRV-path](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/7327922281/job/19955453499)
============ **Overview** ============
num_language: 6859
num_others: 901
num_total: 7760
num_skipped: 1158
num_cuda_only_skipped: 637
num_failed: 995
num_passed: 5607
total_pass_rate: 77.49%
num_new_solved_expected_cases: 5
num_new_solved_todo_cases: 32
num_new_failed_cases: 943
num_new_failed_not_todo_cases: 0

[**failed cases**](https://github.com/intel/intel-xpu-backend-for-triton/tree/main/.github/tests)

## UT failed cases in llvm-target branch: [llvm-path](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/7453690196/job/20279592177)

============ **Overview (core tests)** ============
**=== 5422 passed, 392 skipped, 1165 xfailed, 56 warnings in 816.25s (0:13:36) ===**
**=== 5422/(5422+392+1165) = 5422/6979 = 77.69% ===**

### xfail cases
test_core.py::test_atomic_rmw #152
test_core.py::test_convert2d [skip]
test_core.py::test_convertmma2mma [test_mma2mma is not supported in HIP/XPU]
test_core.py::test_dot [skip]
test_core.py::test_fp8_dot_acc [test_fp8_dot_acc not supported on XPU]
test_core.py::test_reduce_layouts #156

### cuda only
test_core.py::test_globaltimer
test_core.py::test_num_threads
test_core.py::test_smid
test_core.py::test_inline_asm[1]
test_core.py::test_inline_asm_multiple_outputs
test_core.py::test_inline_asm_packed[1]
test_core.py::test_inline_asm_packed_multiple_outputs
test_core.py::test_inline_asm_with_pointers[1]

### skipped as FIXME issue
test_core.py::test_scan2d #153
test_core.py::test_locality #154
test_core.py::test_scan_layouts #155
test_core.py::test_reduce_layouts #156
test_core.py::test_chain_reduce #164
test_core.py::test_masked_load_shared_memory #158
test_conversions.py::test_typeconvert_downcast
test_conversions.py::test_typeconvert_upcast

### Note
No more cases passed in spirv-path but failed in llvm-path expect for **Not** ported and enabled operator/runtime/tools cases

**Comment by etiotto** [comment]
Overall I would say no surprises here. This information was known already, I have opened issues to track the functional problems which are also linked in this work item.

**Comment by ESI-SYD** [comment]
closing, find specified work item from opening issues, free free to reopen

**Comment by vlad-penkin** [comment]
llvm branch have reached the parity with the spirv on the ut pass rate
