### ISSUE TITLE
CXX tests not running in CI

### ISSUE THREAD

**Issue by anmyachev** [intel/intel-xpu-backend-for-triton#2238]
```bash
***************************************************
******      Running Triton CXX unittests     ******
***************************************************
Test project /runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/python/build/bdist.linux-x86_64
No tests were found!!!
```

https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10839982281/job/30081443608

**Comment by anmyachev** [comment]
cc @pbchekin @leshikus

**Comment by etiotto** [comment]
> cc @pbchekin @leshikus
> 
> should it be `python/build/cmake*`?

I think so.

**Comment by pbchekin** [comment]
Regression as a result of https://github.com/intel/intel-xpu-backend-for-triton/pull/2183/files#diff-4d5d42f64f4d5eb186307a9233a4e4a467e3c5640ab980de05ac5a16694a26c6R167

**Comment by leshikus** [comment]
Sorry, guys, the correct path was missed during one of rebases. Thanks for finding this and fixing
