### ISSUE TITLE
Subset of E2E models for accuracy tests

### ISSUE THREAD

**Issue by pbchekin** [intel/intel-xpu-backend-for-triton#2246]
We currently have a [subset](https://github.com/intel/intel-xpu-backend-for-triton/tree/llvm-target/.github/models/performance) of models to test E2E performance. We need similar subset for E2E accuracy tests. If the E2E accuracy workflow started with the subset, it should check that all models in the subset passed the accuracy check.

Periodic E2E jobs (E2E accuracy, Try latest PyTorch) need to use the subset mode to catch regressions early.

**Comment by vlad-penkin** [comment]
@pbchekin this ticket partially duplicates 
- #2164 
 
Let's align scope between two tickets.
