### ISSUE TITLE
Pathfinding SIMD path for better performance

### ISSUE THREAD

**Issue by tdeng5** [intel/intel-xpu-backend-for-triton#225]
# Issue Description

Pathfinding SIMD path for better performance.

# Code Example

# System Info
- OS:
- PyTorch:
  
- Intel Extension For Pytorch:
  
- LLVM Version.
  
- Triton Version:
  
- Intel® XPU Backend for Triton*:

**Comment by Dewei-Wang-sh** [comment]
duplicate issue
