### ISSUE TITLE
[UT] Rerun failed core tests 

### ISSUE THREAD

**Issue by Retribution98** [intel/intel-xpu-backend-for-triton#2275]
Some workers crash when running core tests on some systems

**Comment by pbchekin** [comment]
Reopening to configure specific environments / runners, where crashed were observed.

**Comment by pbchekin** [comment]
With #2316 all core test passed with 1 pytest worker on the runner under consideration. The run itself is 2.5 times longer, which is acceptable. At the same time confirmed that the old runner with 8 pytest workers shows inconsistent results: the number of failed core tests varies from 2 to 6 for the same commit id.
