### ISSUE TITLE
build-test workflow always uses `--ignore-errors`

### ISSUE THREAD

**Issue by pbchekin** [intel/intel-xpu-backend-for-triton#2288]
See https://github.com/intel/intel-xpu-backend-for-triton/blob/main/.github/workflows/build-test-reusable.yml#L126

```
echo TRITON_TEST_CMD="bash -v -x scripts/test-triton.sh --warning-reports --skip-pytorch-install --reports-dir $GITHUB_WORKSPACE/reports --ignore-errors $skiplist"
```

This option should be added only if `ignore_errors` is `true`.

**Comment by anmyachev** [comment]
Fixed by https://github.com/intel/intel-xpu-backend-for-triton/pull/2293
