### ISSUE TITLE
Cherry pick fix for #2188 into release/3.1.x

### ISSUE THREAD

**Issue by dvrogozh** [intel/intel-xpu-backend-for-triton#2297]
Can a fix for https://github.com/intel/intel-xpu-backend-for-triton/issues/2188, please, be cherry-picked to release/3.1.x branch? I.e. these 2 commits:
* https://github.com/intel/intel-xpu-backend-for-triton/commit/b6e5fd2ddf413ae1286d2e50b58778537de28843
* https://github.com/intel/intel-xpu-backend-for-triton/commit/2abe039a2cc8fea26c1745560c8c3b671d95926d

@vlad-penkin

**Comment by EikanWang** [comment]
Please do **NOT** land this PR to release/3.1.x. Otherwise, it will block PyTorch XPU 2.5 release because we do **NOT** plan to land https://github.com/pytorch/pytorch/pull/135567 to PyTorch XPU 2.5.

**Comment by EikanWang** [comment]
@riverliuintel
