### ISSUE TITLE
Logs for "Automate update Translator cid" are not readable

### ISSUE THREAD

**Issue by pbchekin** [intel/intel-xpu-backend-for-triton#2302]
For example: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10950266371/job/30405179010

The log is too big it is almost impossible to see the compilation / testing results in a reasonable time. The verbosity of the workflow needs to be reduced. Also it should clearly print what translator commits have been verified and what was the result (exact error message) for each commit.

**Comment by AshburnLee** [comment]
It is working in progress.

**Comment by AshburnLee** [comment]
In review

**Comment by AshburnLee** [comment]
The attached PR meets the target, check comments:
https://github.com/intel/intel-xpu-backend-for-triton/pull/2319#issuecomment-2401704522
