### ISSUE TITLE
[test_max_num_imprecise_acc]: Fails to run correctly on PVC

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#231]
The end-to-end core test `test_max_num_imprecise_acc` fails to run correctly on a PVC GPU. We need to investigate the cause of the functional problem(s).

**Comment by etiotto** [comment]
The issue currently is the problem size. With:

-  M, N, K, num_warps, MAX_NUM_IMPRECISE_ACC = 128, 128, 128, 4, 64

the test fails, but with a smaller problem size:

-  M, N, K, num_warps, MAX_NUM_IMPRECISE_ACC = 128, 64, 64, 4, 64

it passes. The error is `RuntimeError: Triton Error [ZE]: 1879048196`.

I am not sure who emits the error above, speculating is during the kernel setup when the data is copied from the XPU memory to the GPU.
