### ISSUE TITLE
try-latest-pytorch does not use the latest pytorch

### ISSUE THREAD

**Issue by pbchekin** [intel/intel-xpu-backend-for-triton#2315]
https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10987962296/job/30503642580#step:2:17

`pytorch_ref` is not set for "Inductor tests", so instead of the latest commit used the pinned one.

```
{
  "pytorch_ref": "",
  "suite": "inductor/test_codegen_triton.py inductor/test_triton_extension_backend.py inductor/test_triton_heuristics.py inductor/test_triton_wrapper.py inductor/test_triton_kernels.py",
  "runner_label": "",
  "python_version": "3.9",
  "pytorch_repo": "pytorch/pytorch"
}
```

**Comment by kwasd** [comment]
This is not inductor tests workflow problem, this is problem in `try-latest-pytorch.yml` and also affects other tests.
The commit ID remains empty if `get-commit-id` got empty branch as input. This is fixed for `try-latest-pytorch.yml` in #2321 

Before fix: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10987962296/job/30503634842#step:4:14
After fix: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/11013947939/job/30583453655#step:4:15
