### ISSUE TITLE
Allocation analysis only consider `NvidiaMmaEncodingAttr`

### ISSUE THREAD

**Issue by LiyangLingIntel** [intel/intel-xpu-backend-for-triton#2340]
Triton shared memory allocation pass only convert tensor layout to `NvidiaMmaEncodingAttr`.
https://github.com/intel/intel-xpu-backend-for-triton/blob/6955edf097b076e2154cd7a4d85c68686d76a1e2/lib/Analysis/Allocation.cpp#L42-L46.

This would make it get incorrect allocation size for Intel GPU cases.

**Comment by etiotto** [comment]
This is no longer applicable because upstream has change `Allocation.cpp` and the NVidia specific lines in the abstract aren't there any longer. Removed as part of https://github.com/triton-lang/triton/commit/9293f0a24e07a9fc17272fed665b60529bb20ad4
