### ISSUE TITLE
spirv.UGreaterThan does not support 'i1'

### ISSUE THREAD

**Issue by CuiYifeng** [intel/intel-xpu-backend-for-triton#235]
# Issue Description
Intel-xpu-backend-for-triton `>` operator does not support `i1` but triton for CUDA can.

# Code Example
    tmp83 = tmp77 != tmp77
    tmp84 = tmp80 != tmp80
    tmp85 = tmp83 > tmp84
Please find example in attachment. 
[maml_cuda.txt](https://github.com/intel/intel-xpu-backend-for-triton/files/13898654/maml_cuda.txt) is triton code generated with Pytorch CUDA. The above triton code segment also appears in it.
[maml_xpu_to_cuda.txt](https://github.com/intel/intel-xpu-backend-for-triton/files/13898658/maml_xpu_to_cuda.txt) is triton code generated with XPU backend. It works with Pytorch CUDA after replacing the header. 

# System Info
- Triton Version:
  607190fda19daa9ecbccd7b10ed49d24b7916fd2
- Intel® XPU Backend for Triton*:
  645ee06f6a276fa53273315c95fc75e9fd28aeda

**Comment by aregm** [comment]
This is related to SPIR-V lowering path. Can you please recheck after migration to the llvm-target.

**Comment by tdeng5** [comment]
Will double check if this issue happens in LLVM path when E2E could run.

**Comment by vlad-penkin** [comment]
The llvm branch has reached parity with the spirv branch in terms of the UT pass rate. Closing the issue.
