### ISSUE TITLE
Consider interop options for triton runtime and pytorch's aten implementation for intel GPUs

### ISSUE THREAD

**Issue by kurapov-peter** [intel/intel-xpu-backend-for-triton#236]
There are two aspects of the task: 
1. There is a particular problem with synchronization to data movement sycl queues (triton and pytorch's upstream data movement have to exchange synchronization events).
2. The overall strategy on memory management (sycl runtime is a bit higher overhead and brings additional dependencies in) between components needs to be settled.

**Comment by kurapov-peter** [comment]
# Current state & Motivation
Triton backend for Intel GPU uses an API to interact with the GPU driver. [Upstream work](https://github.com/pytorch/pytorch/issues/114723) on eager mode operator implementation relies on SYCL runtime to allocate and move device memory, invoke kernels, and synchronize those GPU queues. Current packaging assumes users install oneAPI base toolkit to have access to the runtime library. Triton’s initial runtime implementation is Level Zero based. It faced synchronization problems when interacting with IPEX and the currently proposed solution is to introduce SYCL runtime dependency for Triton. 

Thoroughly designing components interaction provides an opportunity for user experience and performance improvements.

# Analysis results
Triton needs a runtime to bundle a kernel invocation as well as memory movement to and from GPUs. The are three main options to consider: SYCL runtime, Level Zero runtime, and Unified runtime.

Triton is usually used together with pytorch in a sense that Triton kernels consume pytorch tensors and often represent some custom operation. Hence, Triton runtime needs to interact with pytorch components to guarantee synchronization. These components include:

- The basic device memory allocation & movement (e.g., `torch.randn(1823, 781, device='xpu')`)
- Aten operators’ implementations via oneDNN
- Pytorch distributed modes via oneCCL
- Habana’s Synapse backend (oneDNN + custom compiler)

Fundamentally, a pytorch+triton package needs to be able to allocate and move device memory, run kernels, and synchronize on events. All of these can be done at the lowest level (L0).

Using the lowest level possible has following benefits:
- Minimizing the number of dependencies of the package. E.g., Level Zero is a self-contained small (~200KB) loader library that is easily packaged.
- Minimizing the overhead of operation invocations. I.e., SYCL introduces additional layers of abstraction atop Leve Zero API.
- Stabilizing the interface. I.e., having lower-level stable API at the bottom frees the package from updates and compatibility issues as well as allows easier higher level abstractions evolution.
- Narrowing the surface of potential package conflicts.

Using SYCL runtime benefits are:
- Improving the quality of SYCL components by exposing them to more usage scenarios.
- Tactical short-term development speed-up as some of the functionality can be reused (e.g., IPEX memory management).

The key to providing seamless access to Intel’s hardware is frictionless user experience. From user’s perspective, a library is expected to have the minimal possible set of dependencies, not have conflicts with other installations that they might have and be “debugable” and well documented. Triton as a component has no meaningful dependency on SYCL runtime, so applying the above principles it should use the lowest layer possible.

The main technical obstacle in using L0 or Unified runtime for all the components is the presence of the host part of SYCL kernels developed by oneDNN. Internal wrapper structures and integration headers make it complex to execute SYCL fat binaries to be executed by a lower-level runtime. Although possible via dumping the IR/assembly generated by the SYCL compiler and feeding them to lower-level runtime directly for device code and generating the integration headers (e.g., similar technique is used by Unified runtime for CTS tests), the mechanism is ad-hoc.

Components interaction surface is limited to synchronization, that is, passing and consuming events and waiting on them. Having one component use low-level runtime and the other one a high-level creates interoperability issue. This is partially covered by existing functionality such as [Native Driver Access](https://oneapi-src.github.io/unified-runtime/core/PROG.html#native-driver-access) but there are scenarios in which the support is not enough. An example of this would be a component using L0 runtime submitting a kernel and passing control flow to a component that uses SYCL runtime. The latter does not wait on the native L0 queue to drain before reading the data.

Ultimately this means that Triton is forced to have a dependency on SYCL runtime only to wrap the native queue handles for other components to respect the synchronization point.

# Directions
Going forward, removing SYCL runtime dependency from Triton can be achieved with some joint effort (Triton, upstream work for memory allocation, oneDNN, oneCCL, and runtimes). Without significant changes to runtimes there are two areas of improvement: data allocation and movement API and synchronization with SYCL-based components.

Memory allocation and movement does not depend on SYCL and can be consumed by SYCL-based components with relatively minor changes. Using Unified runtime is an appealing option as it has the necessary interop capabilities with L0 and can potentially become the standard mechanism for accelerator interaction in pytorch. It also does not restrict the language choice for kernels implementation and may avoid the need for additional runtimes interop features.

Pytorch has a [mechanism of streams](https://pytorch.org/docs/stable/generated/torch.cuda.Stream.html#torch.cuda.Stream) (a linear sequence of execution that belongs to a specific device) to orchestrate kernel invocation and data movement. Using pytorch’s synchronization abstractions can help decouple Triton kernels and Aten operator implementations by communicating via a stream (handled at the Inductor level). The stream can use a low-level runtime and have wrappers for SYCL-based consumers. Its implementation will live inside pytorch as a separate component.

There is also an option to introduce SYCL kernel invocation support into Unified runtime to make it indifferent to the input. This path allows for putting Unified runtime as the first-class citizen tool for all the components.

Triton will have an opportunity to be used without pytorch while not having a redundant dependency on SYCL runtime and display all the beneficial qualities of relying on a low-level runtime.

# Proposed actions

1. Evaluate Unified Runtime application as the basis for tensor memory allocation and movement in presence of SYCL-based and L0 based consumers. Address the concern of additional effort from SYCL-based components.
2. Identify the requirements for stream implementation and map them to a low-level runtime API.
3. Bring up the idea of supporting SYCL kernel invocation to UR forum.

**Comment by kurapov-peter** [comment]
@aregm, @alexbaden, @whitneywhtsang, @etiotto, @Dewei-Wang-sh, @Sarbojit2019, @pbchekin, @pengtu, @chengjunlu, @ienkovich, @quintinwang5, @ESI-SYD, @vlad-penkin, @Jianhui-Li, thoughts?
Please ping relevant people.

**Comment by etiotto** [comment]
This is a good description of the problems we are facing with using the L0 runtime. Tactically, in the short term, as a practical solution we are going to use the SYCL RT.  Depending on timeline, we might switch to use the L0 runtime once synchronization issues are resolved.

**Comment by vlad-penkin** [comment]
@kurapov-peter to add research results to the documentation as a research paper. After it this issue can be closed.
