### ISSUE TITLE
Conda based build

### ISSUE THREAD

**Issue by kurapov-peter** [intel/intel-xpu-backend-for-triton#237]
We should not expect users to install the base toolkit for torch to work on Intel GPUs. A system-wide installed driver is enough.

**Comment by kurapov-peter** [comment]
There's a known issue with versions 2024.0.2 and 2024.0.1 btw, only 2024.0.0 works for compilation.

**Comment by pbchekin** [comment]
> There's a known issue with versions 2024.0.2 and 2024.0.1 btw, only 2024.0.0 works for compilation.

What is the issue?

**Comment by kurapov-peter** [comment]
Not familiar with the details, but it doesn't work - tried it myself.

**Comment by pbchekin** [comment]
> Not familiar with the details, but it doesn't work - tried it myself.

The reason I am asking about the compilation issue is that I have a successful build in conda environment, but 3 failed (out of 5k+) core tests, so I am trying to understand if we are talking about the same issue.

**Comment by pbchekin** [comment]
```
3 failed, 5303 passed, 381 skipped, 1142 xfailed, 53 warnings in 1398.80s (0:23:18)
FAILED test_core_xpu.py::test_chain_reduce[0-sum-src_layout3-256-128] - AssertionError:
FAILED test_core_xpu.py::test_chain_reduce[1-sum-src_layout3-128-128] - AssertionError:
FAILED test_core_xpu.py::test_chain_reduce[1-max-src_layout3-128-128] - AssertionError:
```

**Comment by kurapov-peter** [comment]
Oh, I meant I tried sycl compilation. I didn't try triton.

**Comment by pbchekin** [comment]
Delayed by #173 and #358, still in progress.

**Comment by leshikus** [comment]
the builds are complete, there is some work to be done fixing the compiler and the tests
