### ISSUE TITLE
SPIRV Runner: Improve the serialize args dictionary pattern

### ISSUE THREAD

**Issue by kballeda** [intel/intel-xpu-backend-for-triton#2389]
At preset we process tensors and scalarArgs independently in following pattern,
```
{
  "gridX": 97,
  "gridY": 1,
  "gridZ": 1,
  "num_warps": 4,
  "threads_per_warp": 32,
  "shared_memory": 0,
  "kernel_name": "add_kernel",
  "spv_name": "add_kernel.spv",
  "tensor_9": "torch.float32",
  "tensor_10": "torch.float32",
  "tensor_11": "torch.float32",
  "scalarArg_12": 98432
}
```
As per the request here - https://github.com/intel/intel-xpu-backend-for-triton/pull/2258#pullrequestreview-2338336020 , https://github.com/intel/intel-xpu-backend-for-triton/pull/2258#issuecomment-2378981847
Use array of entries for tensors/scalarArgs as array of "arguments",  this helps in complexity of processing regex/string expressions in c++. Also, as part of serialization process, we are generating 2 files serialize_args.json and signature.json at present one that covers kernel arguments and other presents the actual kernel signature. Suggested JSON format change will help in generating single JSON file instead of two.

```
{
    "gridX": 97,
    "gridY": 1,
    "gridZ": 1,
    "num_warps": 4,
    "threads_per_warp": 32,
    "shared_memory": 0,
    "kernel_name": "add_kernel",
    "spv_name": "add_kernel.spv",
    "arguments": [
        {
            "name": "tensor_9",
            "type": "tensor",
            "dtype": "torch.float32",
            "ctype": "*fp32"
        },
        {
            "name": "scalarArg_12",
            "type": "scalar",
            "value": 98432
        }
    ]
}
```

**Comment by vlad-penkin** [comment]
This implementation requirement is part of:
- #1471

PR #2258 is still not merged, no need to create a duplicate issue.
