### ISSUE TITLE
Investigate commonality between AOT Inductor/Triton/SPIRV Runner and refactor SYCL kernel launcher

### ISSUE THREAD

**Issue by kballeda** [intel/intel-xpu-backend-for-triton#2395]
Find commonality between AOT Inductor needs, SPIRV Runner needs, and Triton needs and refactor the launch code in driver.py to separate out the SYCL-only parts. 

PyTorch AOT Inductor will also be using SYCL launch code for running Triton kernels outside of Triton
Reference: https://github.com/pytorch/pytorch/pull/135318/files#diff-2bbc58fcef7d498ae6d81ce8751f411d60ce5c4e8da9aa8dd95ccd29b64a1ba8

**Comment by vlad-penkin** [comment]
The preparation work for enabling AOT Inductor mode is in scope for
- #1792 

@alexbaden is this research task needed?
