### ISSUE TITLE
Can I help with providing early feedback ?

### ISSUE THREAD

**Issue by fcharras** [intel/intel-xpu-backend-for-triton#24]
I've been exploring writing kernels with [`numba_dpex`](https://github.com/IntelPython/numba-dpex/) which brings a `numba.cuda`-like interface to xpu-device, and I've also been following this project with great interest. If you can provide me with early install instructions I'd be very interested in early testing this backend on intel xpu devices (flex 170 GPU and iGPUs) and give feedback.

**Comment by EikanWang** [comment]
@fcharras , Thanks for your suggestion. This project is a git submodule of Triton. You just need to build Triton by setting an environment variable `TRITON_CODEGEN_INTEL_XPU_BACKEND=1`. Anyway, we will add a wiki page to express how to build Triton w/ Intel XPU backend.

**Comment by fcharras** [comment]
That's awesome thank you, trying that ASAP !

**Comment by fcharras** [comment]
I managed to compile but unfortunately I can't run triton examples, running a kernel fails with

> ValueError: Cannot find backend for xpu

(I suppose my environment is OK otherwise since compiling worked and pytorch+ipex is working well too :thinking: )

Do you have suggestions about what went wrong ? or maybe should I be more patient for install instructions or release of binaries :grinning:

**Comment by chengjunlu** [comment]
Hi @fcharras ,

It is glad to see you are trying out the Triton for XPU backend.

Could you share the version of the packages you are using?

**Comment by fcharras** [comment]
This is the output of the `collect_env.py` script taken from the intel_extension_for_pytorch repo:

```
Collecting environment information...
PyTorch version: 2.0.0a0+gite9ebda2
PyTorch CXX11 ABI: Yes
IPEX version: 2.0.110+gitb7412a4
IPEX commit: b7412a42
Build type: Release

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: N/A
IGC version: 2023.1.0 (2023.1.0.20230320)
CMake version: version 3.26.4
Libc version: glibc-2.31

Python version: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0] (64-bit runtime)
Python platform: Linux-5.14.0-1047-oem-x86_64-with-glibc2.31
Is XPU available: True
DPCPP runtime version: 2023.1.0
MKL version: 2023.1.0
GPU models and configuration: 
[0] _DeviceProperties(name='Intel(R) Graphics [0x56c0]', platform_name='Intel(R) Level-Zero', dev_type='gpu, support_fp64=0, total_memory=13535MB, max_compute_units=512, gpu_eu_count=512)
Intel OpenCL ICD version: 22.28.23726.1+i419~u20.04
Level Zero version: 1.3.23726.1+i419~u20.04

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 57 bits virtual
CPU(s):                          40
On-line CPU(s) list:             0-39
Thread(s) per core:              2
Core(s) per socket:              20
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           108
Model name:                      Intel(R) Xeon(R) D-2796NT CPU @ 2.00GHz
Stepping:                        1
Frequency boost:                 enabled
CPU MHz:                         900.000
CPU max MHz:                     2001.0000
CPU min MHz:                     800.0000
BogoMIPS:                        4000.00
Virtualization:                  VT-x
L1d cache:                       960 KiB
L1i cache:                       640 KiB
L2 cache:                        25 MiB
L3 cache:                        30 MiB
NUMA node0 CPU(s):               0-39
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single intel_ppin ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect wbnoinvd dtherm ida arat pln pts avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid fsrm md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] intel-extension-for-pytorch==2.0.110+gitb7412a4
[pip3] numpy==1.25.0
[pip3] torch==2.0.0a0+gite9ebda2
[pip3] torchaudio==2.0.2+31de77d
[pip3] torchvision==0.15.2a0+fa99a53
[conda] intel-extension-for-pytorch 2.0.110+gitb7412a4          pypi_0    pypi
[conda] mkl                       2023.1.0         h84fe81f_48680    conda-forge
[conda] mkl-include               2023.1.0         h84fe81f_48680    conda-forge
[conda] numpy                     1.25.0          py310ha4c1d20_0    conda-forge
[conda] torch                     2.0.0a0+gite9ebda2          pypi_0    pypi
[conda] torchaudio                2.0.2+31de77d            pypi_0    pypi
[conda] torchvision               0.15.2a0+fa99a53          pypi_0    pypi
```

Exemple of a test snippet with torch that works in this environment:

```python
import intel_extension_for_pytorch
import torch
data = torch.rand(500000, 10, dtype=torch.float32, device="xpu")
group_idx = torch.randint(0, 100, (500000,1), dtype=torch.int64, device="xpu")
groupby_sum = torch.zeros(100, 10, dtype=torch.float32, device="xpu")
groupby_sum.scatter_add(dim=0, index=group_idx.expand(-1, 10), src=data)
```

**Comment by chengjunlu** [comment]
All the packages looks good to me.

Could you please also share the script that failed in Triton?

**Comment by fcharras** [comment]
Here's the script (taken from [triton examples](https://triton-lang.org/main/getting-started/tutorials/01-vector-add.html) and replacing `cuda` with `xpu`):

```python
import triton
import triton.language as tl


@triton.jit
def add_kernel(
    x_ptr,  # *Pointer* to first input vector.
    y_ptr,  # *Pointer* to second input vector.
    output_ptr,  # *Pointer* to output vector.
    n_elements,  # Size of the vector.
    BLOCK_SIZE: tl.constexpr,  # Number of elements each program should process.
                 # NOTE: `constexpr` so it can be used as a shape value.
):
    # There are multiple 'programs' processing different data. We identify which program
    # we are here:
    pid = tl.program_id(axis=0)  # We use a 1D launch grid so axis is 0.
    # This program will process inputs that are offset from the initial data.
    # For instance, if you had a vector of length 256 and block_size of 64, the programs
    # would each access the elements [0:64, 64:128, 128:192, 192:256].
    # Note that offsets is a list of pointers:
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    # Create a mask to guard memory operations against out-of-bounds accesses.
    mask = offsets < n_elements
    # Load x and y from DRAM, masking out any extra elements in case the input is not a
    # multiple of the block size.
    x = tl.load(x_ptr + offsets, mask=mask)
    y = tl.load(y_ptr + offsets, mask=mask)
    output = x + y
    # Write x + y back to DRAM.
    tl.store(output_ptr + offsets, output, mask=mask)

def add(x: torch.Tensor, y: torch.Tensor):
    # We need to preallocate the output.
    output = torch.empty_like(x)
    n_elements = output.numel()
    # The SPMD launch grid denotes the number of kernel instances that run in parallel.
    # It is analogous to CUDA launch grids. It can be either Tuple[int], or Callable(metaparameters) -> Tuple[int].
    # In this case, we use a 1D grid where the size is the number of blocks:
    grid = lambda meta: (triton.cdiv(n_elements, meta['BLOCK_SIZE']),)
    # NOTE:
    #  - Each torch.tensor object is implicitly converted into a pointer to its first element.
    #  - `triton.jit`'ed functions can be indexed with a launch grid to obtain a callable GPU kernel.
    #  - Don't forget to pass meta-parameters as keywords arguments.
    add_kernel[grid](x, y, output, n_elements, BLOCK_SIZE=1024)
    # We return a handle to z but, since `torch.cuda.synchronize()` hasn't been called, the kernel is still
    # running asynchronously at this point.
    return output

size = 98432
x = torch.rand(size, device='xpu')
y = torch.rand(size, device='xpu')
output_torch = x + y
output_triton = add(x, y)
```

I also tried the matmul examples, it gives the same outcome.

**Comment by chengjunlu** [comment]
The `torch` and `intel_extension_for_pytorch` are required to be loaded before using the XPU device.
After add 
```Python
import torch
import intel_extension_for_pytorch
```
to your script, I can successfully run the example. Can you try it?

And for the error reported at first time, can you also try this and check what is the output?
```Python
Type "help", "copyright", "credits" or "license" for more information.
>>> import triton
>>> import triton.common.backend
>>> triton.common.backend.get_backend("xpu")
```

If the above not work, please also help to check this:
```Python
Type "help", "copyright", "credits" or "license" for more information.
>>> import triton
>>> import triton.third_party.xpu
```

**Comment by fcharras** [comment]
TY for the suggestions, the very last command `import triton.third_party.xpu` outputs a meaningful traceback, is seems that the import triggers `check_onednn_cfg` from `intel_extension_for_pytorch/xpu/cpp_extension.cpp` and I don't have onednn installed. Will report after fixing that.

**Comment by fcharras** [comment]
The same example give a new error during the kernel call, apparently there's an issue with lookup of device properties:

```
File ~/triton_compiler/triton/python/triton/third_party/xpu/__init__.py:409, in XPUBackend.get_architecture_descriptor(self, **kwargs)
    407 def get_architecture_descriptor(self, **kwargs):
    408     dev_props = torch.xpu.get_device_properties(torch.xpu.current_device())
--> 409     max_work_group_size = dev_props.max_work_group_size
    410     max_num_subgroup = dev_props.max_num_subgroup
    411     subgroup_sizes = dev_props.subgroup_sizes

AttributeError: 'intel_extension_for_pytorch._C._DeviceProperties' object has no attribute 'max_work_group_size'
```

The error persisted after I update to the latest commit of the master branch. I also tried with torch 1.3 and torch 2.0.

Here's the content of device props:

```
In [3]: torch.xpu.get_device_properties(torch.xpu.current_device())
Out[3]: _DeviceProperties(name='Intel(R) Graphics [0x56c0]', platform_name='Intel(R) Level-Zero', dev_type='gpu, support_fp64=0, total_memory=13535MB, max_compute_units=512)
```

I don't have the "max_work_group_size" property. `dpctl` correctly expose the attribute though.

This is on a Flex 170 GPU using the intel edge dev cloud.

**Comment by fcharras** [comment]
Most likely this is an issue with the intel extension for pytorch, not the xpu triton extension. I cross posted the issue at https://github.com/intel/intel-extension-for-pytorch/issues/385

**Comment by fcharras** [comment]
If I hardcode the `dev_props.*` values into the xpu extension code, it laters fails with:

```
File ~/triton_compiler/triton/python/triton/compiler/compiler.py:582, in CompiledKernel._init_handles(self)
    580     device = self.device_backend.get_current_device()
    581     bin_path = self.device_backend.get_kernel_bin()
--> 582     max_shared = self.device_backend.get_device_properties(device)["max_shared_mem"]
    583     fn_load_binary = self.device_backend.get_load_binary_fn()
    585 if self.shared > max_shared:

File ~/triton_compiler/triton/python/triton/third_party/xpu/__init__.py:389, in XPUBackend.get_device_properties(self, device)
    387 @functools.lru_cache(None)
    388 def get_device_properties(self, device):
--> 389     return self.driver.utils.get_device_properties(torch.xpu.device(device).to_sycl_dev())

AttributeError: 'device' object has no attribute 'to_sycl_dev'
```
which is harder to patch since it happens in a lot of files in triton.

Are you testing against an internal version of the intel extension for pytorch that is not synchronized with the github repo maybe ? or I would need to compile using another branch in the repo ?

**Comment by chengjunlu** [comment]
> If I hardcode the `dev_props.*` values into the xpu extension code, it laters fails with:
> 
> ```
> File ~/triton_compiler/triton/python/triton/compiler/compiler.py:582, in CompiledKernel._init_handles(self)
>     580     device = self.device_backend.get_current_device()
>     581     bin_path = self.device_backend.get_kernel_bin()
> --> 582     max_shared = self.device_backend.get_device_properties(device)["max_shared_mem"]
>     583     fn_load_binary = self.device_backend.get_load_binary_fn()
>     585 if self.shared > max_shared:
> 
> File ~/triton_compiler/triton/python/triton/third_party/xpu/__init__.py:389, in XPUBackend.get_device_properties(self, device)
>     387 @functools.lru_cache(None)
>     388 def get_device_properties(self, device):
> --> 389     return self.driver.utils.get_device_properties(torch.xpu.device(device).to_sycl_dev())
> 
> AttributeError: 'device' object has no attribute 'to_sycl_dev'
> ```
> 
> which is harder to patch since it happens in a lot of files in triton.
> 
> Are you testing against an internal version of the intel extension for pytorch that is not synchronized with the github repo maybe ? or I would need to compile using another branch in the repo ?

Yes. Actually we are using the internal version of the IPEX and intel_xpu_backend_for_triton.

Most issue you met is fixed in the latest intel_xpu_backend_for_triton. Like this:
https://github.com/intel/intel-xpu-backend-for-triton/commit/534bce3b82e147aeabf05f2b0c8a30f59184b0bb

I think you may need to pull the latest intel_xpu_backend_for_triton submodule in the triton/third_party.

**Comment by fcharras** [comment]
I have been using the compile bundle for the intel extension for pytorch, I think I'm fine on this end.

> I think you may need to pull the latest intel_xpu_backend_for_triton submodule in the triton/third_party.

I didn't realize that submodule states are pinned for a given commit of the parent module. Probably my setup is missing this step, ty for the suggestion, will try that.

**Comment by chengjunlu** [comment]
@fcharras Please let us know any issue or any question during your testing.

**Comment by fcharras** [comment]
Early feedback on running the tutorials on the flex 170 GPU:

- [vector addition](https://triton-lang.org/main/getting-started/tutorials/01-vector-add.html): runs fine out of the box. Performance is OK (about 30% slower than ipex).
- [matrix multiplication](https://triton-lang.org/main/getting-started/tutorials/03-matrix-multiplication.html): running the autotune feature requires replacing `cuda` with `xpu` everywhere in the module `triton.testing.py`, else the autotune needs to be bypassed to run the tutorial. In any case the resulting matmul is super slow (on 4096 * 4096 matmul, several seconds for triton VS 10 ms for ipex). float16 inputs (as intended in the tutorial) have significant numerical errors with the float16 ipex matmul counterpart. No numerical errors with float32 inputs.

I've heard there is ongoing work to make the matmul example work but is it expected to be that slow currently ?

**Comment by chengjunlu** [comment]
> Early feedback on running the tutorials on the flex 170 GPU:
> 
> * [vector addition](https://triton-lang.org/main/getting-started/tutorials/01-vector-add.html): runs fine out of the box. Performance is OK (about 30% slower than ipex).
> * [matrix multiplication](https://triton-lang.org/main/getting-started/tutorials/03-matrix-multiplication.html): running the autotune feature requires replacing `cuda` with `xpu` everywhere in the file `triton/testing.py`, else the autotune needs to be bypassed to run the tutorial. In any case the resulting matmul is super slow (on 4096 * 4096 matmul, several seconds for triton VS 10 ms for ipex). float16 inputs (as intended in the tutorial) have significant numerical errors with the float16 ipex matmul counterpart. No numerical errors with float32 inputs.
> 
> I've heard there is ongoing work to make the matmul example work but is it expected to be that slow currently (or maybe it's an install issue) ?

Thanks @fcharras for the information. Here is some clue we have for now. But we haven't fully focus on the performance yet.

vector addition:
1. The vectorized load/store are not 100% lowered correctly. And the memory bandwidth is not fully used for now.

matrix multiplication:
1. The tl.dot is lowered to FMA in Triton for now.
2. The number stage used by default is large than 1 in IPEX. That may cause the register pressures and spill which is the worst in performance. (There is no DMA engine in EU in Flex GPU. So the better use the num_stage=1 for now).

We will start performance tuning task with the elem-wise and reduce first. And then enable the Intel XMX in tl.dot.

**Comment by chengjunlu** [comment]
@fcharras 
I run the vectorize add on the A770. It shows the performance is close between IPEX and Triton. 
![image](https://github.com/intel/intel-xpu-backend-for-triton/assets/63445766/fcfb01e7-beaf-4513-984e-c8bc93f9a1a2)

Here is the A770 memory bandwidth.
```
 Global memory bandwidth (GBPS)
      float   : 399.67
      float2  : 405.23
      float4  : 408.76
      float8  : 419.72
      float16 : 422.77
```
I assume the performance gap is caused by some old code you are using.

**Comment by vlad-penkin** [comment]
@fcharras let us know if we can close this ticket. We greatly appreciate your feedback. 

If you want to revisit / review your findings please use llvm-target branch.

**Comment by fcharras** [comment]
I think you can close. I will definitely revisit, but the last time I tried I failed at compiling. So I thought I should be more patient and wait for binaries before revisiting, and was waiting for https://github.com/intel/intel-xpu-backend-for-triton/issues/275 to be adressed.
