### ISSUE TITLE
[CI] Update LTS driver to 803.103 in GHA runners

### ISSUE THREAD

**Issue by vlad-penkin** [intel/intel-xpu-backend-for-triton#2426]
https://dgpu-docs.intel.com/releases/LTS_803.103_20240925.html

**Comment by pbchekin** [comment]
Successful run: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/11185091262/job/31097227624

```
all: passed: 17047, failed: 0, skipped: 293, xfailed: 1296, total: 18636, fixme: 2, pass rate (w/o xfailed): 98.31%
```
