### ISSUE TITLE
[GEMM] Improve performance of shape 4096x8x128x16384

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#2434]
Currently Triton performance is ~86% of XeTLA on both default and advanced paths.

**Comment by ESI-SYD** [comment]
~90% of XeTLA with #2601 in CI now, WIP on more investigation and improvement.

**Comment by ESI-SYD** [comment]
Like https://github.com/intel/intel-xpu-backend-for-triton/issues/2442
Before:
![image](https://github.com/user-attachments/assets/deb137a1-216a-4a0a-a5bd-4bccfead7678)

![image](https://github.com/user-attachments/assets/d356f850-3f40-4134-a84b-7769e766d270)

After with https://github.com/intel/intel-xpu-backend-for-triton/pull/2646:
![image](https://github.com/user-attachments/assets/ceed836f-3fc3-4160-b9f8-4c3a489f711b)
