### ISSUE TITLE
[GEMM] Improve performance of shape 8192x16384x4096 on default path

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#2435]
Currently Triton performance is ~93% on default path, and ~99% on advanced path.
This issue is to investigate what is missing on default path from advanced path.

**Comment by ESI-SYD** [comment]
The latest data from dashboard shows ~96% on default path, and ~94% on advanced path.
![image](https://github.com/user-attachments/assets/507fa5b2-267d-4e61-8c9d-89d3c70f8919)

Will double check then.

**Comment by ESI-SYD** [comment]
Closing due to the gap comes from variance, not reproduced in x1 locally.

~98.8% on default path vs ~99.7% on advanced path in
[latest CI run](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/11949575978/job/33309296709)
