### ISSUE TITLE
Can triton xpu work with clang instead of DPC++ if SYCL runtime is available?

### ISSUE THREAD

**Issue by dvrogozh** [intel/intel-xpu-backend-for-triton#2441]
That's a follow up from https://github.com/pytorch/pytorch/issues/137518#issuecomment-2400877164.

I observe that XPU Triton can work (within pytorch) with clang given that SYCL runtime (headers + library) is available. Can you, please, clarify:
- [x] Is this a supported use case?
- [ ] If yes, which clang versions are supported? (I see that as of now only clang>=16 work, and with previous versions there is an error)
- [x] If yes, can clang-14 and clang-15 be supported? (clang-14 is default in ubuntu:22.04)

`clang-14` and `clang-15` fail with:
```
/usr/local/include/sycl/detail/defines_elementary.hpp:81:1: error: static assertion failed due to requirement '201402L >= 201703L': DPCPP does not support C++ version earlier than C++17.
```
I guess, explicit `-std=c++17` might be needed to make these compilers work.

CC: @vlad-penkin

**Comment by anmyachev** [comment]
Hi @dvrogozh!

> Is this a supported use case?

Yes

>  If yes, which clang versions are supported? (I see that as of now only clang>=16 work, and with previous versions there is an error)
>  If yes, can clang-14 and clang-15 be supported? (clang-14 is default in ubuntu:22.04)

I checked clang-14 compiler and it works on triton main branch. This version is starting to work because of this pull request: https://github.com/intel/intel-xpu-backend-for-triton/pull/1857/files (which also adds `-std=c++17` flag, so you're right).

Triton version you reported in https://github.com/pytorch/pytorch/issues/137518#issue-2574127748: `pytorch-triton-xpu 3.1.0+91b14bf559`, simply doesn't include the necessary changes yet.

**Comment by dvrogozh** [comment]
> Triton version you reported in https://github.com/pytorch/pytorch/issues/137518#issue-2574127748: pytorch-triton-xpu 3.1.0+91b14bf559, simply doesn't include the necessary changes yet.

Yep. That's expected since I tried this from PyTorch nightly build and there is a lag updating Triton on PyTorch side.

**Comment by dvrogozh** [comment]
`c++17` flag imposes requirement of GCC 8 or later (prev. versions, gcc 6 and gcc 7, had only experimental support). I am not sure which clang version started to officially supports `c++17` option. @anmyachev : are you checking clang versions earlier than clang 14 for support? I am fine if not - I believe information currently available in this issue is good enough for its closure. It's ok if you see some more work is needed here to keep it open.
