### ISSUE TITLE
[FA] Improve performance of shapes <95% on advanced path - 32x32x512, 4x32x4096, 2x32x8192

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#2442]
There are currently 3 shapes (causal=false, d_head=64) that have performance <95% of XeTLA.
- 32, 32, 512: 78%
- 4, 32, 4096: 82%
- 2, 32, 8192: 93%

**Comment by quintinwang5** [comment]
Huge **SBIDStalls** in Triton kernel.
![image](https://github.com/user-attachments/assets/9008b6f9-37bf-43bb-8a8b-03ab768152e0)
![image](https://github.com/user-attachments/assets/afde11c8-65e3-41e6-9c85-cc904cb22528)
Also more **DistStalls** in Triton kernel(the red line)
![image](https://github.com/user-attachments/assets/6352bad8-5b05-498c-af9e-633c26ba08e0)
![image](https://github.com/user-attachments/assets/85887574-e200-4500-8b86-2d8ad284581c)
WIP to investigate and finetune.

**Comment by quintinwang5** [comment]
Status: Did lots of finetunes and experiments. Most finetune configs are harmful to the performance. Modified llir by hand and execute it, there is also no big performance gains(ex. While dpas insts are atomic, we'll have more spills. It will offset the benefit from atomic dpas). The reason is higher SBIDStall and DistStall for load/sync insts than XETLA. This shows we are in short of registers. We may need helps from XETLA team or others.

**Comment by quintinwang5** [comment]
Cache hit of XETLA:
![image](https://github.com/user-attachments/assets/c6b63b20-d110-4436-ae2b-7e3fe96a784b)
Cache hit of Triton:
![image](https://github.com/user-attachments/assets/79bac639-8888-4212-a1c5-8ba102f41be7)
Triton with [PR](https://github.com/intel/intel-xpu-backend-for-triton/pull/2600):
![image](https://github.com/user-attachments/assets/34b1a937-f9e9-4804-827e-9bb1bf1c4847)

**Comment by quintinwang5** [comment]
Overall status:
![image](https://github.com/user-attachments/assets/7c8e0374-8689-462d-8106-98af609d8a00)

**Comment by quintinwang5** [comment]
According to the new overall status:

- **32, 32, 512 , 64, False: 78% --> 92.99%**
- 4, 32, 4096, 64, False: 82% --> 96.17% (not by this issue)
- 2, 32, 8192, 64, Flase: 93% --> 97.85 (not by this issue)

extra N_CTX=512 shapes:

- 32, 16, 512, 128, False: 66.41% --> 80.91%
- 32, 16, 512, 128, True: 60.10% --> 80.26%
- 32, 32, 512, 64, True:  65.91% --> 88.44%

Still need some works to bring 92.99%  up to 95%+.

**Comment by tdeng5** [comment]
What did we change to make the performance improvement?

**Comment by quintinwang5** [comment]
> What did we change to make the performance improvement?

I change the grid info (global_range in SYCL kernel submit). The main idea is to keep the splited-M axis align with the `num_warps * threads_per_warp` axis. For `32, 32, 512, 64, False` case, the range will change from `{{32, 32, 4}, {128, 1, 1}}` to `{{4, 32, 32}, {128, 1, 1}}`(in CUDA style), which 4 = N_CTX / BLOCK_M = 512 / 128. This change will benefit our L3 cache hit greatly(about 10x better) for N_CTX=512 cases, but is harmful to some other cases(especially causal=True, small batch cases observed). The detail mechnism is under investigation.
