### ISSUE TITLE
Stock PyTorch can‘t update triton commit pin due to triton version

### ISSUE THREAD

**Issue by guangyey** [intel/intel-xpu-backend-for-triton#2467]
The current triton version in main branch is [3.0.0](https://github.com/intel/intel-xpu-backend-for-triton/blob/58364a922202783b3c83defe883efdedd3ed11cf/python/triton/__init__.py#L2). But stock PyTorch needs triton version is [3.1.0](https://github.com/pytorch/pytorch/blob/ee713f80ed5ca6b64353f573ee699175b4b3b27e/.ci/docker/triton_version.txt#L1).
This blocks the reland of https://github.com/pytorch/pytorch/pull/135567. Please help take a look.

**Comment by riverliuintel** [comment]
@vlad-penkin @alexbaden we need the version update for PyTorch main branch Triton upgrade.

**Comment by guangyey** [comment]
Thanks @alexbaden
