### ISSUE TITLE
[operators/test_blocksparse.py::test_softmax] fails to run correctly on PVC

### ISSUE THREAD

**Issue by ESI-SYD** [intel/intel-xpu-backend-for-triton#255]

**Comment by ESI-SYD** [comment]
This case can pass on SPIRV path but fail on LLVM path.

**Comment by whitneywhtsang** [comment]
https://github.com/intel/intel-xpu-backend-for-triton/pull/370 fixes a subset of the `test_softmax` tests.

**Comment by vlad-penkin** [comment]
@whitneywhtsang can we close this issue?

**Comment by whitneywhtsang** [comment]
> @whitneywhtsang can we close this issue?

No, because only a subset of the test cases are passing.

**Comment by etiotto** [comment]
Verified that the LLVM IR produced by Triton is correct. The `tl.num_programs(0)` is correctly lowered to the OpenCL function `size_T get_global_size(unsigned int)`: 

```
  %50 = call i64 @_Z15get_global_sizej(i32 0), !dbg !30
  %51 = trunc i64 %50 to i32, !dbg !30
  %52 = call i32 (ptr addrspace(2), ...) @_Z18__spirv_ocl_printf(ptr addrspace(2) @printfFormat_1, i32 %8, i32 %10, i32 %12, ptr addrspace(2) @printfPrefix_1, i32 %51)
```
Note: 
```
% c++filt _Z15get_global_sizej
get_global_size(unsigned int)
```

I used  `export DISABLE_LLVM_OPT=1` to disable LLVM optimizations. So this looks like a potential IGC issue.
