### ISSUE TITLE
Investigate the new tensor descriptor API

### ISSUE THREAD

**Issue by mfrancepillois** [intel/intel-xpu-backend-for-triton#2586]
OpenAI has improved the way structured memory access is handled.

The PR : https://github.com/triton-lang/triton/pull/4916
 cleans-up, extends the triton dialect with new operations and improves the way TMA descriptors are handled by triton.

As significant changes result from this PR, we should investigate if and how these memory accesses using tensor descriptors could be transformed into block pointers.

**Comment by mfrancepillois** [comment]
The information needed to create a block pointer are:
- Base: pointer to parent tensor​
- Shapes: parent tensor shape​
- Strides: parent tensor strides​
- Block_shape​
- Offsets: block offsets​
- Order: block order

The new proposal for Tensor descriptor allows users to create a tensor descriptor on the device, which will be lowered into a TMA descriptor. This PR extends the Triton Dialect with a new operation `MakeTensorDescOp`.
This operation contains the following information:
- Base: pointer to parent tensor​
- Shapes: parent tensor shape​
- Strides: parent tensor strides​
- Block_shape​
Combining these pieces of information with the offsets included in the `experimental_descriptor_{load/store}` operations, could allow us to have all the required information to translate Tensor descriptor into block pointer.
​
A possible solution could be to add a pass to the front of the Intel pipeline that:​
1. Search for load/store Ops using a ptr created by a `MakeTensorDescOp` (at some point should be a specific type, see https://github.com/triton-lang/triton/blob/837308f780066a6606df4362a9648f9ce55c625b/include/triton/Dialect/Triton/IR/TritonOps.td#L961)​
2. Create a `MakeTensorPtrOp` just before the load/store with information collected from the `MakeTensorDescOp` + offsets from the load/store operation​
Notice that, in that case, the `MakeTensorPtrOp` cannot be moved (or must be moved with care => cannot be moved before the offset computation)​

Possible alternative: keep the `MakeTensorDescOp` as it is in the pipeline and implement only our XPU-specific lowering that should use 2D block operations.

**Comment by etiotto** [comment]
I think the new API looks promising. In the short term the proposed solution should allows us to materialize block pointers (i.e. make_tensor_ptr) operations and replace `experimental_descriptor_{load/store}` with `tt.load` operations on the create blocked pointer. 

Longer term I think block pointers will be sunset and we should therefore remove the pass above and make use of the new operations directly.
