### ISSUE TITLE
Pytorch does not compile with 2025 compiler

### ISSUE THREAD

**Issue by ZzEeKkAa** [intel/intel-xpu-backend-for-triton#2594]
If you try to build pytorch using deep-learning-essentials or any 2025 compiler - it will fail due to https://github.com/intel/torch-xpu-ops/issues/1027 .

As a workaround I've created torch-xpu-ops fork, that contains fixes that works only with 2025 compiler based on the pined commit of pytorch (https://github.com/intel/intel-xpu-backend-for-triton/blob/main/.github/pins/pytorch-upstream.txt) -> pinned commit of torch-xpu-ops (https://github.com/pytorch/pytorch/blob/0efa590d435d2b4aefcbad9014dd5fa75dcf8405/third_party/xpu.txt): 
https://github.com/ZzEeKkAa/torch-xpu-ops/pull/1/files

And corresponding commit in pytorch: https://github.com/pytorch/pytorch/commit/0b3b4a7ab93d85a2073e14ce2dca3ed71522acde

**Comment by riverliuintel** [comment]
Got you. We will fix the torch-xpu-ops issue with priority.

**Comment by ZzEeKkAa** [comment]
Okay, I've created a tiny PR that fixes the issue: https://github.com/ZzEeKkAa/pytorch/pull/2
We need to add it as a patch

**Comment by riverliuintel** [comment]
PR is merged into torch-xpu-ops https://github.com/intel/torch-xpu-ops/pull/1017

**Comment by pbchekin** [comment]
Fixed with: #2689
Verified with: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/11801397565
