### ISSUE TITLE
Cannot build pytorch with IPEX using `compile-pytorch-ipex.sh` 

### ISSUE THREAD

**Issue by etiotto** [intel/intel-xpu-backend-for-triton#2651]
To reproduce: 
```
conda create --name triton-3.10 python=3.10   
conda activate triton-3.10
git clone https://github.com/intel/intel-xpu-backend-for-triton.git
cd /intel-xpu-backend-for-triton
./scripts/compile-triton.sh 
pip install matplotlib pandas tabulate
pip install wheel cmake  
./scripts/compile-pytorch-ipex.sh
```

This is the error:
```
....
Fetching submodule third_party/oneDNN
From https://github.com/oneapi-src/oneDNN
 * [new tag]             v3.4-rc    -> v3.4-rc
Fetching submodule third_party/xetla
fatal: remote error: upload-pack: not our ref 53a487515fa8d78a0df28b06d08c4049e26db194
fatal: remote error: upload-pack: not our ref 0debfce71cf3bc8b313aa2d6ad247f1a72adb6a0
fatal: remote error: upload-pack: not our ref ceaeb2556a40ed8f50fe0ab6e0d42f9cd9577786
Errors during submodule fetch:
        third_party/xetla
        third_party/oneDNN
        third_party/ideep
```

**Comment by etiotto** [comment]
@whitneywhtsang as discussed offline this is the error I got while trying to collect performance result for FlashAttention. Is this the error you got as well ?

**Comment by whitneywhtsang** [comment]
> @whitneywhtsang as discussed offline this is the error I got while trying to collect performance result for FlashAttention. Is this the error you got as well ?

Yes, I got the same error.

**Comment by anmyachev** [comment]
@whitneywhtsang  @etiotto my build was successful, but I manually removed `.scripts_cache/pytorch` folder before. There is a possibility that an attempt is being made to install the old PyTorch into the folder where the new one was previously installed. Could you try to manually delete the folder if it exists and restart the script?

**Comment by whitneywhtsang** [comment]
Still fail the same way with the latest code.
