### ISSUE TITLE
Evaluate deploying runner using IDC (Intel Developer Cloud) server for Triton project

### ISSUE THREAD

**Issue by tdeng5** [intel/intel-xpu-backend-for-triton#270]
For fixing no server resource issues, logs for this task:

WW50: expect to get IDC server in Q3'24; Need to check with Areg
WW47:
	1. We has tried the method and confirmed it works. (based on Teng’s IDC server, using other repo, not Triton, since we don’t have permission)
	2. We could enable CI on IDC server in a couple of days when the IDC server is ready. (depends on Triton token response)

**Comment by pbchekin** [comment]
Got machines from IDC, added runners to the repository with tag "max1550".
