### ISSUE TITLE
Initiate a pull request to Triton that enables dispatching from Triton frontend to XPU backend

### ISSUE THREAD

**Issue by LiyangLingIntel** [intel/intel-xpu-backend-for-triton#271]
The latest Triton refactoring removed the Intel Triton backend from the third-party, `llvm-target` branch is a fork of `openai/Triton` with in-tree modifications.
To upstream Intel XPU Triton backend to `openai/triton`, we need to extract and clean up these in-tree modifications and initiate a PR to Triton repo. The updated glue code should enable the dispatching from Triton frontend to XPU backend besides NV and AMD backends.

This task is related to https://github.com/intel/intel-xpu-backend-for-triton/issues/170.

**Comment by LiyangLingIntel** [comment]
There should be a mechanism that regularly updates intel-xpu-backend-for-triton as a third-party backend to OpenAI Triton repository.

**Comment by etiotto** [comment]
In order to upstream change to OpenAI we first need to have #170 complete. We also need to change the FE to use the SYCL RT.
