### ISSUE TITLE
Unable to run any triton example after installing nightly 20241113

### ISSUE THREAD

**Issue by jgtong** [intel/intel-xpu-backend-for-triton#2711]
Greetings:

I am having issues with running any tutorial after installing the [20241113 nightly wheel](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/11827387422) binaries. The issue I get is a runtime error that reports a missing `libmpicxx.so.12` file that cannot be found:

```
Traceback (most recent call last):
  File "/home/jaytong/intel-xpu-backend-for-triton/python/tutorials/./01-vector-add.py", line 21, in <module>
    import torch
  File "/home/jaytong/pyenv/nightly-20241113/lib/python3.10/site-packages/torch/__init__.py", line 377, in <module>
    _load_global_deps()
  File "/home/jaytong/pyenv/nightly-20241113/lib/python3.10/site-packages/torch/__init__.py", line 333, in _load_global_deps
    raise err
  File "/home/jaytong/pyenv/nightly-20241113/lib/python3.10/site-packages/torch/__init__.py", line 311, in _load_global_deps
    ctypes.CDLL(global_deps_lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libmpicxx.so.12: cannot open shared object file: No such file or directory

```

System Config:

OS: Ubuntu 22.04.5
SDK: Using pytorch-gpu-dev kit 0.5.3 located here: https://www.intel.com/content/www/us/en/developer/articles/tool/pytorch-prerequisites-for-intel-gpu/2-5.html
Driver: Latest 2024-11-12 release (1032.19) https://dgpu-docs.intel.com/releases/rolling-release-notes.html#release-2024-11-12

I do not face this issue when using the [nightly wheels from the 20241112 build](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/11807287450). I am wondering what has changed?

**Comment by anmyachev** [comment]
Hi @jgtong,

we recently switched the Triton build to use the new toolchain (namely Intel® Deep Learning Essentials): https://github.com/intel/intel-xpu-backend-for-triton/pull/2708/files. I believe you also need to update it in your environment so that everything works.

**Comment by jgtong** [comment]
@anmyachev , thanks for your prompt response. I will give that a try

**Comment by jgtong** [comment]
@anmyachev , 

I installed the deep learning essentials  version 2025.0.0.345. I am getting an import error: `ImportError: libsycl.so.7: cannot open shared object file: No such file or directory` 

I checked my `/path/to/intel_deep_learning_ess/oneapi/compiler/2025.0/lib` directory and noticed that there's a `libsycl.so.8` but no `libsycl.so.7`

```
lrwxrwxrwx 1 jaytong jaytong   14 2024-10-17 14:38:32 libsycl.so -> ./libsycl.so.8
lrwxrwxrwx 1 jaytong jaytong   18 2024-10-17 14:38:34 libsycl.so.8 -> ./libsycl.so.8.0.0
-rwxr-xr-x 1 jaytong jaytong 4.1M 2024-10-08 12:05:24 libsycl.so.8.0.0
-rwxr-xr-x 1 jaytong jaytong  41K 2024-10-08 12:05:24 libsycl.so.8.0.0-gdb.py

```

Any advice?

**Comment by jgtong** [comment]
@anmyachev : nevermind, I got it to work. I had to remove the .triton in my home dir. Thanks for your time
