### ISSUE TITLE
[DPAS]: Improve the Triton GEMM/flash attention/sparse attention kernel performance to get 60% tensor core peak performance.

### ISSUE THREAD

**Issue by chengjunlu** [intel/intel-xpu-backend-for-triton#272]
As Phil's comments that the backend need to get 60% tensor core peak performance for flash attention and dense matmul, the Triton would package it as part of Triton 3.0 release.

**Comment by etiotto** [comment]
All right. I think the steps here are to get `tt.dot` to use the DPAS instruction on PVC GPUs correctly first. Then use 2D block loads for the operands and then analyze what the performance for these workloads is at that point.

**Comment by Dewei-Wang-sh** [comment]
related to issue #772 and #773

**Comment by vlad-penkin** [comment]
Linked issues:
- #772 
- #773

**Comment by vlad-penkin** [comment]
Closing this issue. The reminder will be tracked in
- #773
