### ISSUE TITLE
Support system Python in some workflows 

### ISSUE THREAD

**Issue by pbchekin** [intel/intel-xpu-backend-for-triton#2722]
The following workflows:

* Build and test
* Triton benchmarks

need to support using a system Python installed in the runner instead of installing one. This is required for runners that have, for example, Ubuntu 24.10, which is not supported by `actions/setup-python`. These runners will have a system Python that workflow should use.

**Comment by pbchekin** [comment]
I will take this to unblock @kwasd with client GPUs runs.

**Comment by anmyachev** [comment]
> This is required for runners that have, for example, Ubuntu 24.10, which is not supported by actions/setup-python

Just wondering what the error looks like when trying to use it on 24.10?

**Comment by pbchekin** [comment]
> > This is required for runners that have, for example, Ubuntu 24.10, which is not supported by actions/setup-python
> 
> Just wondering what the error looks like when trying to use it on 24.10?

```
Error: The version '3.10' with architecture 'x64' was not found for this operating system.
```
