### ISSUE TITLE
[CI] Add auto sending test report (UT and nightly) feature to the test scripts.

### ISSUE THREAD

**Issue by ESI-SYD** [intel/intel-xpu-backend-for-triton#273]
Add a general script to email CI report summary to stakeholders

**Comment by etiotto** [comment]
Please coordinate with @pbchekin on this idea. He is driving our CI process.

**Comment by pbchekin** [comment]
Where does this requirement come from?

**Comment by ESI-SYD** [comment]
> Where does this requirement come from?

It comes from offline discussion with SH team.

**Comment by vlad-penkin** [comment]
@ESI-SYD let's hold on implementation and discuss it internally first. In my opinion it's P3 and requirements should be clarified first.

**Comment by vlad-penkin** [comment]
This topic hasn't been brought up for a while, so I'm closing the ticket.
