### ISSUE TITLE
[GEMM] 2048x2048x2048 out of box performance degradation 

### ISSUE THREAD

**Issue by ESI-SYD** [intel/intel-xpu-backend-for-triton#2733]
### Describe the bug

Triton OOB performance of 2k only get ~210 [latest nightly run](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/11882989210/job/33109154713#step:15:809), with ~12% degradation from [248](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/11769279538/job/32780106259#step:15:809) or [242](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/11787592466/job/32833176790#step:15:809)

### Environment details

LIBIGC1_VERSION=1.0.17791.16-1032
LEVEL_ZERO_VERSION=1.17.44.0-1022
AGAMA_VERSION=1032
GPU_DEVICE=Intel(R) Data Center GPU Max 1550
TORCH_VERSION=2.1.0
COMPILER_VERSION=2024.1.4
BENCHMARKING_METHOD=PYTORCH_LEGACY_PROFILER_USING_IPEX

**Comment by quintinwang5** [comment]
@whitneywhtsang @ESI-SYD According to my local tests and benchmark CIs results, I think there is no regression for this case. This case has a big fluctuation. (As you can see, the min is about 80 TFLOPS and the max is up to 280TFLOPS. And XeTLA is similar). I ran several commits locally. With the same commit, the average varies from about 190TFLOPS to 246TFLOPS during multiple runs.(XeTLA is also the case with a slightly different data.) . We can also observe this case from many CI benchmarks. So we may need a research issue to investigate the reason.

**Comment by ESI-SYD** [comment]
Agree, I also noticed such variance in other case.

**Comment by quintinwang5** [comment]
Close this issue, and track the variance issue in [2873](https://github.com/intel/intel-xpu-backend-for-triton/issues/2873)
