### ISSUE TITLE
[GEMM] 16384x8192x4096 out of box performance degradation

### ISSUE THREAD

**Issue by ESI-SYD** [intel/intel-xpu-backend-for-triton#2734]
### Describe the bug

Triton OOB performance of 16384x8192x4096 only get ~247 [latest nightly run](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/11882989210/job/33109154713#step:15:809), with ~5% degradation from [262](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/11769279538/job/32780106259#step:15:809) or [262](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/11787592466/job/32833176790#step:15:809)

### Environment details

LIBIGC1_VERSION=1.0.17791.16-1032
LEVEL_ZERO_VERSION=1.17.44.0-1022
AGAMA_VERSION=1032
GPU_DEVICE=Intel(R) Data Center GPU Max 1550
TORCH_VERSION=2.1.0
COMPILER_VERSION=2024.1.4
BENCHMARKING_METHOD=PYTORCH_LEGACY_PROFILER_USING_IPEX

**Comment by quintinwang5** [comment]
Close due to the variane is less than 5% in recent CIs.
