### ISSUE TITLE
Add Triton backend sendmail feature for Triton community

### ISSUE THREAD

**Issue by ESI-SYD** [intel/intel-xpu-backend-for-triton#274]
This is a PR on the upstream `openai/triton`: https://github.com/openai/triton/pull/2629
which use non-anonymous email sending function to avoid being intercepted, like mail connection string: `smtp+starttls://user:password@server:port`. But we have an effort that requires maintaining account passwords.

Philippe recommended that we use intel machine and manage that.

Pending due to available IDC(Intel Developer Cloud) server as mail-sent runner. Related: #270

**Comment by vlad-penkin** [comment]
@pbchekin can we close this ticket?

**Comment by pbchekin** [comment]
> @pbchekin can we close this ticket?

Not sure if we need this, I would close as not planned.
