### ISSUE TITLE
AttributeError: module 'triton' has no attribute 'jit'

### ISSUE THREAD

**Issue by Yunaik** [intel/intel-xpu-backend-for-triton#2740]
### Describe the bug

Building triton from source using `scripts/compile-triton.sh` doesn't allow running [example 1 -- triton kernel](https://github.com/intel/intel-xpu-backend-for-triton?tab=readme-ov-file#example-1--triton-kernel) as the error `AttributeError: module 'triton' has no attribute 'jit'` is raised.

This issue was resolved in [issue #2099](https://github.com/triton-lang/triton/issues/2099) and [issue #1693](https://github.com/triton-lang/triton/issues/1693). A temporary solution was replacing `pip install -v -e '.[build,tests]'` with `python setup.py install` as suggested by the other issues

### Environment details

Latest triton version (just pulled from main), A770 GPU

**Comment by alexbaden** [comment]
It sounds like there was a build failure somewhere - do you have any log files from the build that you can share with us?

**Comment by Yunaik** [comment]
I just re-compiled with `  pip install -v -e '.[build,tests]'` and get `AttributeError: module 'triton' has no attribute 'jit'`

This is the build log:
[Uploading build.log…]()

**Comment by arunjose696** [comment]
A possible cause of this issue can be having a directory called triton being present in your current directory or one of the directories specified in PATH or PYTHON_PATH this would result in this directory being imported instead of installed triton.  I had faced this issue when I had cloned the [triton](https://github.com/triton-lang/triton) repo in my current directory where I executed my programs.

Could you share the  **output of below script** and the "**pip list**"

```
import triton
print(triton.__path__)
print(dir(triton))
```
The `triton.__path__ `should be ideally "`/PATH_TO_TRITON/intel-xpu-backend-for-triton/python/triton`" which should be same as the path mentioned in pip list.  
Remove or rename any conflicting local "triton" directories if they are present in your path, and python should then use the properly installed package instead.

**Comment by Yunaik** [comment]
Thank you for the advise. I checked and don't have `triton` in my current directory (the directory was directly `intel-xpu-backend-for-triton`, which I cloned from github). It still doesn't work unfortunately.

The output of the script shared by you:
```
Python 3.10.15 | packaged by conda-forge | (main, Oct 16 2024, 01:24:24) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import triton
>>> print(triton.__path__)
['/nfs/site/home/yuankai/code/intel-xpu-backend-for-triton/python/triton']
>>> print(dir(triton))
['CompilationError', 'Config', 'InterpreterError', 'JITFunction', 'KernelInterface', 'MockTensor', 'OutOfResources', 'TensorWrapper', 'TritonError', '_C', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_utils', 'autotune', 'backends', 'cdiv', 'compile', 'compiler', 'errors', 'heuristics', 'jit', 'language', 'next_power_of_2', 'reinterpret', 'runtime', 'set_allocator', 'testing', 'tools']
```

The output of `pip list`:
```
WARNING: Ignoring invalid distribution -orch (/nfs/site/home/yunaik/miniforge3/envs/triton_a770/lib/python3.10/site-packages)
Package                  Version            Editable project location
------------------------ ------------------ ---------------------------------------------------------------
accelerate               1.1.1
aiohappyeyeballs         2.4.3
aiohttp                  3.11.7
aiosignal                1.3.1
Arpeggio                 2.0.2
astunparse               1.6.3
async-timeout            5.0.1
attrs                    24.2.0
autopep8                 2.3.1
bitsandbytes             0.44.1
caliper-reader           0.4.1
causal_conv1d            0.1                /nfs/site/home/yunaik/code/mamba/extern/causal_conv1d_module
certifi                  2024.8.30
charset-normalizer       3.4.0
cmake                    3.31.0.1
contourpy                1.2.1
cycler                   0.12.1
datasets                 3.1.0
debugpy                  1.8.8
dill                     0.3.8
einops                   0.8.0
exceptiongroup           1.2.2
expecttest               0.2.1
filelock                 3.16.1
flake8                   7.1.1
fonttools                4.53.0
frozenlist               1.5.0
fsspec                   2024.10.0
huggingface-hub          0.26.2
hypothesis               6.119.3
idna                     3.10
iniconfig                2.0.0
isort                    5.13.2
Jinja2                   3.1.4
kiwisolver               1.4.5
lintrunner               0.12.5
lit                      18.1.8
llnl-hatchet             2024.1.3
mamba_ssm                0.0.1              /nfs/site/home/yunaik/code/mamba/python
MarkupSafe               3.0.2
matplotlib               3.9.0
mccabe                   0.7.0
mpmath                   1.3.0
multidict                6.1.0
multiprocess             0.70.16
networkx                 3.4.2
ninja                    1.11.1.1
numpy                    1.26.4
nvidia-cublas-cu12       12.4.5.8
nvidia-cuda-cupti-cu12   12.4.127
nvidia-cuda-nvrtc-cu12   12.4.127
nvidia-cuda-runtime-cu12 12.4.127
nvidia-cudnn-cu12        9.1.0.70
nvidia-cufft-cu12        11.2.1.3
nvidia-curand-cu12       10.3.5.147
nvidia-cusolver-cu12     11.6.1.9
nvidia-cusparse-cu12     12.3.1.170
nvidia-nccl-cu12         2.21.5
nvidia-nvjitlink-cu12    12.4.127
nvidia-nvtx-cu12         12.4.127
optree                   0.13.1
packaging                24.2
pandas                   2.2.3
pillow                   11.0.0
pip                      24.3.1
pluggy                   1.5.0
propcache                0.2.0
psutil                   6.1.0
pyarrow                  18.1.0
pybind11                 2.13.6
pycodestyle              2.12.1
pydot                    3.0.2
pyflakes                 3.2.0
pyparsing                3.2.0
pytest                   8.3.3
python-dateutil          2.9.0.post0
pytz                     2024.2
PyYAML                   6.0.2
regex                    2024.9.11
requests                 2.32.3
safetensors              0.4.5
scipy                    1.14.1
setuptools               72.1.0
six                      1.16.0
sortedcontainers         2.4.0
sympy                    1.13.1
textX                    4.1.0
tokenizers               0.20.3
tomli                    2.1.0
torch                    2.6.0a0+gitae7f809
tqdm                     4.67.0
transformers             4.47.0.dev0
triton                   3.2.0+gitc7eb08b7  /nfs/site/home/yunaik/code/intel-xpu-backend-for-triton/python
types-dataclasses        0.6.6
typing_extensions        4.12.2
tzdata                   2024.2
urllib3                  2.2.3
wheel                    0.45.0
xxhash                   3.5.0
yarl                     1.18.0
```

**Comment by Yunaik** [comment]
> A possible cause of this issue can be having a directory called triton being present in your current directory or one of the directories specified in PATH or PYTHON_PATH this would result in this directory being imported instead of installed triton. I had faced this issue when I had cloned the [triton](https://github.com/triton-lang/triton) repo in my current directory where I executed my programs.
> 
> Could you share the **output of below script** and the "**pip list**"
> 
> ```
> import triton
> print(triton.__path__)
> print(dir(triton))
> ```
> 
> The `triton.__path__ `should be ideally "`/PATH_TO_TRITON/intel-xpu-backend-for-triton/python/triton`" which should be same as the path mentioned in pip list. If it is not remove or rename any conflicting local "triton" directories if they are present in your path, and python should then use the properly installed package instead.

This was indeed the issue. When running the tutorial vector-add.py, it works without any issues.

In my project, I've a folder named `triton` and this caused the issue as described.

Thanks for your help!
