### ISSUE TITLE
Release of xpu backend binaries ?

### ISSUE THREAD

**Issue by fcharras** [intel/intel-xpu-backend-for-triton#275]
I am interested in trying to use the xpu backend for triton with its latest development features, and there's a 2.2.0 tag that has just been issued last week, I wonder if pre-built binaries are available to download somewhere yet ?

**Comment by vlad-penkin** [comment]
@fcharras we are planning to make a new binaries release by the end of the Q1. Right now new xpu backend version (llvm-target branch) is an active development with multiple changes being merged each day.

**Comment by fcharras** [comment]
I don't see a place where I could download binaries, do you mean that the workflow is ready and it will be available with 3.0 ?

**Comment by vlad-penkin** [comment]
@fcharras we are planning to start publishing nightly wheels be end of March. The target date for PyPI release is end of April.
