### ISSUE TITLE
[GEMM] Improve performance of shape 8192x16384x4096 out of box

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#2796]
### Describe the issue

Investigate what is missing from out of box performance to get to >95%.
It is currently at 91.21%.

### Environment details

PVC

**Comment by ESI-SYD** [comment]
Closing as goal has been met now. https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/12020443042/job/33509054011#step:16:822
