### ISSUE TITLE
Request Triton enable block pointer support on Intel GPU

### ISSUE THREAD

**Issue by riverliuintel** [intel/intel-xpu-backend-for-triton#281]
# Feature request 
PyTorch community is enabling Triton block pointer support, which will be enabled by default. 
PyTorch upstream Intel GPU backend for Inductor PR should be ready for review by the middle of Feb 2024.

https://github.com/pytorch/pytorch/pull/116079

https://github.com/pytorch/pytorch/pull/116079/files#diff-90b954bddfc0db29441328610022aa85c98d3e2647875f7982a6b42acdf2b183R543-R545

**Comment by Dewei-Wang-sh** [comment]
triton has a fallback pass - "triton-rewrite-tensor-pointer" which rewrite block pointer to pointer of tensors.
this pass is already included in llvm-target branch.

**Comment by etiotto** [comment]
We have blocked pointer working: 

![image](https://github.com/intel/intel-xpu-backend-for-triton/assets/56368199/ad0dad12-f8f7-4318-9eef-4bbf5e0f34ee)

**Comment by Jianhui-Li** [comment]
block pointer is mainly to support tl.dot/GEMM,  but GEMM is not required for pytorch intel GPU upstream.

**Comment by vlad-penkin** [comment]
@riverliuintel can we close this issue?
