### ISSUE TITLE
Flaky Triton build

### ISSUE THREAD

**Issue by pbchekin** [intel/intel-xpu-backend-for-triton#2817]
Sometimes build fails with the following error:

```
      /runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/include/triton/Dialect/TritonGPU/IR/Types.h:11:10: fatal error: triton/Dialect/TritonGPU/IR/TypeInterfaces.h.inc: No such file or directory
         11 | #include "triton/Dialect/TritonGPU/IR/TypeInterfaces.h.inc"
            |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      compilation terminated.
```

Example: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/12005805471/job/33463103804#step:9:560

Restarting usually helps.

**Comment by pbchekin** [comment]
CC: @whitneywhtsang, @anmyachev

**Comment by anmyachev** [comment]
I also began to observe this problem quite often.

**Comment by victor-eds** [comment]
Issue probably related to weak CMake dependencies. If we see https://github.com/intel/intel-xpu-backend-for-triton/blob/ba7a1c388f96367271c7932da2f2fe5e4c1cbeb9/lib/Dialect/Triton/IR/CMakeLists.txt:
```cmake
add_triton_library(TritonIR
  Dialect.cpp
  Ops.cpp
  Traits.cpp
  Types.cpp
  OpInterfaces.cpp

  DEPENDS
  TritonTableGen

  LINK_LIBS PUBLIC
  MLIRIR
  MLIRArithDialect
  MLIRMathDialect
  MLIRSCFDialect
)
```
We can see the dependency on `TritonTableGen`, but not on `TritonGPUTableGen`.
