### ISSUE TITLE
Remove `getElemsPerThreadForOperands` from `MmaEncodingTrait`

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#2823]
Goal: reduce changes in common files.

`getElemsPerThreadForOperands` is added in `MmaEncodingTrait` from https://github.com/intel/intel-xpu-backend-for-triton/commit/dcb220e74da05360478e9dff2184e5febfdc38b8. Since we now have better support of linear layout, please check if we can remove `getElemsPerThreadForOperands`.

**Comment by chengjunlu** [comment]
The changes were closed in an old PR to Triton https://github.com/triton-lang/triton/pull/4598.
We thought it should be not required when the LL is used. But the code is still required in LL conversion for slice layout. 
https://github.com/triton-lang/triton/blob/9c62d882abe213616b4bb42f66395de4eb903e6e/lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp#L744

I think we need to upstream the changes to the public Triton. I will re-open one new PR.

**Comment by chengjunlu** [comment]
Upstream PR is under reviewing.
https://github.com/triton-lang/triton/pull/5328
