### ISSUE TITLE
Reduce changes in common files for windows support

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#2824]
### Describe the bug

Goal: reduce changes in common files.

There are currently 6 common files modified for windows support:
[diff_windows.txt](https://github.com/user-attachments/files/17912277/diff_windows.txt)
This issue is to track upstreaming these changes if possible.

### Environment details

PVC

**Comment by anmyachev** [comment]
Perhaps one way to get rid of the [functions](https://github.com/intel/intel-xpu-backend-for-triton/blob/9161385f1d06df43cefc0ce8e2ae7a36b3816361/python/setup.py#L149) in `setup.py` for initializing `MSVC` compiler environment is to use cmake toolset feature like: `cmake -DCMAKE_TOOLCHAIN_FILE=msvc-toolchain.cmake`.

I found one project that provides what is needed for this (at first glance, I have not tested it yet) and under a suitable license
https://github.com/MarkSchofield/WindowsToolchain/blob/main/Windows.MSVC.toolchain.cmake

@gshimansky @pbchekin thoughts?

**Comment by anmyachev** [comment]
@pbchekin do we have machine with NVIDIA gpu to test related changes before upstreaming?

**Comment by anmyachev** [comment]
One more commit in upstream: https://github.com/triton-lang/triton/commit/a612088cbcc7ad475fff86d918f48e74cfd415ca

**Comment by anmyachev** [comment]
I think I did all I could, the last changes were rejected.

**Comment by etiotto** [comment]
For the record, the PR rejected upstream is: https://github.com/triton-lang/triton/pull/5372
