### ISSUE TITLE
Upstream changes for allocation

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#2825]
### Describe the bug

Goal: reduce changes in common files.

Upstream changes made in `lib/Analysis/Allocation.cpp` and `include/triton/Analysis/Allocation.h`: [diff_allocation.txt](https://github.com/user-attachments/files/17912327/diff_allocation.txt)

### Environment details

PVC

**Comment by victor-eds** [comment]
I think it should actually be the other way around: We should adhere to the content of those files. I'll do that.
