### ISSUE TITLE
Triton "do_bench" does not support XPU.

### ISSUE THREAD

**Issue by etaf** [intel/intel-xpu-backend-for-triton#284]
# Issue Description

Public Pytorch Inductor use [`do_bench` ](https://github.com/openai/triton/blob/5ddf524c64f2f9b3729ed189ab9d1e3826cd1e9e/python/triton/testing.py#L101)function from triton for kernel benchmark. But currently ` [`do_bench` ](https://github.com/openai/triton/blob/5ddf524c64f2f9b3729ed189ab9d1e3826cd1e9e/python/triton/testing.py#L101) only support CUDA. This blocked our Intel XPU Inductor backend upstream.

Please refer to the do_bench impl:
https://github.com/openai/triton/blob/5ddf524c64f2f9b3729ed189ab9d1e3826cd1e9e/python/triton/testing.py#L101
# Code Example

# System Info
- OS: Linux
- PyTorch: Public Pytorch release 2.1： a545ebf33472f165c20b85a0678a633c2cc3ab30
  
- Intel Extension For Pytorch: nternal master: 091e1e2ae2317fd63da6a0d58d6dd73f9ce76a58
  
- LLVM Version.
  
- Triton Version: release 2.1: https://github.com/intel/intel-xpu-backend-for-triton/releases/download/v2.1.0/triton-2.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  
- Intel® XPU Backend for Triton*:

**Comment by etiotto** [comment]
@etaf given this comment https://github.com/intel/intel-xpu-backend-for-triton/issues/284#issuecomment-1914144126 can this issue be closed ?

**Comment by etaf** [comment]
@etiotto @ESI-SYD Thanks for the work!  This feature request is for Intel XPU  Inductor backend upstream in Pytorch, It should check the device type and use the corresponding device interface. But the current implement onlyh support XPU( https://github.com/intel/intel-xpu-backend-for-triton/blob/llvm-target/python/triton/testing.py#L102), this will block CUDA path.

@EikanWang  do you have any opinion?

**Comment by EikanWang** [comment]
@etiotto , do_bench is not a dedicated API for XPU. It should support multiple devices. With current changes, does it imply that the code will not be upstreamed to Triton?

**Comment by etiotto** [comment]
I believe the OpenAI version of that file contains `torch.cuda.synchronize()` which is not going to work for all vendors. 
We should probably query whether we are 
```
if torch.cuda.available():
  torch.cuda.synchronize()
elif torch.xpu.available()
  torch.xpu.synchronize()
etc...
```

At the latest monthly interlock OpenAI told us that they are not going to accept Intel backend in the Triton repository. They intend to document the level of SW+HW performance a vendor needs to achieve for its BE to be accepted in tree. 

So currently we are going to exist as a fork of the upstream Triton code.

**Comment by EikanWang** [comment]
Make sense.

**Comment by whitneywhtsang** [comment]
https://github.com/intel/intel-xpu-backend-for-triton/pull/399 made the changes as described in https://github.com/intel/intel-xpu-backend-for-triton/issues/284#issuecomment-1917413962.
