### ISSUE TITLE
[Performance] Big performance gap (0.53x) with A100 due to persistant reduction efficiency issue

### ISSUE THREAD

**Issue by xytintel** [intel/intel-xpu-backend-for-triton#288]
test env: pytorch/release-2.1 (dpcpp 2024.0, cuda 12.3)
for a100: python cuda.py
```python
>>> 0.02581
```
for pvc: python xpu.py
```python
>>> 0.048400
```
There is a 0.53x performance gap
[reproducer.zip](https://github.com/intel/intel-xpu-backend-for-triton/files/13960920/reproducer.zip)

**Comment by LiyangLingIntel** [comment]
@xytintel Could you please help check if this is still a issue in the latest Triton 3.0 version? 
Since the path from path from Pytorch to Triton llvm-target is ready.

**Comment by LiyangLingIntel** [comment]
Tried to reproduce this data on my local machine
|kernel|llvm-target|spirv-target|speedup|
|--|:--:|:--:|:--:|
|reproducer|0.0518|0.0505|0.974x|

The perf is comparable between llvm-target and spirv-target for XPU, but the perf gap to A100 still exists.
