### ISSUE TITLE
[hf][accuracy] Inductor HF AMP(BF16) inference model DebertaV2ForQuestionAnswering accuracy check random failed

### ISSUE THREAD

**Issue by chuanqi129** [intel/intel-xpu-backend-for-triton#289]
It appeared in CI test https://github.com/intel/intel-xpu-backend-for-triton/pull/70 , and I also reproduce this random failure in local with low frequency (about 1/60). Not sure if this issue exist in current code base, need to root cause it.

**Comment by vlad-penkin** [comment]
@chuanqi129 could you please provide more details and link to the recent CI run for the llvm-branch?

**Comment by chuanqi129** [comment]
I remember it used @chengjunlu's fork LLVM at that time (Aug 8 2023). After that we introduced LLVM pre-built binary download for xpu backend. Hi @chengjunlu, could you please share the initial LLVM version which can work on that time?

**Comment by chengjunlu** [comment]
> I remember it used @chengjunlu's fork LLVM at that time (Aug 8 2023). After that we introduced LLVM pre-built binary download for xpu backend. Hi @chengjunlu, could you please share the initial LLVM version which can work on that time?

I cannot recall that LLVM version.

**Comment by aregm** [comment]
Please recheck.

**Comment by vlad-penkin** [comment]
Closing the issue, triton xpu project have switched to the llvm-target branch, spirv branch is no longer supported. If the accuracy failure reappear a new issue needs to be filed.
