### ISSUE TITLE
Resolve Token Permission security issues found by openSSF Scanning

### ISSUE THREAD

**Issue by lucyli-ca** [intel/intel-xpu-backend-for-triton#300]
# Issue Description
Resolve items in the 'Token Permissions' category as per reported from https://securityscorecards.dev/viewer/?uri=github.com/intel/intel-xpu-backend-for-triton

How to resolve: https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions

Time line requested: by Q1 2024

After resolving, the link to the scorecard should show a score of '10'

**Comment by pbchekin** [comment]
@ESI-SYD assigning this to you, since the report contains the following files:
```
Warn: no topLevel permission defined: .github/workflows/triton_xpu_backend_ci.yml:1
Warn: no topLevel permission defined: .github/workflows/triton_xpu_backend_e2e_ci.yml:1
Warn: no topLevel permission defined: .github/workflows/triton_xpu_backend_e2e_nightly.yml:1
Warn: no topLevel permission defined: .github/workflows/triton_xpu_backend_nightly.yml:1
```

**Comment by vlad-penkin** [comment]
@ESI-SYD [OpenSSF report](https://securityscorecards.dev/viewer/?uri=github.com/intel/intel-xpu-backend-for-triton) still indicate four issues with the token permissions:

_Warn: no topLevel permission defined: .github/workflows/triton_xpu_backend_ci.yml:1
Warn: no topLevel permission defined: .github/workflows/triton_xpu_backend_e2e_ci.yml:1
Warn: no topLevel permission defined: .github/workflows/triton_xpu_backend_e2e_nightly.yml:1
Warn: no topLevel permission defined: .github/workflows/triton_xpu_backend_nightly.yml:1
Info: no jobLevel write permissions found_

**Comment by pbchekin** [comment]
> @ESI-SYD [OpenSSF report](https://securityscorecards.dev/viewer/?uri=github.com/intel/intel-xpu-backend-for-triton) still indicate four issues with the token permissions:
> 
> _Warn: no topLevel permission defined: .github/workflows/triton_xpu_backend_ci.yml:1 Warn: no topLevel permission defined: .github/workflows/triton_xpu_backend_e2e_ci.yml:1 Warn: no topLevel permission defined: .github/workflows/triton_xpu_backend_e2e_nightly.yml:1 Warn: no topLevel permission defined: .github/workflows/triton_xpu_backend_nightly.yml:1 Info: no jobLevel write permissions found_

The latest scorecard report is generated at  2024-01-15. I think we need to wait for a new report.

**Comment by pbchekin** [comment]
Revisiting after making llvm-target the default branch.

**Comment by pbchekin** [comment]
Several issues, such as token permissions, are reported against upstream files. Going to fix what we can in this repository and will file an issue for the upstream repository.

**Comment by vlad-penkin** [comment]
This issue can be closed after we'll get an updated clean report from openSSF.

**Comment by pbchekin** [comment]
> This issue can be closed after we'll get an updated clean report from openSSF.

Yes, it wasn't me who closed it, I've just mentioned in PR which was closed. Any suggestion how to keep issues open even if linked PRs get closed?

**Comment by lucyli-ca** [comment]
> > @ESI-SYD [OpenSSF report](https://securityscorecards.dev/viewer/?uri=github.com/intel/intel-xpu-backend-for-triton) still indicate four issues with the token permissions:
> > _Warn: no topLevel permission defined: .github/workflows/triton_xpu_backend_ci.yml:1 Warn: no topLevel permission defined: .github/workflows/triton_xpu_backend_e2e_ci.yml:1 Warn: no topLevel permission defined: .github/workflows/triton_xpu_backend_e2e_nightly.yml:1 Warn: no topLevel permission defined: .github/workflows/triton_xpu_backend_nightly.yml:1 Info: no jobLevel write permissions found_
> 
> The latest scorecard report is generated at 2024-01-15. I think we need to wait for a new report.

Just got some additional information on scan results. These are suppose to be run weekly.  In the meantme, – You can solve this/get refreshed results and control accuracy of information by adding the github action to repo directly.
- These instructions are now available https://wiki.ith.intel.com/display/SecTools/OpenSSF+Scorecard+Checks#OpenSSFScorecardChecks-EnableCheckswithinRepo) to give you pointers to source information, I was told that it should take 10 min or so, (beyond getting pull request reviewed and requested) and then all findings are in Code Quality tab.
-	It also runs weekly and sends data.  So you could also run upon demand after making changes. An example setup is: https://github.com/fido-device-onboard/epid-verification-service/blob/master/.github/workflows/scorecard.yml
- I suggest trying the above, of course we can wait for corporate scan to be fixed… but having the abilities to do our own definitely would help with validating etc as there is a roadmap of items in 2024.

**Comment by pbchekin** [comment]
Yeah, we can run the scanner with GitHub actions or with CLI. I did the latter and will re-run shortly and update this issue when I'll have updates.

**Comment by pbchekin** [comment]
The latest [report](https://securityscorecards.dev/viewer/?uri=github.com/intel/intel-xpu-backend-for-triton) has 10 for "Token-Permissions".
