### ISSUE TITLE
Proton support on XPU

### ISSUE THREAD

**Issue by mgrabban** [intel/intel-xpu-backend-for-triton#3025]
Hello,

Do you have plans to support proton (profiler for triton) on XPU? If yes, when can we expect it?
I do see PR #2635. Maybe you just need to merge it to main to provide with initial support?

Thanks,
Golam

**Comment by vlad-penkin** [comment]
@mgrabban this feature is tracked in the issue
- #1145

The PR is in a draft status and not ready to be merged. We are planning to finalize the work during the first couple of iterations after New Year's.

**Comment by vlad-penkin** [comment]
Closing this issue as duplicate.
