### ISSUE TITLE
IPEX changes the return type of the API `sycl_queue` and `sycl_device`. Triton XPU backend need to align these changes.

### ISSUE THREAD

**Issue by chengjunlu** [intel/intel-xpu-backend-for-triton#305]
The IPEX changes the `sycl_queue` return type at commit.
https://github.com/intel-innersource/frameworks.ai.pytorch.ipex-gpu/commit/6182b5eba7b46230fe2631677dc8aba13703389e

Changes the `sycl_device` return type at commit.
https://github.com/intel-innersource/frameworks.ai.pytorch.ipex-gpu/commit/f65c45e75fa52209dc174a6b56e87e107c702371

Both returns the capsule of the sycl::queue and sycl::device pointer refer to the corresponding object inside IPEX internally.

The capsule names are `torch.xpu.Stream.sycl_queue` and `torch.xpu.device.sycl_device`. 

The Triton XPU backend runtime need to align the new API in IPEX to support torch DL complier use cases.

**Comment by quintinwang5** [comment]
@chengjunlu we already use `PyCapsule_GetPointer(cap, PyCapsule_GetName(cap))`, not hardcode name. https://github.com/intel/intel-xpu-backend-for-triton/blob/5a0d78f36a3a941fcbb92a195774b61a574677ed/third_party/intel/backend/driver.c#L185

**Comment by chengjunlu** [comment]
The merged PR.
https://github.com/intel/intel-xpu-backend-for-triton/pull/239

**Comment by quintinwang5** [comment]
Fixed by https://github.com/intel/intel-xpu-backend-for-triton/pull/239
