### ISSUE TITLE
PyTorch pinned Triton version does not compatible with Intel XPU backend Triton version.

### ISSUE THREAD

**Issue by tdeng5** [intel/intel-xpu-backend-for-triton#309]
LLVM-path based on the latest Triton code(after Triton refactor), while PyTorch (master branch) is using Triton CI: e28a256d71f3cf2bcc7b69d6bda73a9b855e385e ([ci_commit_pins/triton.txt](https://github.com/pytorch/pytorch/blob/main/.ci/docker/ci_commit_pins/triton.txt)) which before Triton refactor(Wed Dec 13 08:21:52 2023).

These two versions incompatible, to make E2E run, we must backport Triton API to match PyTorch’s version, or PyTorch upgrade Triton to the latest version.

**Comment by etiotto** [comment]
Backporting the `llvm-target` branch to Dec 13 isn't something we have in plan. Do we know when the PyTorch community has in plan to move up to the latest Triton ?

**Comment by alexbaden** [comment]
Pytorch has updated to latest Triton API: https://github.com/pytorch/pytorch/pull/117873 
Triton usptream + Pytorch upstream are currently compatible. 
We do not have an Intel XPU backend compatible with the latest pytorch yet, but there are two projects in progress to get there.

**Comment by vlad-penkin** [comment]
This issue have been resolved.
