### ISSUE TITLE
[test_subprocess]: `test_assert` with arg "device_assert", "assert", "no_debug", "double_assert" fails to run correctly

### ISSUE THREAD

**Issue by etiotto** [intel/intel-xpu-backend-for-triton#311]

**Comment by etiotto** [comment]
This work item is blocked. The IGC compiler has a problem described in https://github.com/intel/intel-xpu-backend-for-triton/issues/256#issuecomment-1907085632

**Comment by quintinwang5** [comment]
Blocked by https://github.com/intel/intel-xpu-backend-for-triton/issues/358 now. Need IGC version newer or equal than 1.0.15136.*

**Comment by whitneywhtsang** [comment]
Verified can be fixed by https://github.com/intel/intel-xpu-backend-for-triton/issues/358.
