### ISSUE TITLE
[test_subprocess]:  `test_assert_nested` fails to run correctly

### ISSUE THREAD

**Issue by etiotto** [intel/intel-xpu-backend-for-triton#312]
The end-to-end test `test_assert_nested` fails to run run correctly on a PVC GPU.

**Comment by etiotto** [comment]
This work item is blocked. The IGC compiler has a problem described in https://github.com/intel/intel-xpu-backend-for-triton/issues/256#issuecomment-1907085632 which needs to be resolved in order to unblock this work item.

**Comment by whitneywhtsang** [comment]
Verified can be fixed by https://github.com/intel/intel-xpu-backend-for-triton/issues/358.
