### ISSUE TITLE
[Backend] Summarize the required math functions and report it to DPC++ team

### ISSUE THREAD

**Issue by chengjunlu** [intel/intel-xpu-backend-for-triton#320]
The Triton uses the NV math functions in the libdevice.
Need to summarize the used math functions in Triton.
And provide a list DPC++ team as request if any missed math functions used in Triton but not supported on Intel GPU yet.

**Comment by kurapov-peter** [comment]
Is this the same as #240?

**Comment by vlad-penkin** [comment]
Duplicates:
- #240
