### ISSUE TITLE
Collect  e2e models performance, figure out the gaps on LLVM path.

### ISSUE THREAD

**Issue by tdeng5** [intel/intel-xpu-backend-for-triton#332]
For example, we collected inference perf gaps in SPIRV path.

Inductor HF 3 models AMP(BF16) inference performance with low speedup

name                                                | batch_size | speedup | abs_latency | compilation_latency
MobileBertForQuestionAnswering   | 128           | 0.6755    | 81.7692       | 23.0122
MobileBertForMaskedLM                 | 64             | 0.7024    | 88.9173       | 199.3977
YituTechConvBert                             | 16              | 0.992     | 79.9991        | 273.1471

**Comment by vlad-penkin** [comment]
This is an umbrella ticket to track the performance degradations.

The list currently known issues:
- #545

**Comment by vlad-penkin** [comment]
LLVM backend have reached performance parity with SPIRV a month ago. Closing this ticket.
