### ISSUE TITLE
Poor performance for tutorial tests 05 and 08

### ISSUE THREAD

**Issue by prathams417** [intel/intel-xpu-backend-for-triton#339]
```
assert torch.allclose(dw_tri, dw_ref, atol=1e-2, rtol=0)
AssertionError

```
Tests are stopped by these assertions that are verifying the results within a certain tolerance. If the tolerance is loosened the tests can complete.

To reproduce:

```
python3 -m pip install matplotlib pandas tabulate -q
python3 python/tutorials/<test-name>
```

**Comment by vlad-penkin** [comment]
@prathams417 could you please split this issue into the two, one which related to assertion error and another related to the poor performance.

**Comment by etiotto** [comment]
@prathams417 I noticed the upstream version of the 05 tutorial uses ` atol=1e-2` for checking `dw_tri` and our downstream version now uses `atol=2e-2`. Can you post a PR to add a FIXME to that like so that we remember to go back and investigate more ?

**Comment by etiotto** [comment]
Renamed this issue to track the performance issues.

**Comment by anmyachev** [comment]
According to the results in CI, the issue is no longer actual.
