### ISSUE TITLE
Tutorial 06 does not complete

### ISSUE THREAD

**Issue by prathams417** [intel/intel-xpu-backend-for-triton#340]
Currently when running the test, it just hangs, nothing is displayed in the output and the program does not complete.

To reproduce:
```
python3 -m pip install matplotlib pandas tabulate -q
python3 python/tutorials/06-fused-attention.py
```

**Comment by etiotto** [comment]
Fixed by https://github.com/intel/intel-xpu-backend-for-triton/pull/350.
