### ISSUE TITLE
Khronos translator / dependency on downgraded libigc1

### ISSUE THREAD

**Issue by pbchekin** [intel/intel-xpu-backend-for-triton#358]
We currently need to downgrade libigc1 from `1.0.15136.24-775~22.04` (which comes with L0 from Agama 775) to `1.0.14828.26-736~22.04`. The potential root cause is the new libigc1 uses Khronos translator by default on Linux (still disabled for Windows). Our code needs to work with the released L0 without downgrades.

**Comment by quintinwang5** [comment]
I can update libigc once https://github.com/intel/llvm/pull/12514#issuecomment-1913883757 is merged.

**Comment by whitneywhtsang** [comment]
Verified `test_assert`, `test_assert_nested`, and `test_scan2d_broadcast` all pass with `libigc1=1.0.15136.24-775~22.04`.

**Comment by whitneywhtsang** [comment]
Verified no regressions with `libigc1=1.0.15136.24-775~22.04`.

**Comment by pbchekin** [comment]
To use a runner with `libigc1=1.0.15136.24-775~22.04` change label `runner-0.0.4` in https://github.com/intel/intel-xpu-backend-for-triton/blob/llvm-target/.github/workflows/build_and_test.yml#L78 to `runner-0.0.5`.

**Comment by pbchekin** [comment]
Fixed by #383, #384
