### ISSUE TITLE
Port and Run tests in the regression directory

### ISSUE THREAD

**Issue by etiotto** [intel/intel-xpu-backend-for-triton#377]
We need to investigate whether we can run the tests in the `regression` directory:

![image](https://github.com/intel/intel-xpu-backend-for-triton/assets/56368199/0083ed80-bc23-4e52-b083-b703975f7e42)

**Comment by ienkovich** [comment]
All tests except `test_performance.py` were enabled in CI for XPU. `test_performance.py` runs elemwise add, sum, matmul, and attention (forward + backward) ops and checks GPU utilization matches reference values. We should get back to it after performance tracking mechanisms are defined for Triton on XPU.

@etiotto
I'm closing this one as done, we can get no more functional testing from here. We can open a new one for perf testing if needed.

**Comment by etiotto** [comment]
Thanks @ienkovich I opened #398 to track adding the remaining test.

**Comment by whitneywhtsang** [comment]
FYI https://github.com/openai/triton/commit/9b8a2c9abbaf884a5236a3df4a4b2e3b07846fa7
OpenAI no longer runs regression tests in their CI.
