### ISSUE TITLE
Upstream GEN dialect

### ISSUE THREAD

**Issue by vlad-penkin** [intel/intel-xpu-backend-for-triton#386]
This is an umbrella ticket to track GEN dialect upstreaming.

**Comment by etiotto** [comment]
First step is to publish an RFC and get consensus from the LLVM/MLIR community.

**Comment by etiotto** [comment]
The RFC is live: https://discourse.llvm.org/t/rfc-add-gen-dialect-for-intel-gpus/76753

**Comment by etiotto** [comment]
The RFC for upstreaming the GEN dialect to MLIR is currently under discussion. We should consider this work blocked until we have reached agreement with the community on this RFC.

**Comment by vlad-penkin** [comment]
This ticket is not current
