### ISSUE TITLE
Investigate lowering of `GENX_FpToFpOp` without GenISA

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#387]

**Comment by whitneywhtsang** [comment]
```

**Comment by etiotto** [comment]
There is this code:

```
tatic Value convertFp32ToFp16(Location loc,
                                 ConversionPatternRewriter &rewriter,
                                 const Value &v, const RoundingMode rounding,
                                 const Target &target) {
    switch (target) {
    case mlir::triton::NVVM: {
      PTXBuilder builder;
      StringRef ptx;
      switch (rounding) {
      case RoundingMode::RTNE:
        ptx = "cvt.rn.f16.f32";
        break;
      case RoundingMode::RTZ:
        ptx = "cvt.rz.f16.f32";
        break;
      default:
        llvm::errs() << "WARNING: unsupported rounding mode for f32->f16 "
                        "conversion: "
                     << stringifyRoundingMode(rounding) << "\n";
        llvm_unreachable("");
      }
```

Which we aren't lowering correctly now because we fail to use the same rounding mode as NVIDIA.  To port this code faithfully we will need to set the rounding mode, which is not possible via `llvm::FPTruncOp`.

**Comment by whitneywhtsang** [comment]
> Which we aren't lowering correctly now because we fail to use the same rounding mode as NVIDIA.

Fixed in https://github.com/intel/intel-xpu-backend-for-triton/pull/397.

**Comment by whitneywhtsang** [comment]
Next experiment is to use https://llvm.org/docs/LangRef.html#constrained-floating-point-intrinsics.

**Comment by whitneywhtsang** [comment]
> Next experiment is to use https://llvm.org/docs/LangRef.html#constrained-floating-point-intrinsics.

Created https://github.com/intel/llvm/pull/12588 to use https://llvm.org/docs/LangRef.html#constrained-floating-point-intrinsics.

**Comment by whitneywhtsang** [comment]
The PR is merged, we can no longer generating GenISA for fp to fp conversion.
