### ISSUE TITLE
Add an option to use large register mode on PVC

### ISSUE THREAD

**Issue by pengtu** [intel/intel-xpu-backend-for-triton#388]
https://www.intel.com/content/www/us/en/docs/oneapi/optimization-guide-gpu/2024-0/small-register-mode-vs-large-register-mode.html

The large register mode doubles the number of registers to 256 with half of the threads, 4 vs 8.  It reduces register spills at the expense of less threads per EU.

This feature needs to be supported by the launcher.

**Comment by pengtu** [comment]
To enable the large register mode, we just need to pass an option to Level 0 during module load: 
https://spec.oneapi.io/level-zero/latest/core/PROG.html#module-build-options

**Comment by etiotto** [comment]
Just providing an env. variable to enable large GRF mode shifts the burden on the user.  Ideally the Triton compiler could attempt to compile a kernel using the default GRF mode (small GRF), if IGC reports high register pressure associated with spilling the compiler could resubmit the IR to IGC requestion large GRF mode. 

The first question is whether there is a way to get the register pressure and spilling info in a report (at compilation time).

**Comment by Dewei-Wang-sh** [comment]
in the assembly, we can see whether there is reg spill.
I've also seen some targets convey this info by kernel metadata.
for now, we can use "export IGC_VISAOptions=" -TotalGRFNum 256" to enable it.
later on, we can try below two ways
1) get the kernel's reg usage by an analysis pass, and then enable large grf in triton.
the analysis has to be conservative
2) re-compile if IGC report reg spill

**Comment by etiotto** [comment]
This is done. Currently we resubmit the SPV code to IGC if the number of spills exceeds a threshold. This is done automatically unless the user explicitly sets the GRF mode in an autotuning configuration.
