### ISSUE TITLE
Segment fault happens if the kernel prints a lot of information (>4000 lines) with the SYCL runtime lancuher.

### ISSUE THREAD

**Issue by chengjunlu** [intel/intel-xpu-backend-for-triton#401]
Segment fault happens if the kernel prints a lot of information (>4000 lines) with the SYCL runtime launcher.

While with the L0 runtime, the kernel prints works well for <10000 lines. But it will cause the GPU watch dog time out if more information need to be print.

The segment fault is not only happened in the Triton language but also happened in SYCL language.

So it looks like the common issue in the SYCL runtime.

**Comment by vlad-penkin** [comment]
@chengjunlu what is the current status of this issue?

**Comment by chengjunlu** [comment]
> @chengjunlu what is the current status of this issue?

There is no segment fault issue. The print information is not truncated by the runtime if it is over size.
