### ISSUE TITLE
The LLVM optimization option O3 on Triton side cause some GEMM test case fail.

### ISSUE THREAD

**Issue by chengjunlu** [intel/intel-xpu-backend-for-triton#403]
The LLVM optimization option O3 on Triton side cause some GEMM test case fail because of the in-correct result.
Some part of the output results are set to 0 instead the expected value while the other part are correct.

The test case is `test_op|[16-16-16-1-1-2-None-None-None-False-False-float16-float16-True-True-None-None|]` of `test_matmul.py`

If the LLVM optimization option O0 is used, the issue doesn't happen.

**Comment by etiotto** [comment]
@chengjunlu this is likely caused by the InstCombine pass in LLVM. I discovered this for a different variation of the workload: https://github.com/intel/intel-xpu-backend-for-triton/issues/381#issuecomment-1919271813.

**Comment by etiotto** [comment]
Same as #381, blocked by a problem in the IGC compiler.

**Comment by vlad-penkin** [comment]
This issue duplicates 
- #381

**Comment by etiotto** [comment]
I'd like to keep this open until we can verify that the -O3 IGC problem is fixed.

**Comment by chengjunlu** [comment]
I cannot reproduce this issue with the latest Triton on XPU.

Not sure which changes fixed this issue. But I think we can close this issue for now since it is not reproduced.

**Comment by chengjunlu** [comment]
Reopen the issue. I just found I didn't enable the DPAS correctly in previous test.

**Comment by chengjunlu** [comment]
Has double confirm the test case passed on the latest Triton with the DPAS instruction. This issue cannot be reproduced.
Let's close this issue.
