### ISSUE TITLE
[#2 gemm block-pointer] verify end2end test with tritongpu loweirng to llvm/spirv 

### ISSUE THREAD

**Issue by Dewei-Wang-sh** [intel/intel-xpu-backend-for-triton#408]
to enable end2end running from a python triton kernel, we have to lowering tritongpu to llvm/spirv, and then launching- the kernel.
tt.prefetch => prefetch2d(load2d without result)
tt.load => load2d
tt.dot => dpas

**Comment by Dewei-Wang-sh** [comment]
add pass - tritongpu lowering to spirv with vc-intrinsics, 
verified a few 8x16x1024, 16x32x1024 gemm examples.
https://github.com/intel/intel-xpu-backend-for-triton/compare/main...gemm_simd

**Comment by Dewei-Wang-sh** [comment]
fix running bugs
https://github.com/intel/intel-xpu-backend-for-triton/commit/428a7a26eab0d8b593ab98127d5d4e56e051de6a

**Comment by Dewei-Wang-sh** [comment]
next step is to port to tritongpu-to-llvm

**Comment by etiotto** [comment]
I am helping @Dewei-Wang-sh with the productization of this code.
