### ISSUE TITLE
Doc for building LLVM Target

### ISSUE THREAD

**Issue by Stonepia** [intel/intel-xpu-backend-for-triton#409]
Hello, Could you help to provide a doc for building the LLVM target?

I notice that you have offered a [compile-triton.sh](https://github.com/intel/intel-xpu-backend-for-triton/blob/llvm-target/scripts/compile-triton.sh), but could you write a formal doc describing that? About how to build the triton, and how to run a basic kernel for checking.

In addition, I have two thoughts about this file:

1. What is the recommended `BASE` env setting? From the script, the default setting is `BASE=/iusers/$USER` , and it should be the parent folder of the triton folder. Normally, there is no `iusers` folder, so I would suggest that this `iuser` be changed to something like `$HOME/...`. 
2. The `cmake` is hardcoded to `/usr/bin/cmake`, but there are cases when the user wants to use `cmake` in conda env, especially when the user doesn't have root permission to install cmake in the system path.

**Comment by etiotto** [comment]
> 1. What is the recommended BASE env setting? From the script, the default setting is BASE=/iusers/$USER , and it should be the parent folder of the triton folder. Normally, there is no iusers folder, so I would suggest that this iuser be changed to something like $HOME/....
The cmake is hardcoded to /usr/bin/cmake, but there are cases when the 
> 2. The cmake is hardcoded to /usr/bin/cmake, but there are cases when the user wants to use cmake in conda env, especially when the user doesn't have root permission to install cmake in the system path.

Correct it is the parent of the project folder. We can change the script to use $HOME (or ../../) and also avoid hardcoding the location of the cmake executable.

**Comment by whitneywhtsang** [comment]
Hi @Stonepia , thanks for your suggestions, PRs are created to address them. 

> how to run a basic kernel for checking

For checking, we use test-triton.sh. It takes option to run different kind of tests, e.g., `-lit`, `-core`, `-tutorial`, etc.

@chsasank kindly offered to help in documenting the build process.  (https://github.com/intel/intel-xpu-backend-for-triton/issues/335#issuecomment-1912474408)
Can we track that effect in https://github.com/intel/intel-xpu-backend-for-triton/issues/327?

If you have any questions on building or testing in the meantime, we are happy to help.

**Comment by whitneywhtsang** [comment]
Issue was closed automatically when the PRs were merged in. Reopening to give @Stonepia a chance to response.

**Comment by Stonepia** [comment]
thanks for the help! Issue could be closed.
