### ISSUE TITLE
Add e2e tests to CI 

### ISSUE THREAD

**Issue by vlad-penkin** [intel/intel-xpu-backend-for-triton#419]
E2E tests should run on each PR.

Let's base it on spirv branch job: 
- GHA worfklow - https://github.com/intel/intel-xpu-backend-for-triton/blob/spirv-target/.github/workflows/triton_xpu_backend_e2e_ci.yml
- Job run - https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/6336749054/workflow

Instruction on how to run E2E is here - https://github.com/intel/intel-xpu-backend-for-triton/wiki/End-to-End-Test

PyTorch/IPEX 2.1 with Triton 3.0 API support:

- IPEX - https://github.com/intel/intel-extension-for-pytorch/tree/dev/triton-test-3.0
- PyTorch - https://github.com/Stonepia/pytorch/tree/dev/triton-test-3.0

**Comment by pbchekin** [comment]
Done, but instead of running e2e tests for each PR we will be running them daily or by a manual trigger, the total duration of the workflow is more than 30h. Will file additional issues for fixes/improvements.
