### ISSUE TITLE
 Unknown CMake command "mlir_tablegen"

### ISSUE THREAD

**Issue by jinz2014** [intel/intel-xpu-backend-for-triton#42]
Could you please add doc on building and running examples ?  Thanks.

1 clone the repo
2 mkdir build & cd build
3 cmake ..

-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at include/triton/Conversion/TritonGPUToSPIRV/CMakeLists.txt:2 (mlir_tablegen):
  Unknown CMake command "mlir_tablegen".

**Comment by Stonepia** [comment]
Hello @jinz2014 ,
We are having a PR at https://github.com/intel/intel-xpu-backend-for-triton/pull/36, you could refer to that first.
