### ISSUE TITLE
Automate SPIRV-LLVM-Translator version update

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#447]
Find the last commit that can pass all Triton tests in https://github.com/KhronosGroup/SPIRV-LLVM-Translator, then create a PR with the updated commit in lib/Target/SPIRV/spirv-llvm-translator.conf, like how it is done in https://github.com/intel/intel-xpu-backend-for-triton/pull/445.

**Comment by vlad-penkin** [comment]
@whitneywhtsang and @pbchekin can we close this ticket?

**Comment by whitneywhtsang** [comment]
> @whitneywhtsang and @pbchekin can we close this ticket?

No, because it is not implemented.

**Comment by pbchekin** [comment]
@AshburnLee could you please take a look to this?

**Comment by AshburnLee** [comment]
> [@AshburnLee](https://github.com/AshburnLee) could you please take a look to this?

Of course. And @whitneywhtsang which branch in the Translator repo should we search for the commit from? main or others

**Comment by AshburnLee** [comment]
Have discussed with Pavel, we want to do it in an automate way even the creating PR step, so we agree on split this issue into 2:
1. Find the target commit in the Translator repo,
2. Create PR automatically.
Because in the 2nd step, we are not clear on how to detect if the PR is already created from the previous run.

**Comment by whitneywhtsang** [comment]
> > [@AshburnLee](https://github.com/AshburnLee) could you please take a look to this?
> 
> Of course. And @whitneywhtsang which branch in the Translator repo should we search for the commit from? main or others

main branch is good.

**Comment by AshburnLee** [comment]
This one is tracked by
https://github.com/intel/intel-xpu-backend-for-triton/issues/1672 &
https://github.com/intel/intel-xpu-backend-for-triton/issues/1673
