### ISSUE TITLE
Confirm that new LTS Driver does not require libigc1 downgrade

### ISSUE THREAD

**Issue by vlad-penkin** [intel/intel-xpu-backend-for-triton#450]
This issue was fixed in the latest driver we use
- #358

We need to confirm it too with the new LTS Driver which was released on the 01/01/24 - https://dgpu-docs.intel.com/releases/LTS_803.29_20240131.html

**Comment by vlad-penkin** [comment]
@whitneywhtsang can we close this issue?

**Comment by whitneywhtsang** [comment]
> @whitneywhtsang can we close this issue?

Yes, the assertion UT are passing on LTS.
