### ISSUE TITLE
[Benchmark] tutorial report-out seems not correct

### ISSUE THREAD

**Issue by Jianhui-Li** [intel/intel-xpu-backend-for-triton#470]
The performance report shows too high matmul performance (in TFlops). The TFlops keep growing even when the problem sizes are already very big, which seems indicate the time being measured deosn't grow when the problem size grow.  

The root cause seems that we are measuring the host time using  datetime, not the kernel.  It is likely the host doesnt' wait for the device kernel complete so we measure the host drive time, which is more or less constant comparing to kernel time,  so we got very high artificial TFlops when problem becomes bigger.   https://github.com/intel/intel-xpu-backend-for-triton/blob/llvm-target/python/triton/testing.py#L148 

**  Below is an excerpts from CI report on the tutorial test. These are from the two matmul tutorial test cases.  
 Note that the cuBLAS perfomance is really the torch default performance using onDNN  

https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/7834541571/job/21377998423

matmul-performance:
      M     N     K  TRANS_A  TRANS_B       cuBLAS      Triton
0  2048   512   512    False     True    51.177268    8.263486
1  2048  1024  1024    False    False   178.360381   34.643074
2  2048  2048  2048     True    False   637.677823  122.546929
3  2048  4096  4096     True     True  2853.766101  558.586000
matmul-performance:
        M       N       K       cuBLAS       Triton
0  2048.0   512.0   512.0    42.891425     7.942856
1  2048.0  1024.0  1024.0   159.419456    32.283868
2  2048.0  2048.0  2048.0   571.885667   144.403996
3  2048.0  4096.0  4096.0  2745.051201   558.586000
4  2048.0  8192.0  8192.0  9450.176267  2033.371260

https://github.com/intel/intel-xpu-backend-for-triton/blob/llvm-target/python/tutorials/09-experimental-tma-matrix-multiplication.py
https://github.com/intel/intel-xpu-backend-for-triton/blob/llvm-target/python/tutorials/10-experimental-tma-store-matrix-multiplication.py

**Comment by etiotto** [comment]
The use of `datetime`  in https://github.com/intel/intel-xpu-backend-for-triton/blob/llvm-target/python/triton/testing.py#L148 was introduced by https://github.com/intel/intel-xpu-backend-for-triton/pull/363/files#r1467799172

**Comment by jinz2014** [comment]
@etiotto  Is it right that we need to move the end_time after synchronize() ? 

```
        start_times[i] = datetime.now()
        fn()
        //end_times[i] = datetime.now()
    # Record clocks
    if torch.cuda.is_available():
        torch.cuda.synchronize()
    elif torch.xpu.is_available():
        torch.xpu.synchronize()
    end_times[i] = datetime.now()  
```

**Comment by etiotto** [comment]
> @etiotto Is it right that we need to move the end_time after synchronize() ?
> 
> ```
>         start_times[i] = datetime.now()
>         fn()
>         //end_times[i] = datetime.now()
>     # Record clocks
>     if torch.cuda.is_available():
>         torch.cuda.synchronize()
>     elif torch.xpu.is_available():
>         torch.xpu.synchronize()
>     end_times[i] = datetime.now()  
> ```

@jinz2014 let me give that a try to see what effect that would have on the performance numbers computed.
