### ISSUE TITLE
[ci][reporting] Show UT pass rate in CI

### ISSUE THREAD

**Issue by vlad-penkin** [intel/intel-xpu-backend-for-triton#471]
Parse pytest reports for all tests suites except tutorial and show pass rate for all tests in the last step of the CI workflow.

**Comment by etiotto** [comment]
I wonder why we do not want to report the pass rate **including** also the tutorials. In a strict sense they aren't part of the Triton unit tests but they provide valuable insights as well. 

Can show somewhere the tutorial status. Maybe a separate report.

**Comment by pbchekin** [comment]
> I wonder why we do not want to report the pass rate **including** also the tutorials. In a strict sense they aren't part of the Triton unit tests but they provide valuable insights as well.
> 
> Can show somewhere the tutorial status. Maybe a separate report.

Yes, we can do a separate report.

**Comment by pbchekin** [comment]
> I wonder why we do not want to report the pass rate **including** also the tutorials. In a strict sense they aren't part of the Triton unit tests but they provide valuable insights as well.
> 
> Can show somewhere the tutorial status. Maybe a separate report.

Filed #483.
