### ISSUE TITLE
Collect UT warnings (with FIXME) and do not account these tests as passed

### ISSUE THREAD

**Issue by pbchekin** [intel/intel-xpu-backend-for-triton#482]
Some tests have been modified (reduced scope, increased tolerance, etc) and currently they are passing, but they generate warnings, which can be parsed. Such test should not be accounted as passed in the pass rate dashboard. It is reasonable to keep these modified tests with warnings in CI (instead skipping them completely) to avoid regressions.

**Comment by pbchekin** [comment]
Related to #471.

**Comment by vlad-penkin** [comment]
@pbchekin can we close this ticket?
