### ISSUE TITLE
Report pass rate for tutorials

### ISSUE THREAD

**Issue by pbchekin** [intel/intel-xpu-backend-for-triton#483]
> I wonder why we do not want to report the pass rate including also the tutorials. In a strict sense they aren't part of the Triton unit tests but they provide valuable insights as well. Can show somewhere the tutorial status. Maybe a separate report.

**Comment by wutthichai46** [comment]
> > ฉันสงสัยว่าทำไมเราไม่ต้องการรายงานอัตราการผ่านรวมถึงบทช่วยสอนด้วย ในแง่ที่เข้มงวด สิ่งเหล่านี้ไม่ได้เป็นส่วนหนึ่งของการทดสอบหน่วยของ Triton แต่ให้ข้อมูลเชิงลึกที่มีคุณค่าเช่นกัน สามารถแสดงสถานะการฝึกสอนที่ไหนสักแห่งได้ อาจจะเป็นรายงานแยกต่างหาก

**Comment by pbchekin** [comment]
Currently we run all existing tutorials meaning that pass rate is 100%. Any failure with tutorials will be reported as a workflow failure and needs to be fixed. Do we need anything else here?
