### ISSUE TITLE
[timm][accuracy][float32][inference] deit_base_distilled_patch16_224, jx_nest_base, pit_b_224, twins_pcpvt_base, vit_base_patch16_224, xcit_large_24_p8_224

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#485]
The following models pass with v2.1, but fail_accuracy with v3.0:
`deit_base_distilled_patch16_224`, `jx_nest_base`, `pit_b_224`, `twins_pcpvt_base`, `vit_base_patch16_224`, `xcit_large_24_p8_224`
Example command line: `bash inductor_xpu_test.sh timm_models float32 inference accuracy xpu 0 static 1 0 xcit_large_24_p8_224`

v2.1 env:
```
intel-innersource/frameworks.ai.pytorch.private-gpu	pytorch-2.1	2f3017f60aa8b9363acb62c180b6d362c836b5d0
intel/intel-xpu-backend-for-triton/releases/download/v2.1.0_rc1/triton-2.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl		
intel-extension-for-pytorch	2.1.10+xpu	
torch	2.1.0a0+git59f7c41
torchvision	0.16.0a0+cxx11.abi	
timm                        0.8.22.dev0
```
v3.0 env:
```	
Stonepia/pytorch	dev/triton-test-3.0	0f6d72ce16bd4b30402dcad97144d17cd7bc53ed
intel/intel-xpu-backend-for-triton	b6d3678483dbffa58f0470a46c0b512f223aabda	
intel-extension-for-pytorch 2.1.10+git99b4297		
torch	2.1.0a0+git59f7c41	
torchvision	0.16.0a0+47cd5ea	
timm	0.8.22.dev0	
```

**Comment by whitneywhtsang** [comment]
To reproduce v2.1 env:
```
wget https://github.com/intel/intel-xpu-backend-for-triton/releases/download/v2.1.0_rc1/triton-2.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
pip install triton-2.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
python -m pip install torch==2.1.0a0 torchvision==0.16.0a0 torchaudio==2.1.0a0 intel-extension-for-pytorch==2.1.10+xpu --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/xpu/us/
pip install pandas scipy tqdm
```
```
triton                      2.1.0
intel-extension-for-pytorch 2.1.10+xpu
torch                       2.1.0a0+cxx11.abi
torchaudio                  2.1.0a0+cxx11.abi
torchvision                 0.16.0a0+cxx11.abi
timm                        0.9.15.dev0
```

**Comment by vlad-penkin** [comment]
No longer reproduceable.

Env:
- pytorch is built from source, top of the main trunk, commit_id - `9a8ab778d34bd24c5caceb340837483decc4c311`
- triton xpu is built from source, top of the main trunk, commit_id - `fe93a00ffe438e9ba8c8392c0b051b1662c810de`
- benchmark is built from source, top of the main trunk, commit_id - `d54ca9f80ead108c8797441681e219becaf963d8`
- torchaudio is built from source, top of the main trunk,  commit_id - `1980f8af5bcd0bb2ce51965cf79d8d4c25dad8a0`
- torchvision  is built from source, top of the main trunk,  commit_id - `10239873229e527f8b7e7b3340c40ee38bb1cfc4`
- PyTorch Dependency Bundle 0.5.0
- Latest Rolling Driver
