### ISSUE TITLE
Rocky Linux Compatibility

### ISSUE THREAD

**Issue by sjagtap1803** [intel/intel-xpu-backend-for-triton#486]
I am interested in installing triton on Rocky Linux 8.8 but the README says that it is compatible only with Ubuntu 22.04. Is installation possible on other Linux distributions?

Thanks!

**Comment by etiotto** [comment]
We have focused on Ubuntu but is worth to give it a try.

**Comment by sjagtap1803** [comment]
Ok. Which installation method would be the best for installation on a different Linux distribution? I see that it can be installed from source or built with a custom LLVM.

**Comment by etiotto** [comment]
The installation method is documented here: https://github.com/intel/intel-xpu-backend-for-triton/blob/spirv-target/docs/build_from_source.md

**Comment by pbchekin** [comment]
> Ok. Which installation method would be the best for installation on a different Linux distribution? I see that it can be installed from source or built with a custom LLVM.

We are working on conda environment that can be used to build and run Triton. Ideally it will be possible to use it with any Linux distribution where conda is supported.
