### ISSUE TITLE
[GEN]: Move GEN dialect in Triton

### ISSUE THREAD

**Issue by etiotto** [intel/intel-xpu-backend-for-triton#531]
The GEN dialect is currently an LLVM leaf dialect augmenting the LLVM dialect in a similar way as the NVVM/ROCDL dialects. 
The MLIR community isn't quite ready to accept this dialect in MLIR, therefore we need to make the GEN dialect a Triton dialect.
This entails changing the GEN dialect from a LLVM extension dialect to a generic MLIR dialect with conversion to the LLVM dialect.

**Comment by etiotto** [comment]
This is complete. Remaining issue will be tracked via #673.

**Comment by pbchekin** [comment]
> This is complete. Remaining issue will be tracked via #673.

Does it mean we are no longer need to use a custom llvm? If this is the case, then we need to make a corresponding changes to our build scripts and CI workflows.

**Comment by whitneywhtsang** [comment]
> > This is complete. Remaining issue will be tracked via #673.
> 
> Does it mean we are no longer need to use a custom llvm? If this is the case, then we need to make a corresponding changes to our build scripts and CI workflows.

We still need a custom llvm, due to the remaining issue tracked via #673.

**Comment by etiotto** [comment]
> > This is complete. Remaining issue will be tracked via #673.
> 
> Does it mean we are no longer need to use a custom llvm? If this is the case, then we need to make a corresponding changes to our build scripts and CI workflows.

Not yet. We can remove the dependency once #673 is complete.
