### ISSUE TITLE
Create LLVM IR for dot (SIMD pass)

### ISSUE THREAD

**Issue by etiotto** [intel/intel-xpu-backend-for-triton#533]
Create a LLVMIR file that uses XeGPU for lowering a dot operation in SIMD mode.  Get an estimate of initial performance and compare it to the SIMT path. 

One could use compiler to generate the LLVM IR file, but not implement the analysis portion and hard code the transformation portion as needed.

**Comment by Jianhui-Li** [comment]
The team is actively working on it.   @Garra1980 to sync on the schedule.

**Comment by Dewei-Wang-sh** [comment]
```bash
        Kernel test_kernel : 243 registers
the kernel execution time is (ms, on L0 runtime):avg: 0.5678, min: 0.4691, max: 0.8896 (over 100 runs)
        Kernel test_kernel : 243 registers
the kernel execution time is (ms, on L0 runtime):avg: 0.5684, min: 0.4685, max: 1.2571 (over 100 runs)
        Kernel test_kernel : 243 registers
the kernel execution time is (ms, on L0 runtime):avg: 0.5776, min: 0.4690, max: 1.0789 (over 100 runs)
        Kernel test_kernel : 243 registers
the kernel execution time is (ms, on L0 runtime):avg: 0.5773, min: 0.4682, max: 1.5646 (over 100 runs)
        Kernel test_kernel : 243 registers
the kernel execution time is (ms, on L0 runtime):avg: 0.5729, min: 0.4685, max: 1.1934 (over 100 runs

>>> 2*4096**3/0.4690/1e9
293.046809108742 TFlops
```
for the GEMM 4Kx4Kx4Kxfp16, the generated spirv runs on GPU Max1550 is ~290TFlops which is on par with current showed result ( MLIR team 300TFlops, XeTLA 317 TFlops)
the methodology is as below:
1. handwritten tritongpu code with prefetch added
2.  go through pass "tritongpu-distribute-to-warps"
3.  go through pass "tritongpu-match-target-size"
4. go through pass "convert-tritongpu-to-spirv{vc-enabled}
5.  replace the spv binary in IMEX repo, and do profiling.
[gemm4k.spirv.mlir.log](https://github.com/intel/intel-xpu-backend-for-triton/files/14402656/gemm4k.spirv.mlir.log)

**Comment by etiotto** [comment]
> ```shell
>         Kernel test_kernel : 243 registers
> the kernel execution time is (ms, on L0 runtime):avg: 0.5678, min: 0.4691, max: 0.8896 (over 100 runs)
>         Kernel test_kernel : 243 registers
> the kernel execution time is (ms, on L0 runtime):avg: 0.5684, min: 0.4685, max: 1.2571 (over 100 runs)
>         Kernel test_kernel : 243 registers
> the kernel execution time is (ms, on L0 runtime):avg: 0.5776, min: 0.4690, max: 1.0789 (over 100 runs)
>         Kernel test_kernel : 243 registers
> the kernel execution time is (ms, on L0 runtime):avg: 0.5773, min: 0.4682, max: 1.5646 (over 100 runs)
>         Kernel test_kernel : 243 registers
> the kernel execution time is (ms, on L0 runtime):avg: 0.5729, min: 0.4685, max: 1.1934 (over 100 runs
> 
> >>> 2*4096**3/0.4690/1e9
> 293.046809108742 TFlops
> ```
> 
> for the GEMM 4Kx4Kx4Kxfp16, the generated spirv runs on GPU Max1550 is ~290TFlops which is on par with current showed result ( MLIR team 300TFlops, XeTLA 317 TFlops) the methodology is as below:
> 
> 1. handwritten tritongpu code with prefetch added
> 2. go through pass "tritongpu-distribute-to-warps"
> 3. go through pass "tritongpu-match-target-size"
> 4. go through pass "convert-tritongpu-to-spirv{vc-enabled}
> 5. replace the spv binary in IMEX repo test, so that same host configuration with MLIR team, and do profiling.
> 
> the generated spv binary is attached [gemm4k.spirv.mlir.log](https://github.com/intel/intel-xpu-backend-for-triton/files/14402656/gemm4k.spirv.mlir.log)

Note that we aren't using the L0 runtime (we use the SPIRV runtime) for the `llvm-target` branch so it would be best to use it to launch the SPV binary.  From the log " the kernel execution time is (ms, on L0 runtime):" are you using the L0 runtime in this experiment?

**Comment by Dewei-Wang-sh** [comment]
yes, using the same L0 runtime to have a comparison with MLIR team and XeTLA.
```bash
        Kernel test_kernel : 243 registers
the kernel execution time is (ms):avg: 0.5665, min: 0.4683, max: 0.9704 (over 100 runs)
        Kernel test_kernel : 243 registers
the kernel execution time is (ms):avg: 0.5709, min: 0.4682, max: 1.0629 (over 100 runs)
```
this is running with sycl-runtime, the perf seems do not change
