### ISSUE TITLE
[performance] suggested GEMM tile sizes for workgroup/subgroup and prefetch distance

### ISSUE THREAD

**Issue by Jianhui-Li** [intel/intel-xpu-backend-for-triton#536]
The following tile size parameters can be used to set the triton.autotune's config for bf16/fp16 GEMM for PVC: 
       BLOCK_SIZE_M <- wgm
       BLOCK_SIZE_N <- wgn
       BLOCK_SIZE_K <- sgk
       warp size <- Thread  #
       num_stages <- prefetch distance

sgm, sgn, and sgk can be used to set triton's subgroup level tile size when assigning the block layout.   The sgk size for int8 and tf32 will need adjust to make sure the byte size are same as bf16/fp16.

wgm | wgn | sgk | sgm | sgn | prefetch distance | register usage | thread# | row_thrd# (wgm/sgm) | col_thrd (wgn/sgn)
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
256 | 256 | 32 | 32 | 64 | 3 | 224 | 32 | 8 | 4
128 | 256 | 32 | 16 | 64 | 3 | 176 | 32 | 8 | 4
256 | 128 | 32 | 32 | 32 | 3 | 128 | 32 | 8 | 4
512 | 128 | 32 | 64 | 32 | 3 | 192 | 32 | 8 | 4
128 | 512 | 32 | 32 | 64 | 3 | 224 | 32 | 4 | 8
128 | 128 | 32 | 16 | 32 | 3 | 96 | 32 | 8 | 4
  |   |   |   |   |   |   |   |   |  
64 | 128 | 32 | 16 | 32 | 3 | 96 | 16 | 4 | 4
128 | 64 | 32 | 32 | 16 | 3 | 80 | 16 | 4 | 4
128 | 128 | 16 | 32 | 32 | 3 | 80 | 16 | 4 | 4
  |   |   |   |   |   |   |   |   |  
32 | 64 | 32 | 16 | 16 | 3 | 56 | 8 | 2 | 4
64 | 32 | 32 | 16 | 16 | 3 | 56 | 8 | 4 | 2
32 | 32 | 32 | 16 | 16 | 3 | 56 | 4 | 2 | 2
16 | 64 | 32 | 8 | 16 | 3 | 44 | 8 | 2 | 4
8 | 64 | 32 | 8 | 16 | 3 | 44 | 4 | 1 | 4
16 | 32 | 16 | 8 | 16 | 3 | 24 | 4 | 2 | 2

 
Rational: 
1. The peak performance achieved from 4Kx4K GEMM uses the following configure. At the subgroup level, it is 32x32x64 (sgm x k_step x sgn).  This is the size you can drive the DPAS fully busy, and uses 224 registers (with the large register file 256 limit) to hide mem latency.  At workgroup level, the size is 256 x 32 x 256 (wgm x k_step x wgn) for each k step, which maps to 8 x 4 subgroup threads and the max threads a Xecore can support with the large register file mode.   

wgm | wgn | sgk | sgm | sgn | prefetch distance | register usage | thread# | row_thrd# (wgm/sgm) | col_thrd (wgn/sgn)
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
256 | 256 | 32 | 32 | 64 | 3 | 224 | 32 | 8 | 4

register usage = bf16 matrix A size + bf16 matrix B size + fp32 matrix C size = sgm * sgk /32 + sgk * sgn /32 + sgm * sgn /16

2. The next 4 lines tweaks the size of wgm and wgn, so to fit better the problem size, but keep the same threads number for high utilization and good register usage for subgroup efficiency.

3. The next batch of 3 lines reduces the threads # to 16, and also reduce the register usage to 80. The size is reduced to fit smaller matrix.  Since the threads # is half of maximum limit, there is chance that two workgroups can be scheduled to one a same Xecore. These configure also reduces registers sizes, which also implies the cache size being used, so that two set of workgroups could be executed to the same Xecore without resource conflict (like SLM/cache).

4. The last batch of  6 lines are really for very small matrix. The rational is similar to 3 but just to scale further down the workgroup size, subgroup thread numbers, and register usage.    
 
5. For GEMM involves a transpose of input matrix, say those in the backward, it may make sense to tune the sgk to 16, so that the over register usage won't surpass the large register file limit (256 on PVC).

**Comment by tdeng5** [comment]
This issue has split to several issues to track. Just close it.
1. Prefetch: [[performance] cooperative prefetch strategy for GEMM #542](https://github.com/intel/intel-xpu-backend-for-triton/issues/542)
2. Different tiling strategy [#2 GEMM Performance] gemm perf of certain shapes below 80% of oneDNN #926
