### ISSUE TITLE
Pass optimization for TTGIR

### ISSUE THREAD

**Issue by huanpengchu** [intel/intel-xpu-backend-for-triton#537]
During the transition from ttir to ttgir, Intel_XPU and Nvidia's _compiler.py_  （ in third_party） are almost identical. 
 I would like to ask if the optimized code of ttgir is consistent with NvidiaGPU, and what is the difference?
The code is shown as follows:

```python
` def make_ttgir(mod, metadata, opt, capability):
        cluster_info = intel.ClusterInfo() \n
        if opt.cluster_dims is not None:
            cluster_info.clusterDimX = opt.cluster_dims[0]
            cluster_info.clusterDimY = opt.cluster_dims[1]
            cluster_info.clusterDimZ = opt.cluster_dims[2]
        # TTIR -> TTGIR
        pm = ir.pass_manager(mod.context)
        pm.enable_debug()
        passes.ttir.add_convert_to_ttgpuir(pm, opt.num_warps, opt.threads_per_warp, opt.num_ctas, capability)
        # optimize TTGIR
        passes.ttgpuir.add_coalesce(pm)
        # TODO(Qingyi): Move PlanCTAPass to the front of CoalescePass
        intel.passes.ttnvgpuir.add_plan_cta(pm, cluster_info)
        passes.ttgpuir.add_remove_layout_conversions(pm)
        passes.ttgpuir.add_optimize_thread_locality(pm)
        passes.ttgpuir.add_accelerate_matmul(pm, capability)
        passes.ttgpuir.add_remove_layout_conversions(pm)
        if opt.optimize_epilogue:
            passes.ttgpuir.add_optimize_epilogue(pm)
        passes.ttgpuir.add_optimize_dot_operands(pm)
        passes.common.add_cse(pm)
        if capability // 10 >= 8:
            passes.ttgpuir.add_pipeline(pm, opt.num_stages, opt.num_warps, opt.num_ctas, capability)
        if capability // 10 <= 8:
            passes.ttgpuir.add_prefetch(pm)
        passes.ttgpuir.add_optimize_dot_operands(pm)
        passes.ttgpuir.add_remove_layout_conversions(pm)
        passes.ttgpuir.add_reduce_data_duplication(pm)
        passes.ttgpuir.add_reorder_instructions(pm)
        passes.common.add_cse(pm)
        passes.common.add_symbol_dce(pm)
        if capability // 10 >= 9:`
```

If I want to **register a new backend for triton** refer to  IntelXPU, what needs to be modified by ttgir's optimization pass? Thank you very much

**Comment by whitneywhtsang** [comment]
You are correct that the transformation pipelines on the two backends are very similar to start with, but the passes are invoked with different arguments and the transformations themselves are modified. One example is we have added a dpas layout as a counterpart of the NVidia mma layout. You don't need to do that if performance is not a concern, and you can just use FMA. We plan to modify the pipeline as needed, e.g., when we have new optimizations.
You can see the modifications we did by git diff our repo with the corresponding OpenAI commit.

**Comment by whitneywhtsang** [comment]
@huanpengchu Can we close this issue?

**Comment by huanpengchu** [comment]
> @huanpengchu Can we close this issue?

ok, thank you very much
