### ISSUE TITLE
IPEX  to handle the new AttrsDescriptor

### ISSUE THREAD

**Issue by vlad-penkin** [intel/intel-xpu-backend-for-triton#538]
This issue is related to the
- #511

To resolve this issue:
- IPEX Team needs to implement the support for the new AttrsDescriptor
- Triton XPU Team to revert #511

**Comment by LiyangLingIntel** [comment]
The new `AttrsDescriptor` params are updated in https://github.com/Stonepia/pytorch/commit/30f44da22b3185e1c0dfe13db420d3dc8caab613
@whitneywhtsang , can you help validate and revert https://github.com/intel/intel-xpu-backend-for-triton/pull/511

**Comment by whitneywhtsang** [comment]
> The new `AttrsDescriptor` params are updated in [Stonepia/pytorch@30f44da](https://github.com/Stonepia/pytorch/commit/30f44da22b3185e1c0dfe13db420d3dc8caab613) @whitneywhtsang , can you help validate and revert #511

Thanks @LiyangLingIntel, it works, created PR to revert #511.
