### ISSUE TITLE
[Performance] end to end performance for llvm backend is not competible as spirv backend.

### ISSUE THREAD

**Issue by Stonepia** [intel/intel-xpu-backend-for-triton#545]
We did an end to end test for the huggingface model suite. The llvm backend's performance largely lags behind the spirv target.   The overall result is below, for the geomean speedup, in every case the LLVM backend is behind the spirv baseline.

|     Test Scenario    |    Comp Item    |     Huggingface    |        Huggingface       |
|:--------------------:|:---------------:|:------------------:|:------------------------:|
|                      |                 | Triton LLVM latest | Triton 2.1 as   baseline |
| AMP_BF16   Inference |    Pass Rate    |     100%, 78/78    |        100%, 78/78       |
|                      | Geomean Speedup |        1.20x       |           2.13x          |
|   AMP_BF16 Training  |    Pass Rate    |     94%, 80/85     |        92%, 78/85        |
|                      | Geomean Speedup |        1.15x       |           1.44x          |
| AMP_FP16   Inference |    Pass Rate    |     100%, 46/46    |        100%, 46/46       |
|                      | Geomean Speedup |        1.12x       |           2.09x          |
|   AMP_FP16 Training  |    Pass Rate    |     93%, 43/46     |        93%, 43/46        |
|                      | Geomean Speedup |        1.08x       |           1.48x          |
|    BF16 Inference    |    Pass Rate    |     100%, 77/77    |        100%, 77/77       |
|                      | Geomean Speedup |        1.05x       |           1.33x          |
|     BF16 Training    |    Pass Rate    |     94%, 78/83     |        92%, 76/83        |
|                      | Geomean Speedup |        1.01x       |           1.12x          |
|    FP16 Inference    |    Pass Rate    |     100%, 46/46    |        100%, 46/46       |
|                      | Geomean Speedup |        1.02x       |           1.29x          |
|     FP16 Training    |    Pass Rate    |     93%, 43/46     |        93%, 43/46        |
|                      | Geomean Speedup |        1.01x       |           1.11x          |
|    FP32 Inference    |    Pass Rate    |     100%, 46/46    |        100%, 46/46       |
|                      | Geomean Speedup |        1.01x       |           1.15x          |
|     FP32 Training    |    Pass Rate    |     100%, 46/46    |        100%, 46/46       |
|                      | Geomean Speedup |        1.00x       |           1.08x          |

For example, below is a comparison for amp bf16 inference.

The `comparison` column is the ratio between llvm/spirv, the eager time on spirv and llvm are basically aligned. However, for the inductor time, the llvm backend is much slower.

|                                   |            | llvm path |             |          |   spirv path   |                |             |   | Comparison    |                    |
|-----------------------------------|------------|:---------:|:-----------:|:--------:|:--------------:|:--------------:|:-----------:|---|---------------|--------------------|
| name                              | batch_size | speedup   | Inductor | Eager    | speed_up_spirv | inductor_spirv | eager_spirv |   | Inductor Comp | Eager Compararison |
| XLNetLMHeadModel                  | 8          | 0.382705  | 0.298739    | 0.114329 | 1.884108       | 0.060599       | 0.114174    |   | 0.202848      | 0.998649           |
| ElectraForQuestionAnswering       | 64         | 0.71939   | 0.083922    | 0.060373 | 2.497017       | 0.023153       | 0.057814    |   | 0.275888      | 0.957614           |
| RobertaForQuestionAnswering       | 16         | 0.743583  | 0.072586    | 0.053974 | 2.551326       | 0.020942       | 0.053429    |   | 0.288507      | 0.989904           |
| T5ForConditionalGeneration        | 4          | 0.955389  | 0.072279    | 0.069055 | 3.276058       | 0.021023       | 0.068874    |   | 0.290865      | 0.997386           |
| T5Small                           | 4          | 0.96356   | 0.072049    | 0.069424 | 3.266502       | 0.021152       | 0.069094    |   | 0.293582      | 0.995252           |
| RobertaForCausalLM                | 16         | 0.840574  | 0.087003    | 0.073132 | 2.414822       | 0.025949       | 0.062663    |   | 0.298257      | 0.856841           |
| PLBartForConditionalGeneration    | 4          | 0.50075   | 0.104992    | 0.052575 | 1.55131        | 0.032259       | 0.050044    |   | 0.307256      | 0.951872           |
| BertForQuestionAnswering          | 16         | 0.745903  | 0.079237    | 0.059103 | 2.333583       | 0.02458        | 0.057358    |   | 0.310202      | 0.970477           |
| BertForMaskedLM                   | 16         | 0.809786  | 0.093029    | 0.075333 | 2.271049       | 0.029016       | 0.065897    |   | 0.311904      | 0.874735           |
| LayoutLMForSequenceClassification | 16         | 0.778216  | 0.075163    | 0.058493 | 2.392575       | 0.024335       | 0.058223    |   | 0.323758      | 0.995374           |
| OPTForCausalLM                    | 2          | 1.209439  | 0.09254     | 0.111922 | 3.150567       | 0.030503       | 0.096101    |   | 0.329617      | 0.858647           |
| DebertaForQuestionAnswering       | 16         | 0.696973  | 0.074557    | 0.051964 | 2.077687       | 0.024921       | 0.051779    |   | 0.334261      | 0.996438           |

We suspect that for the spirv path, the `num_warps` and other info are included in the kernel info. However, when changed to the llvm path, the kernel does not contain such info, and llvm path does not choose the optimal config. 

Please help for locating the root cause.

**Comment by Stonepia** [comment]
Env info:

```
GPU: Max 1100
Driver version:  803.29
oneAPI: 2024.1

Triton:  890b7402b6a4cbada9cd94484237b0416686cec4 (Tue Feb 20)
PyTorch: 0f6d72ce16bd4b30402dcad97144d17cd7bc53ed (Based on PyTorch 2.1)
IPEX: f496a32aed6d9ad4c70fcbbf2d3321a385affccb

HUGGINGFACE_PIN_COMMIT: 4.27.4
```

**Comment by aregm** [comment]
@Stonepia I don't understand what 'Eager' column is? Eager mode working on PVC?

**Comment by Stonepia** [comment]
Hello @aregm , Thanks for the comment.

- The "speedup" is calculated by "eager/inductor": if speedup is less than 1, then this means inductor time is longer than eager time.
- The "Eager" means eager time, i.e., run the model in eager mode, run op by op. This is the native mode in PyTorch, and that is set as a baseline.
- The "Inductor" means graph time. i.e., run the model in graph mode (torch.compile), the ops will be fused into one triton kernel, and then run kernel by kernel.
