### ISSUE TITLE
Merge OpenAI Triton till March 28th

### ISSUE THREAD

**Issue by vlad-penkin** [intel/intel-xpu-backend-for-triton#554]
It is essential to keep up to date with OpenAI Triton, to get the latest features, and reduce the difficulty to upstream our changes to OpenAI Triton.

This ticket is continuation of:
- #208

**Comment by whitneywhtsang** [comment]
Moved up from Feb 15 to Mar 6 Triton version from OpenAI, which includes 111 commits. 
\[https://github.com/intel/intel-xpu-backend-for-triton/pull/535, https://github.com/intel/intel-xpu-backend-for-triton/pull/557, https://github.com/intel/intel-xpu-backend-for-triton/pull/566, https://github.com/intel/intel-xpu-backend-for-triton/pull/578, https://github.com/intel/intel-xpu-backend-for-triton/pull/585, https://github.com/intel/intel-xpu-backend-for-triton/pull/590, https://github.com/intel/intel-xpu-backend-for-triton/pull/599, https://github.com/intel/intel-xpu-backend-for-triton/pull/602, https://github.com/intel/intel-xpu-backend-for-triton/pull/605, https://github.com/intel/intel-xpu-backend-for-triton/pull/606, https://github.com/intel/intel-xpu-backend-for-triton/pull/661, https://github.com/intel/intel-xpu-backend-for-triton/pull/667, https://github.com/intel/intel-xpu-backend-for-triton/pull/670 \]

**Comment by whitneywhtsang** [comment]
Moved up from Mar 6 to Mar 27 Triton version from OpenAI, which includes 115 commits.
\[https://github.com/intel/intel-xpu-backend-for-triton/pull/696, https://github.com/intel/intel-xpu-backend-for-triton/pull/702, https://github.com/intel/intel-xpu-backend-for-triton/pull/721, https://github.com/intel/intel-xpu-backend-for-triton/pull/724, https://github.com/intel/intel-xpu-backend-for-triton/pull/726, https://github.com/intel/intel-xpu-backend-for-triton/pull/727, https://github.com/intel/intel-xpu-backend-for-triton/pull/753, https://github.com/intel/intel-xpu-backend-for-triton/pull/767, https://github.com/intel/intel-xpu-backend-for-triton/pull/774 ]
