### ISSUE TITLE
[timm][inference][float16][regression] `res2net50_14w_8s` fail accuracy

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#562]
`res2net50_14w_8s` fail accuracy at float16 in inference mode. It passes with v2.1.

**Comment by riverliuintel** [comment]
There is no accuracy difference between A100 and PVC on this model with pytorch 2.1, and PyTorch upstream goal is on par with CUDA about accuracy and functionality pass rate. So won't fix for PyTorch upstream.
