### ISSUE TITLE
Incorrect include path computation

### ISSUE THREAD

**Issue by leshikus** [intel/intel-xpu-backend-for-triton#570]
Here the include dir is computed incorrectly 

https://github.com/intel/intel-xpu-backend-for-triton/blob/f4a6318f077cee697afd8d90cdf63cc96fd868fb/third_party/intel/backend/driver.py#L14

1) it should not contain `local`
2) it should not contain `level_zero` because include commands already contain it

**Comment by pbchekin** [comment]
@leshikus, please add more details for this. Currently it works with  oneAPI BaseKit installed with offline installer and initialized with `setvars.sh`, but does not work when installing level_zero from deb packages and BaseKit packages with conda.

**Comment by vlad-penkin** [comment]
@whitneywhtsang and @kurapov-peter can you look at this ticket?

**Comment by vlad-penkin** [comment]
@pbchekin and @leshikus can we close this ticket?

**Comment by leshikus** [comment]
Fixed
