### ISSUE TITLE
[unified builds] PT/IPEX/PT benchmark branches which support Intel Triton XPU 2.1 wheel and Triton 3.0 API at the same time

### ISSUE THREAD

**Issue by vlad-penkin** [intel/intel-xpu-backend-for-triton#572]
To streamline the e2e functional and performance validation we PT/IPEX/PT Benchmark branches which support Intel Triton XPU 2.1 (spirv branch) and Intel Triton 3.0 XPU (llvm branch) at the same time:

- PYTORCH_REPO: https://github.com/Stonepia/pytorch.git
- PYTORCH_BRANCH: dev/triton-test-3.0
- IPEX_REPO: https://github.com/intel/intel-extension-for-pytorch.git
- IPEX_BRANCH: dev/triton-test-3.0
- BENCHMARK_REPO: https://github.com/weishi-deng/benchmark.git
- BENCHMARK_BRANCH: main

**Comment by Stonepia** [comment]
Hello, This feature is implemented in the latest PyTorch and Triton, for IPEX, there is no API change.

PyTorch: https://github.com/Stonepia/pytorch/commit/cbd2bb7011a63102e3f9235b03e0ce300d151e51

Triton spirv-target: https://github.com/intel/intel-xpu-backend-for-triton/commit/ffc918d7e03b094a68a852419f5e38b78be6ded2

 

For the above version, both llvm-target and spirv-target could work.

**Comment by pbchekin** [comment]
> Hello, This feature is implemented in the latest PyTorch and Triton, for IPEX, there is no API change.
> 
> PyTorch: [Stonepia/pytorch@85c67db](https://github.com/Stonepia/pytorch/commit/85c67db7c86bc97b4fb6d39efa62b33e87b4952e)
> 
> Triton spirv-target: [ffc918d](https://github.com/intel/intel-xpu-backend-for-triton/commit/ffc918d7e03b094a68a852419f5e38b78be6ded2)
> 
> For the above version, both llvm-target and spirv-target could work. To use the spirv backend, please make sure `export TRITON_XPU_USE_LEGACY_API=1`

Note that https://github.com/Stonepia/pytorch/commit/85c67db7c86bc97b4fb6d39efa62b33e87b4952e#diff-8dfc175f817a04eb10c183509564129a91f32db31190e7b4ad3fd9653337c6f6R487

```
if os.environ["TRITON_XPU_USE_LEGACY_API"]=="1":
```

raises `KeyError: 'TRITON_XPU_USE_LEGACY_API'` if `TRITON_XPU_USE_LEGACY_API` not set.

**Comment by Stonepia** [comment]
Hi, Thanks for pointing out! I have fixed it using `os.environ.get` in https://github.com/Stonepia/pytorch/commit/d6785e186d9dda8a65c9d9170bd96a6f7faeecdf

It's strange that I didn't encounter this error locally, is it because of the Python version? I use 3.10, and seems that I could pass even if I didn't set this key.

**Comment by pbchekin** [comment]
> It's strange that I didn't encounter this error locally, is it because of the Python version? I use 3.10, and seems that I could pass even if I didn't set this key.

Thank you fore fixing it! This branch of code is not executed when you install IPEX with the existing Triton. The exception handler is executed if Triton is not installed or installed but import fails.
