### ISSUE TITLE
[perf] Inefficient barriers are used for reductions

### ISSUE THREAD

**Issue by ienkovich** [intel/intel-xpu-backend-for-triton#577]
The problem should be reproducible with any reduction kernel. I tried kernel with `tl.max`:
```
@triton.jit
def kernel(in_p, out_p, num_blocks, num_elems):
    block_no = tl.program_id(0)
    block_index = tl.full([1], block_no, tl.int32)
    index = tl.arange(0, 512)
    mask = index < num_elems
    x = tl.load(in_p + (block_index * 512 + index), mask, other=float("-inf")).to(tl.float32)
    res = tl.max(x, axis=0)
    tl.store(out_p + block_no, res)

def get_args():
    arg_0 = rand_strided((192, 512, 512), (262144, 512, 1), device='xpu:0', dtype=torch.bfloat16)
    arg_1 = rand_strided((192, 512, 1), (512, 1, 1), device='xpu:0', dtype=torch.bfloat16)
    return arg_0, arg_1


def call(args):
    with torch.xpu._DeviceGuard(0):
        torch.xpu.set_device(0)
        stream0 = get_xpu_stream(0)
        kernel.run(*args, 98304, 512, grid=grid(98304), warmup=False)
```

It's ~10x slower compared to Triton SPIRV v2.1. I looked into the generated SPIRV binaries and there is no significant difference in the reduction algorithm except used barriers. We use `barrier(3)` call for that and Triton v2.1 uses `OpControlBarrier %uint_2 %uint_2 %uint_264`. I tried to modify the SPIRV binary by replacing barrier calls with `OpControlBarrier ` and I got 2.493ms -> 0.293ms speed-up. This means we might use too strong barriers and should try to relax them.

**Comment by whitneywhtsang** [comment]
Very good finding @ienkovich!
Both spirv and llvm paths in Triton generates `mlir::gpu::BarrierOp`.
It then lowers to ControlBarrierOp(Workgroup, Workgroup, WorkgroupMemory | AcquireRelease) for spirv path.
```
LogicalResult GPUBarrierConversion::matchAndRewrite(
    gpu::BarrierOp barrierOp, OpAdaptor adaptor,
    ConversionPatternRewriter &rewriter) const {
  MLIRContext *context = getContext();
  // Both execution and memory scope should be workgroup.
  auto scope = spirv::ScopeAttr::get(context, spirv::Scope::Workgroup);
  // Require acquire and release memory semantics for workgroup memory.
  auto memorySemantics = spirv::MemorySemanticsAttr::get(
      context, spirv::MemorySemantics::WorkgroupMemory |
                   spirv::MemorySemantics::AcquireRelease);
  rewriter.replaceOpWithNewOp<spirv::ControlBarrierOp>(barrierOp, scope, scope,
                                                       memorySemantics);
  return success();
}
```
while for llvm path, it is lowered to `_Z7barrierj(3)` in GENX dialect.

**Comment by whitneywhtsang** [comment]
Using KhronosGroup/SPIRV-LLVM-Translator, `ControlBarrierOp(Workgroup, Workgroup, WorkgroupMemory | AcquireRelease)` is lowered to `@_Z7barrierj(i32 1)`.

**Comment by etiotto** [comment]
> Using KhronosGroup/SPIRV-LLVM-Translator, `ControlBarrierOp(Workgroup, Workgroup, WorkgroupMemory | AcquireRelease)` is lowered to `@_Z7barrierj(i32 1)`. We can change the GEN barrier lowering to match it.

That means dropping the **global** memory fence (i.e. generating `_Z7barrierj(CLK_LOCAL_MEM_FENCE)`). 
Relaxing the memory semantics of the barrier in that way would cause the barrier to ensure correct ordering of memory operations to local memory only. Ordering of memory operations to global memory would not be enforced. 

I think the GEN dialect barrier operation should support an attribute to specify the memory fence semantics that are desired.

**Comment by ienkovich** [comment]
We use `genx.barrier` to lower `gpu.barrier` and the latter doesn't have attributes to specify any fence scope. We should be fine using local fences for `genx.barrier` unconditionally for now.

The patch for that is trivial but I don't have write access to push them and make PR. I'd appreciate it if someone made a PR so we don't have to wait for my write access.
```
diff --git a/mlir/include/mlir/Dialect/LLVMIR/GENXOps.td b/mlir/include/mlir/Dialect/LLVMIR/GENXOps.td
index ff45571f8e75..4f65d70652ed 100644
--- a/mlir/include/mlir/Dialect/LLVMIR/GENXOps.td
+++ b/mlir/include/mlir/Dialect/LLVMIR/GENXOps.td
@@ -130,13 +130,13 @@ def GENX_BarrierOp : GENX_Op<"barrier"> {

   string baseDescription = [{
     The `genx.barrier` operation performs a workgroup barrier and ensures all
-    outstanding memory transaction using local or global memory are complete.
+    outstanding memory transaction using local are complete.
   }];

   string llvmBuilder = [{
     llvm::Type *retType = builder.getVoidTy();
     llvm::Type *argType = builder.getInt32Ty();
-    int memFence = 3; // local + global memory fence
+    int memFence = 1; // local memory fence
     llvm::Value *arg = llvm::ConstantInt::get(argType, memFence);
     createDeviceFunctionCall(builder, "_Z7barrierj", retType, {argType}, {arg},
                              true /*convergent*/);
diff --git a/mlir/test/Target/LLVMIR/genx.mlir b/mlir/test/Target/LLVMIR/genx.mlir
index 7312674eecd2..84ae18b7cfc7 100644
--- a/mlir/test/Target/LLVMIR/genx.mlir
+++ b/mlir/test/Target/LLVMIR/genx.mlir
@@ -34,7 +34,7 @@ llvm.func @genx_special_regs() -> i32 {

 llvm.func @genx.barrier() {
   // CHECK-LABEL: genx.barrier
-  // CHECK: call void @_Z7barrierj(i32 3) [[ATTR:#.*]]
+  // CHECK: call void @_Z7barrierj(i32 1) [[ATTR:#.*]]
   genx.barrier
   llvm.return
 }
```

**Comment by whitneywhtsang** [comment]
I will make the PR.

**Comment by whitneywhtsang** [comment]
https://github.com/intel/llvm/pull/12846

**Comment by ienkovich** [comment]
Fixed
