### ISSUE TITLE
Undefined function is_integer_type is used in definition of min/max functions

### ISSUE THREAD

**Issue by gshimansky** [intel/intel-xpu-backend-for-triton#580]
Here are two calls to `is_integer_type`:
1. https://github.com/intel/intel-xpu-backend-for-triton/blob/llvm-target/python/triton/language/standard.py#L196
2. https://github.com/intel/intel-xpu-backend-for-triton/blob/llvm-target/python/triton/language/standard.py#L248

Normally this call is ignored because it is used inside of `assert` operator that is ignored by default. But when `TRITON_DEBUG=1` is used or assertions are enabled in another way, these statements are actually compiled and `is_integer_type` cannot be found.

**Comment by prathams417** [comment]
Issue also existed on OpenAI/triton. Has been resolved now and waiting on merge in OpenAI/triton https://github.com/openai/triton/pull/3358
