### ISSUE TITLE
Commits to PyToch/IPEX/Benchmark branches for Triton need to be verified

### ISSUE THREAD

**Issue by pbchekin** [intel/intel-xpu-backend-for-triton#584]
Currently there is no CI to validate commits to branches dev/triton-test-3.0 of Stonepia/pytorch and intel/intel-extension-for-pytorch. Our CI uses these branches to validate every PR, so any bad commit to these branches will block  a development process in this repository (this happened at least once in the past, see #582).

**Comment by vlad-penkin** [comment]
@riverliuintel this is a recurring problem. The recent commit in PT benchmark repo broke our E2E CI pipeline:
- #694

**Comment by Stonepia** [comment]
PR at https://github.com/intel/intel-extension-for-pytorch/pull/575 FYI
