### ISSUE TITLE
Check if LTS driver and Rolling release driver will impact the performance.

### ISSUE THREAD

**Issue by tdeng5** [intel/intel-xpu-backend-for-triton#591]
Check if LTS driver and Rolling release driver (on both LLVM-target and SPIRV-path) will impact the performance.

**Comment by ESI-SYD** [comment]
Checked some models: **No huge performance difference** between these two driver version

![image](https://github.com/intel/intel-xpu-backend-for-triton/assets/76785525/d7ac332f-799b-44ce-9623-dc721fe39f5c)
