### ISSUE TITLE
[Pytorch Upstream] Triton should not re-initialize XPU in forked subprocess.

### ISSUE THREAD

**Issue by etaf** [intel/intel-xpu-backend-for-triton#624]
When Stock pytorch use triton3.0 compile a kernel, we got: `RuntimeError: Cannot re-initialize XPU in forked **subprocess.**`.

The root cause:
Stock pytorch defaultly  use triton.compile API in multi-thread, and meanwhile, the CUDA/XPU runtime are designed should not be re-initialized in forked subprocess. But in Triton XPU Backend, it does re-initialized XPU runtime

CUDA backend have no such issue. May be triton team can align the implementation with CUDA.

This issue blocked pytorch upstream, please prioritize, thanks.

**Comment by ienkovich** [comment]
Does it mean upstream and downstream interfaces are misaligned? Why can't we always use `torch.xpu.current_stream`? Also, `cuda_stream` property in your patch doesn't look right.

**Comment by ienkovich** [comment]
> Stock pytorch defaultly use triton.compile API in multi-thread, and meanwhile, the CUDA/XPU runtime are designed should not be re-initialized in forked subprocess. But in Triton XPU Backend, it does re-initialized XPU runtime

Could you please elaborate on this? The code you referenced initializes spirv_utils module's structures, it doesn't call any SYCL or L0 initialization code. With your changes, any call to `XPUDriver.get_current_target` would fail with a segfault because of uninitialized structures.

It would also help if you could provide a test with a triton kernel in a forked process to reproduce the problem.

**Comment by etaf** [comment]
@ienkovich Sorry, my workaround patch not really work, removed them.

**Comment by etaf** [comment]
Hi, @ienkovich @vlad-penkin @guangyey 
Triton re-initializes XPU runtime in this trace: `Init XPUDriver => Init XPUUtils => get_sycl_queue`
 `get_sycl_queue` :
https://github.com/intel/intel-xpu-backend-for-triton/blob/528fc31b3dd6348206ad8fe6b74b95913725656f/third_party/intel/backend/driver.py#L66

It's ok when Inductor use triton.compile API in parent subprocess. But Inductor defaultly compile the tirton kernel parallelly, and cause the above trace hapends in a forked subprocess. By design, XPU runtime should not be re-initialized in subprocess.
CUDA doesn't have such beheavior.

**Comment by guangyey** [comment]
Actually, triton needs to init XPU runtime lazily but init when triton is imported. Currently, XPUDriver is initialized when triton is imported, which results in XPU runtime.

**Comment by etaf** [comment]
Hi，@ienkovich  @vlad-penkin 
 XPU runtime should not, and does not need to, be used during the processing of triton.compile, but it is in intel triton:`Init XPUDriver => Init XPUUtils => get_sycl_queue`, thus triggering a duplicate reinitialization in the child process. 
 
The correct way to do this is like CUDA backend as the following graph show:
![image](https://github.com/intel/intel-xpu-backend-for-triton/assets/2347459/23e1356b-1d77-40b0-ac93-8c3702339866)

This problem has always existed, but has been overcome by IPEX workaroud, which forks the child process before initializing the XPU, so that the initialization work is all done in the child process, and the error of repeated initialization of the child process does not occur.
 
![image](https://github.com/intel/intel-xpu-backend-for-triton/assets/2347459/17c2ac25-d687-46bf-9361-2ded37b4c383)

However this workaroud cannot be upstreamed and it is also not a correct solution. Because no one can guarantee that xpu runtime won't be initialized before forking a child process.

So we suggest triton team align the CUDA implementation.

**Comment by ienkovich** [comment]
> Actually, triton needs to init XPU runtime lazily but init when triton is imported. Currently, XPUDriver is initialized when triton is imported, which results in XPU runtime being re-inited in a child process.

Backend drivers in Triton are created lazily (see LazyProxy class). It works the same for all backends. So initialization happens only when the driver is used the first time. Usually, it happens on the first kernel compilation.

**Comment by ienkovich** [comment]
> XPU runtime should not, and does not need to, be used during the processing of triton.compile, but it is in intel triton:`Init XPUDriver => Init XPUUtils => get_sycl_queue`, thus triggering a duplicate reinitialization in the child process.

Both CUDA and XPU drivers implement the same interface and are used through the same driver mechanism. Both backends are created lazily. If in your case CUDA driver is created once and XPU driver is created twice then I'd suspect Triton is used differently for different backends.

A significant difference between CUDA and XPU drivers might be that XPU driver makes some XPU runtime calls on initialization while CUDA doesn't. But I don't think it might be a problem taking into account that drivers are created only on the first usage.

It's really hard to investigate the problem and propose any fixes with no way to reproduce the problem. If you could share your pytorch branch or wheel and a reproducer, it would dramatically speed up the process. Access to a machine with proper env to reproduce also works.

**Comment by EikanWang** [comment]
On the Triton side for CUDA, the `triton.compile` does not invoke any runtime APIs but just returns an instance of `CompiledKernel`. And the callee needs to invoke `_init_handles` explicitly to invoke CUDA runtime APIs through PyTorch to get some device/runtime information. 

On the PyTorch side for CUDA, the `torch.compile` forks multiple subprocesses to compile Triton kernels by invoking `triton.compile` only. When the compilation tasks finish, the main process of `torch.compile` gets the `triton.CompiledKernel` invokes its `triton.CompiledKernel._init_handles`.

It means that all the CUDA runtime API invocations happen in the main process of `torch.compile`. 

- Main process(Intialize CUDA runtime) -> Subprocess(`triton.compile` w/o any runtime invocations) -> Main process(Invoke `triton.CompiledKernel._init_handles` w/ some CUDA runtime API invocations)

PyTorch does not allow invoking device runtime APIs in the forked process if the main process has initialized device runtime. The above illustration demonstrates that CUDA does not break the rule. Regarding this issue, the key difference between XPU and CUDA is whether `triton.compile` invokes runtime APIs - CUDA: NO, XPU: YES.

If we submit a fix to reproduce the issue by excluding the workaround on IPEX side, it will break some WIP tasks for both the Triton team and the PyTorch team. But we can provide a patch to reproduce this issue. @ienkovich , does it make sense?

**Comment by ienkovich** [comment]
> If we submit a fix to reproduce the issue by excluding the workaround on IPEX side, it will break some WIP tasks for both the Triton team and the PyTorch team. But we can provide a patch to reproduce this issue. @ienkovich , does it make sense?

Yes, I could use a patch to build a local IPEX version for debugging.

Meanwhile, could you please check if this patch helps? With this, I don't have `XPUUtils` initialization on `triton.compile`.

```
diff --git a/third_party/intel/backend/driver.py b/third_party/intel/backend/driver.py
index 0bf07275..45befa91 100644
--- a/third_party/intel/backend/driver.py
+++ b/third_party/intel/backend/driver.py
@@ -379,11 +379,18 @@ class XPULauncher(object):
 class XPUDriver(DriverBase):

     def __init__(self):
-        self.utils = XPUUtils()
         self.binary_ext = "spv"
         self.launcher_cls = XPULauncher
-        self.get_current_stream = self.get_current_stream
-        self.get_current_device = self.utils.get_current_device
+
+    def get_utils(self):
+        # Lazily initialize utils to avoid unnecessary XPU runtime invocations.
+        # See https://github.com/intel/intel-xpu-backend-for-triton/issues/624
+        if not hasattr(self, "utils"):
+            self.utils = XPUUtils()
+        return self.utils
+
+    def get_current_device(self):
+        self.get_utils().get_current_device()

     def get_current_stream(self, device):
         import torch
```

**Comment by etaf** [comment]
Hi, @ienkovich, I've tried your patch, and the triton.compile currently works normal. But there seems still some problem introduced by your patch. Please check the folowing log, it happends after the triton compilation finished:
https://github.com/pytorch/pytorch/blob/1a28ebffb3e9225211413c8572f1b7dd21f0d85e/torch/_inductor/triton_heuristics.py#L361

```
  File "/tmp/torchinductor_xinanlin/zl/czlbumvr7yklu7o2fopkdbwax2hwson4s2ofukyubw6omysc22yq.py", line 105, in <module>
    async_compile.wait(globals())
  File "/home/xinanlin/xinanlin/pytorch/torch/_inductor/codecache.py", line 2658, in wait
    scope[key] = result.result()
  File "/home/xinanlin/xinanlin/pytorch/torch/_inductor/codecache.py", line 2466, in result
    kernel = self.kernel = _load_kernel(self.kernel_name, self.source_code)
  File "/home/xinanlin/xinanlin/pytorch/torch/_inductor/codecache.py", line 2442, in _load_kernel
    kernel.precompile()
  File "/home/xinanlin/xinanlin/pytorch/torch/_inductor/triton_heuristics.py", line 206, in precompile
    compiled_binary, launcher = self._precompile_config(
  File "/home/xinanlin/xinanlin/pytorch/torch/_inductor/triton_heuristics.py", line 363, in _precompile_config
    binary._init_handles()
  File "/home/xinanlin/xinanlin/intel-xpu-backend-for-triton/python/triton/compiler/compiler.py", line 295, in _init_handles
    max_shared = driver.active.utils.get_device_properties(device)["max_shared_mem"]
torch._dynamo.exc.BackendCompilerFailed: backend='compile_fx_wrapper' raised:
TypeError: 'NoneType' object cannot be interpreted as an integer

```

**Comment by etaf** [comment]
Hi, @ienkovich @vlad-penkin , please follow the following step to reproduce using IPEX.
 ### Step 1
Preparing pytorch and IPEX with my patch. Please refer this [doc](https://wiki.ith.intel.com/pages/viewpage.action?pageId=3413320045 ) to clone internal pytorch (dev/triton-test-3.0 ) and IPEX(dev/triton-test-3.0).
And apply this patch to pytorch:
```
index 7922cf45a..bddbd3a66 100644
--- a/intel_extension_for_pytorch/_inductor/xpu/__init__.py
+++ b/intel_extension_for_pytorch/_inductor/xpu/__init__.py
@@ -1,13 +1,8 @@
 import torch
 from .overrides import override_size_asserts
 from torch._inductor.codegen.common import register_backend_for_device
-from .codegen.triton import XPUTritonScheduling
-from .codegen.wrapper import XPUTritonWrapperCodeGen
-
 from .lowering import *
 from .fx_passes.fusion import *
 from ._meta_registrations import *
+override_size_asserts()

-if torch.xpu.is_available():
-    override_size_asserts()
-    register_backend_for_device("xpu", XPUTritonScheduling, XPUTritonWrapperCodeGen)
(xinanlin) sdp@7cc25526b770:~/xinanlin/ipex-t3$ cd ../pytorch-t3/
(xinanlin) sdp@7cc25526b770:~/xinanlin/pytorch-t3$ git diff
diff --git a/torch/_inductor/graph.py b/torch/_inductor/graph.py
index 71119ecd47..c164612c2c 100644
--- a/torch/_inductor/graph.py
+++ b/torch/_inductor/graph.py
@@ -154,7 +154,11 @@ class GraphLowering(torch.fx.Interpreter):
             from .codegen.triton import TritonScheduling

             register_backend_for_device("cuda", TritonScheduling, WrapperCodeGen)
-
+        if get_scheduling_for_device("xpu") is None and torch.xpu.is_available():
+            from intel_extension_for_pytorch._inductor.xpu.codegen.triton import XPUTritonScheduling
+            from intel_extension_for_pytorch._inductor.xpu.codegen.wrapper import XPUTritonWrapperCodeGen
+            register_backend_for_device("xpu", XPUTritonScheduling, XPUTritonWrapperCodeGen)
+
     def __init__(
         self,
         gm: torch.fx.GraphModule,

```

Then apply this patch to IPEX:
```
diff --git a/intel_extension_for_pytorch/_dynamo/__init__.py b/intel_extension_for_pytorch/_dynamo/__init__.py
index 9356e149c..eb8e67e09 100644
--- a/intel_extension_for_pytorch/_dynamo/__init__.py
+++ b/intel_extension_for_pytorch/_dynamo/__init__.py
@@ -1,9 +1,6 @@
 from typing import List
 import torch

-# Note: import order is significant here due to the defect of triton.compile
-# in XPU backend. Here codecache is a temp WA.
-from torch._inductor import codecache  # noqa
 from torch._dynamo.device_interface import register_interface_for_device
 from torch._dynamo.backends.registry import register_backend
 from torch._inductor.compile_fx import compile_fx
diff --git a/intel_extension_for_pytorch/_inductor/xpu/__init__.py b/intel_extension_for_pytorch/_inductor/xpu/__init__.py
index 7922cf45a..acc46eb3a 100644
--- a/intel_extension_for_pytorch/_inductor/xpu/__init__.py
+++ b/intel_extension_for_pytorch/_inductor/xpu/__init__.py
@@ -1,13 +1,9 @@
 import torch
 from .overrides import override_size_asserts
 from torch._inductor.codegen.common import register_backend_for_device
-from .codegen.triton import XPUTritonScheduling
-from .codegen.wrapper import XPUTritonWrapperCodeGen
-
 from .lowering import *
 from .fx_passes.fusion import *
 from ._meta_registrations import *

 if torch.xpu.is_available():
-    override_size_asserts()
-    register_backend_for_device("xpu", XPUTritonScheduling, XPUTritonWrapperCodeGen)
+    override_size_asserts()

```

### Step 2
Follow the above  [doc](https://wiki.ith.intel.com/pages/viewpage.action?pageId=3413320045 )  to build pytorch, ipex, triton.

### Step3
 Run case：
```
cd  to IPEX repo 

 python tests/gpu/pytorch/test/inductor/test_torchinductor.py --verbose -k test_abs_xpu

then get the following error:

  File "/home/sdp/xinanlin/pytorch-t3/torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/sdp/xinanlin/pytorch-t3/torch/_inductor/graph.py", line 945, in compile_to_module
    mod = PyCodeCache.load_by_key_path(key, path, linemap=linemap)
  File "/home/sdp/xinanlin/pytorch-t3/torch/_inductor/codecache.py", line 1143, in load_by_key_path
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_sdp/2j/c2jqnzssfo4ktm3rsdojh5xgba4ttxjruphtkaredatwe23bnkw7.py", line 60, in <module>
    async_compile.wait(globals())
  File "/home/sdp/xinanlin/pytorch-t3/torch/_inductor/codecache.py", line 1431, in wait
    scope[key] = result.result()
  File "/home/sdp/xinanlin/pytorch-t3/torch/_inductor/codecache.py", line 1290, in result
    self.future.result()
  File "/home/sdp/miniconda3/envs/xinanlin/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/home/sdp/miniconda3/envs/xinanlin/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
torch._dynamo.exc.BackendCompilerFailed: backend='compile_fx_wrapper' raised:
RuntimeError: Cannot re-initialize XPU in forked subprocess. To use XPU with multiprocessing, you must use the 'spawn' start method

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information

```

Please feel free to ping me in teams directory if you have any problem.

**Comment by ienkovich** [comment]
> Hi, @ienkovich @vlad-penkin , please follow the following step to reproduce using IPEX.

Thanks! I could reproduce the error. Here is a fix that works for me. I'm currently running Triton tests with this patch. Do you want to make some additional checks before we merge it?
```
diff --git a/third_party/intel/backend/driver.py b/third_party/intel/backend/driver.py
index 0bf07275..b74261c0 100644
--- a/third_party/intel/backend/driver.py
+++ b/third_party/intel/backend/driver.py
@@ -379,11 +379,20 @@ class XPULauncher(object):
 class XPUDriver(DriverBase):

     def __init__(self):
-        self.utils = XPUUtils()
         self.binary_ext = "spv"
         self.launcher_cls = XPULauncher
-        self.get_current_stream = self.get_current_stream
-        self.get_current_device = self.utils.get_current_device
+
+    def __getattr__(self, name):
+        # Lazily initialize utils to avoid unnecessary XPU runtime invocations.
+        # See https://github.com/intel/intel-xpu-backend-for-triton/issues/624
+        if name == "utils":
+            self.utils = XPUUtils()
+            return self.utils
+        else:
+            raise AttributeError
+
+    def get_current_device(self):
+        return self.utils.get_current_device()

     def get_current_stream(self, device):
         import torch
```

**Comment by etaf** [comment]
Hi, @ienkovich  thanks for you help, this patch works for me!
