### ISSUE TITLE
Remove unsigned releases

### ISSUE THREAD

**Issue by pbchekin** [intel/intel-xpu-backend-for-triton#643]
There are several releases, which contain artifacts that are not cryptographically signed. Such releases need to be removed (and re-published with signed artifacts, if necessary).

**Comment by tdeng5** [comment]
@vlad-penkin @pbchekin , just double confirm, I'm going to remove the following pre-releases, is that OK?
1. [Intel XPU Backend for Triton v2.2.0](https://github.com/intel/intel-xpu-backend-for-triton/releases/tag/untagged-2c340f959f6c8d83d6b3)
2. [LLVM(5e5a22ca) Pre-built Packages](https://github.com/intel/intel-xpu-backend-for-triton/releases/tag/llvm_pkg_5e5a22ca)
3. [LLVM(b1115f8c) Pre-built Packages](https://github.com/intel/intel-xpu-backend-for-triton/releases/tag/llvm_pkg_b1115f8c)

**Comment by pbchekin** [comment]
> @vlad-penkin @pbchekin , just double confirm, I'm going to remove the following pre-releases, is that OK?
> 
> 1. [Intel XPU Backend for Triton v2.2.0](https://github.com/intel/intel-xpu-backend-for-triton/releases/tag/untagged-2c340f959f6c8d83d6b3)
> 2. [LLVM(5e5a22ca) Pre-built Packages](https://github.com/intel/intel-xpu-backend-for-triton/releases/tag/llvm_pkg_5e5a22ca)
> 3. [LLVM(b1115f8c) Pre-built Packages](https://github.com/intel/intel-xpu-backend-for-triton/releases/tag/llvm_pkg_b1115f8c)

I see that currently there are 6 releases. Do you think we can remove them all except https://github.com/intel/intel-xpu-backend-for-triton/releases/tag/v2.1.0? which is marked as "latest". For that release, I think, it should be possible to add signatures for each binary artifact.

**Comment by tdeng5** [comment]
Just checked with PyTorch team, the following releases are required for v2.1 building, we need to keep them.
1. [LLVM(5e5a22ca) Pre-built Packages](https://github.com/intel/intel-xpu-backend-for-triton/releases/tag/llvm_pkg_5e5a22ca)
2. [Intel XPU Backend for Triton v2.1.0](https://github.com/intel/intel-xpu-backend-for-triton/releases/tag/v2.1.0)

I will double check the following releases.
1. [Intel XPU Backend for Triton v2.2.0](https://github.com/intel/intel-xpu-backend-for-triton/releases/tag/untagged-2c340f959f6c8d83d6b3)
2. [LLVM(b1115f8c) Pre-built Packages](https://github.com/intel/intel-xpu-backend-for-triton/releases/tag/llvm_pkg_b1115f8c)
3. [Intel XPU Backend for Triton v2.1.0_rc1](https://github.com/intel/intel-xpu-backend-for-triton/releases/tag/v2.1.0_rc1)
4. [LLVM package for v0.1](https://github.com/intel/intel-xpu-backend-for-triton/releases/tag/llvm_pkg_v0.1)

**Comment by tdeng5** [comment]
After double confirmed with stakeholders, I just remove the following 4 release.
[Intel XPU Backend for Triton v2.2.0](https://github.com/intel/intel-xpu-backend-for-triton/releases/tag/untagged-2c340f959f6c8d83d6b3)
[LLVM(b1115f8c) Pre-built Packages](https://github.com/intel/intel-xpu-backend-for-triton/releases/tag/llvm_pkg_b1115f8c)
[Intel XPU Backend for Triton v2.1.0_rc1](https://github.com/intel/intel-xpu-backend-for-triton/releases/tag/v2.1.0_rc1)
[LLVM package for v0.1](https://github.com/intel/intel-xpu-backend-for-triton/releases/tag/llvm_pkg_v0.1)

The following 2 releases are used by PyTorch team, we need to keep them.
[LLVM(5e5a22ca) Pre-built Packages](https://github.com/intel/intel-xpu-backend-for-triton/releases/tag/llvm_pkg_5e5a22ca)
[Intel XPU Backend for Triton v2.1.0](https://github.com/intel/intel-xpu-backend-for-triton/releases/tag/v2.1.0)

**Comment by tdeng5** [comment]
@pbchekin I've removed 4 releases and keep 2 releases. For the remain 2 releases, need we sign them again? please double check.

**Comment by pbchekin** [comment]
> @pbchekin I've removed 4 releases and keep 2 releases. For the remain 2 releases, need we sign them again? please double check.

Thank you! I think we will be able to sign the remaining releases, I am going to work on that. I will close this issue when it is done, meanwhile reassigning it to me.

**Comment by pbchekin** [comment]
The remaining releases now have signatures.
