### ISSUE TITLE
[Pytorch Upstream] Triton.compile raise error: AttributeError: module 'triton.language.math' has no attribute 'isinf'

### ISSUE THREAD

**Issue by etaf** [intel/intel-xpu-backend-for-triton#645]
We got error: AttributeError: module 'triton.language.math' has no attribute 'isinf' when integration triton 3.0 into stock pytorch.

Reproduce:  Build Internal pytorch , IPEX , and triton3.0 following this [doc](https://wiki.ith.intel.com/pages/viewpage.action?pageId=3413320045)
Run case: `python tests/gpu/pytorch/test/inductor/test_torchinductor.py --verbose -k test_any_xpu`
Then get error:
```
  File "/tmp/torchinductor_sdp/mk/cmkgdp2e6af7yolwpjqr6u3s2vuzziius5xzl4wqcijqeispmprl.py", line 96, in <module>
    async_compile.wait(globals())
  File "/home/sdp/xinanlin/pytorch-t3/torch/_inductor/codecache.py", line 1431, in wait
    scope[key] = result.result()
  File "/home/sdp/xinanlin/pytorch-t3/torch/_inductor/codecache.py", line 1290, in result
    self.future.result()
  File "/home/sdp/miniconda3/envs/xinanlin/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/home/sdp/miniconda3/envs/xinanlin/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
torch._dynamo.exc.BackendCompilerFailed: backend='compile_fx_wrapper' raised:
AttributeError: module 'triton.language.math' has no attribute 'isinf'


```

**Comment by etaf** [comment]
Futher more, I found there are similar error like:
AttributeError: module 'triton.language.math' has no attribute 'isnan'
AttributeError: module 'triton.language.math' has no attribute 'min'

**Comment by riverliuintel** [comment]
> @riverliuintel @vlad-penkin Futher more, I found there are similar error like: AttributeError: module 'triton.language.math' has no attribute 'isnan' AttributeError: module 'triton.language.math' has no attribute 'min' This issue cause many Inductor UT fail, I think we should prioritize.

Then it will become a PR submission block issue.

**Comment by whitneywhtsang** [comment]
Can we do a similar change as https://github.com/Stonepia/pytorch/pull/3 in upstream pytorch?

**Comment by etaf** [comment]
Hi @whitneywhtsang , I think we should not change the triton codegen in upstream pytorch. BTW, Does intel triton designed to not support tl.math.*?

**Comment by whitneywhtsang** [comment]
openai triton made that decision: https://github.com/intel/intel-xpu-backend-for-triton/commit/0bd315f6be50cd8b8f9a25107bd4aca5f69bb853

**Comment by etiotto** [comment]
Given that this change was made in Triton upstream. I think pytorch will have have to be changed to adapt to the Triton changes (even for NVidia).

**Comment by etaf** [comment]
Thanks @whitneywhtsang @etiotto , I found stock pytorch just support this change today. We can close this issue.
