### ISSUE TITLE
[Pytorch Upstream] Triton 3.0 triton.compiler.compiler.AttrsDescriptor  got an unexpected keyword argument 'divisible_by_8'

### ISSUE THREAD

**Issue by etaf** [intel/intel-xpu-backend-for-triton#646]
We got `TypeError: AttrsDescriptor.__init__() got an unexpected keyword argument 'divisible_by_8'`  when trying to integrate triton3.0 into stock pytorch.
The ` triton.compiler.compiler.AttrsDescriptor` API seems not match. 

In inductor, https://github.com/pytorch/pytorch/blob/909d73d8cb6c5697201f8dc311a943425bf43f3f/torch/_inductor/utils.py#L704C1-L715C41
 The kwargs for AttrsDescriptor includes "divisible_by_8", but triton 3.0 do not expects it: https://github.com/intel/intel-xpu-backend-for-triton/blob/7696079ec30f58be6bb99e45e42657d7e92712ca/python/triton/compiler/compiler.py#L19C1-L28C36.

You can find the stock pytorch's triton pin commit at: https://github.com/pytorch/pytorch/blob/main/.ci/docker/ci_commit_pins/triton.txt

**Comment by whitneywhtsang** [comment]
Can we do a similar change as https://github.com/Stonepia/pytorch/commit/23ee707e17d292b964e5c812b91fdb0913d7ebb8 in upstream pytorch?

**Comment by etaf** [comment]
Hi @whitneywhtsang, thanks for your reply, stock pytorch is working on adjust this change. We can close this issue.
