### ISSUE TITLE
Binary artifacts in the source repository

### ISSUE THREAD

**Issue by pbchekin** [intel/intel-xpu-backend-for-triton#647]
Currently there are the following binary artifacts in the source repository (not including the upstream ones):

```
Warn: binary detected: python/triton/third_party/spirv/bin/spirv-dis:1
Warn: binary detected: third_party/intel/backend/bin/spirv-dis:1
Warn: binary detected: third_party/intel/lib/TritonGENToLLVM/libGenISAIntrinsics.a:1
```

Binary artifacts cannot be reviewed, allowing possible obsolete or maliciously subverted executables. If they are required for building or testing, please consider building them from sources, or downloading them from a trusted location.

**Comment by pbchekin** [comment]
CC @etiotto , @whitneywhtsang

**Comment by etiotto** [comment]
`third_party/intel/lib/TritonGENToLLVM/libGenISAIntrinsics.a` will be eventually removed as we are going to change the replace the GenISA calls with a different API. 

We need to determine what strategy to use for  the other 2 binaries.

**Comment by whitneywhtsang** [comment]
Dependency to `libGenISAIntrinsics.a` is removed.
