### ISSUE TITLE
[Pytorch Upstream] triton 3.0 compile got RuntimeError: Triton Error [ZE]: 2013265944

### ISSUE THREAD

**Issue by etaf** [intel/intel-xpu-backend-for-triton#666]
We got triton crash when runing stock pytroch inductor UT: ` RuntimeError: Triton Error [ZE]: 2013265944`

To reproduce the issue using IPEX:

Triton commit: 9dd5125ae5c4dd2bac023d3c13e82501c6b5f547 
Build pytorch, IPEX following the [doc](https://wiki.ith.intel.com/pages/viewpage.action?pageId=3413320045)

python run the following case in IPEX:
`python  tests/gpu/pytorch/test/inductor/test_torchinductor.py -k test_isinf_xpu`

**Comment by whitneywhtsang** [comment]
#674 is merged, @etaf please verify.

**Comment by etaf** [comment]
Verified, thanks @whitneywhtsang!
