### ISSUE TITLE
[intel] Change `insert_slice_async` to `async_copy_global_to_local`

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#669]
Upstream OpenAI commit 2f5f038630d853adfd2edef0c947b844cbf69f01 changes `insert_slice_async` to `async_copy_global_to_local`. We need to properly handle it in intel backend. It is temporarily partially reverted in https://github.com/intel/intel-xpu-backend-for-triton/commit/bbc71c7e06d316662201ae18b5877b01706969ff.

**Comment by prathams417** [comment]
https://github.com/intel/intel-xpu-backend-for-triton/pull/682
