### ISSUE TITLE
[test_core.py::test_convert2d] fails to run correctly on PVC

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#695]
To reproduce, remove:
```
    if is_xpu() and M == 128 and N == 128 and interm_layout and (dst_layout.sz_per_thread == [1, 8]
                                                                 or dst_layout.sz_per_thread == [4, 4]):
        pytest.skip("FIXME: out of resource: shared memory")
```
and run:
`python3 -m pytest --verbose --device xpu python/test/unit/language/test_core.py::test_convert2d`

**Comment by ienkovich** [comment]
Most of the failures are related to the wrong compilation pipeline (additional optimizations increase shared memory consumption). But there is also one case that fails even with the correct pipeline. Working on it.
