### ISSUE TITLE
[Triton2.1] Incapable API changes for Triton

### ISSUE THREAD

**Issue by Stonepia** [intel/intel-xpu-backend-for-triton#698]
Hi,
This is just a reminder, because of the need to support the https://github.com/intel/intel-xpu-backend-for-triton/issues/589, the IPEX changed the API in https://github.com/intel/intel-extension-for-pytorch/commit/256254c7bfea90b1064c4fc91155f9d6f10d7731. From this commit, the Triton 2.1 with spirv-target also needs to be changed as in llvm-target (if you wish to run Triton2.1).

The workable commits for Triton 2.1 are:
PyTorch: 1b057713ae09fa8e4e0a55e8085fac3325e33c68
IPEX:  f2915d8a77338ced59a7d321e594aef123725b06

For Triton 3.0, using the latest PyTorch/IPEX would be ok.

**Comment by riverliuintel** [comment]
If want to measure the baseline of Triton v2.1 in test proxy for apple-to-apple comparison, please use the specified version. However, if want to make test proxy continuing support Triton v2.1 version, Triton v2.1 SPLIV source should be updated to include this interface changes.

**Comment by vlad-penkin** [comment]
Triton is switching to upstream PT from IPEX. Triton 3.0 reached Pass rate and Performance parity with 2.1 in March.
