### ISSUE TITLE
[PyTorch Upstream] AttributeError: module 'triton.language.extra.intel.libdevice' has no attribute 'j0'

### ISSUE THREAD

**Issue by etaf** [intel/intel-xpu-backend-for-triton#701]
We got triton compilation errors when runing upstream Pytorch Inductor UT: 
- AttributeError: module 'triton.language.extra.intel.libdevice' has no attribute 'j0'
- AttributeError: module 'triton.language.extra.intel.libdevice' has no attribute 'j1'
- AttributeError: module 'triton.language.extra.intel.libdevice' has no attribute 'y0'
- AttributeError: module 'triton.language.extra.intel.libdevice' has no attribute 'y1'
- AttributeError: module 'triton.language.extra.intel.libdevice' has no attribute 'cyl_bessel_i0'
- AttributeError: module 'triton.language.extra.intel.libdevice' has no attribute 'cyl_bessel_i1'

Triton (llvm-target current latest) commit: 0b0b8d785f1c30e8ffa1edafc243f956fe6f19d8

**Comment by ienkovich** [comment]
We have `j0`, `j1`, `y0`, and `y1` functions in out runtime library and I'll add appropriate libdevice functions. Unfortunately, we don't have `cyl_bessel_i0` and `cyl_bessel_i1` and will have to ask to add it to SYCL runtime (or show us an alternative), this might take some time.

**Comment by etaf** [comment]
@ienkovich thanks for your update.
