### ISSUE TITLE
[Performance] Huggingface models DistilBertForMaskedLM, XLNetLMHeadModel's performance dropped >15% compared to v2.1

### ISSUE THREAD

**Issue by ESI-SYD** [intel/intel-xpu-backend-for-triton#709]
bash inductor_xpu_test.sh huggingface bfloat16 training performance xpu 0 static 1 0 DistilBertForMaskedLM
![image](https://github.com/intel/intel-xpu-backend-for-triton/assets/76785525/c42f708d-9881-4473-b790-4eb49af57f72)

bash inductor_xpu_test.sh huggingface amp_bf16 inference performance xpu 0 static 1 0 XLNetLMHeadModel
![image](https://github.com/intel/intel-xpu-backend-for-triton/assets/76785525/79108e33-1f06-4a35-af61-d51693d756d6)

**Comment by quintinwang5** [comment]
`XLNetLMHeadModel` has the same cause with https://github.com/intel/intel-xpu-backend-for-triton/issues/707, and has been verified.

**Comment by quintinwang5** [comment]
Same as here https://github.com/intel/intel-xpu-backend-for-triton/issues/708#issuecomment-2022248294

**Comment by vlad-penkin** [comment]
@quintinwang5 can we close this ticket?

**Comment by quintinwang5** [comment]
> @quintinwang5 can we close this ticket?

Yes.
