### ISSUE TITLE
[DPAS] 15 cases in test_matmul failed with the LLVM optimization O3.

### ISSUE THREAD

**Issue by chengjunlu** [intel/intel-xpu-backend-for-triton#718]
There are 15 cases in test_matmul failed on PVC with the LLVM optimization O3 on Triton side.
https://github.com/intel/intel-xpu-backend-for-triton/blob/0085bc91c7b0ecad9c98c1ad68e7dfcc1d359d0d/third_party/intel/backend/compiler.py#L170

```
=========================== short test summary info ============================
FAILED test/unit/operators/test_matmul.py::test_op[128-128-32-1-4-2-107-233-83-True-False-float16-float16-True-True-None-None]
FAILED test/unit/operators/test_matmul.py::test_op[128-128-32-1-4-2-107-233-83-True-False-bfloat16-bfloat16-True-True-None-None]
FAILED test/unit/operators/test_matmul.py::test_op[256-128-32-1-8-2-None-None-None-True-False-float32-float32-True-True-None-None]
FAILED test/unit/operators/test_matmul.py::test_op[128-128-32-1-4-2-256-384-160-True-False-float32-float32-True-True-None-None]
FAILED test/unit/operators/test_matmul.py::test_op[128-256-64-1-8-3-256-512-160-True-True-float32-float32-True-True-None-None] Failed with O0
FAILED test/unit/operators/test_matmul.py::test_op[256-128-32-1-8-4-512-256-160-True-False-float32-float32-True-True-None-None]
FAILED test/unit/operators/test_matmul.py::test_op[128-128-32-1-4-4-256-256-160-True-False-float32-float32-True-True-None-None]
FAILED test/unit/operators/test_matmul.py::test_op[128-256-32-1-8-2-None-None-None-True-False-float16-float32-True-True-None-None]
FAILED test/unit/operators/test_matmul.py::test_op[128-256-32-1-8-2-None-None-None-True-False-float16-float32-True-False-None-None]
FAILED test/unit/operators/test_matmul.py::test_op[128-256-32-1-8-2-None-None-None-True-False-float32-float16-True-True-None-None]
FAILED test/unit/operators/test_matmul.py::test_op[128-256-32-1-8-2-None-None-None-True-False-float32-float16-True-False-None-None]
FAILED test/unit/operators/test_matmul.py::test_op[128-256-32-1-8-2-None-None-None-True-False-bfloat16-float32-True-True-None-None]
FAILED test/unit/operators/test_matmul.py::test_op[128-256-32-1-8-2-None-None-None-True-False-bfloat16-float32-True-False-None-None]
FAILED test/unit/operators/test_matmul.py::test_op[128-256-32-1-8-2-None-None-None-True-False-float32-bfloat16-True-True-None-None]
FAILED test/unit/operators/test_matmul.py::test_op[128-256-32-1-8-2-None-None-None-True-False-float32-bfloat16-True-False-None-None]
===== 15 failed, 684 passed, 99 skipped, 3 warnings in 6391.84s (1:46:31) ======
```

After changing the LLVM optimization to O0, 14 of the failed cases can pass correctly.

Only the case `test_op[128-256-64-1-8-3-256-512-160-True-True-float32-float32-True-True-None-None]` failed even with the O0. But it seems the accuracy issue instead of correctness issue.

```
>           torch.testing.assert_close(th_c.cpu(), tt_c.cpu())
E           AssertionError: Tensor-likes are not close!
E
E           Mismatched elements: 1536 / 131072 (1.2%)
E           Greatest absolute difference: 0.821441650390625 at index (151, 338) (up to 1e-05 allowed)
E           Greatest relative difference: 0.6238716244697571 at index (151, 338) (up to 1.3e-06 allowed)
```

Need to narrow down the root cause of the failure with O3.

**Comment by whitneywhtsang** [comment]
Please check if gfx-driver-ci-comp_igc-24641 resolves the failures.

**Comment by chengjunlu** [comment]
> Please check if gfx-driver-ci-comp_igc-24641 resolves the failures, could be the same bug in spill code insertion.

Hi @whitneywhtsang , Can you put the driver on the jupyter hub? And I can try it quickly.

**Comment by whitneywhtsang** [comment]
> > Please check if gfx-driver-ci-comp_igc-24641 resolves the failures, could be the same bug in spill code insertion.
> 
> Hi @whitneywhtsang , Can you put the driver on the jupyter hub? And I can try it quickly.

Sure, it is at `/data/waihungt/libigc1_1.0.24641.15944-igc_amd64.deb`.

**Comment by chengjunlu** [comment]
> test_op[128-128-32-1-4-2-107-233-83-True-False-float16-float16-True-True-None-None]

The test can pass with the IGC driver you give. 

Do you know what is the root cause of this issue in IGC? Is it about the code sink?

BTW: The dpas precision need to be updated to 
```
    I32EnumAttrCase<"TF32",   10,  "tf32">,
    I32EnumAttrCase<"BF16",   11,  "bf16">,
    I32EnumAttrCase<"FP16",   12, "fp16">
```

**Comment by etiotto** [comment]
> > test_op[128-128-32-1-4-2-107-233-83-True-False-float16-float16-True-True-None-None]
> 
> The test can pass with the IGC driver you give.
> 
> Do you know what is the root cause of this issue in IGC? Is it about the code sink?
> 
> BTW: The dpas precision need to be updated for that IGC to
> 
> ```
>     I32EnumAttrCase<"TF32",   10,  "tf32">,
>     I32EnumAttrCase<"BF16",   11,  "bf16">,
>     I32EnumAttrCase<"FP16",   12, "fp16">
> ```

@chengjunlu please open an issue to track this change.

**Comment by chengjunlu** [comment]
#740 is created to track the precision encoding issue.

**Comment by whitneywhtsang** [comment]
> Do you know what is the root cause of this issue in IGC? Is it about the code sink?

Bug in spill code insertion. To spill/fill beyond 4k HW slot offset, we need to switch to LSC message from HWord msg.

**Comment by etiotto** [comment]
> > Do you know what is the root cause of this issue in IGC? Is it about the code sink?
> 
> Bug in spill code insertion. To spill/fill beyond 4k HW slot offset, we need to switch to LSC message from HWord msg.

Ok we can close this issue once we have the new IGC containing the fix in a rolling driver.

**Comment by ESI-SYD** [comment]
Verified pass with driver `Agama 821.30`

**Comment by ESI-SYD** [comment]
> @ESI-SYD Did you change default threads_per_warp when doing your experiment?

Yes, used threads_per_warp=16
