### ISSUE TITLE
LLVM Platform issue

### ISSUE THREAD

**Issue by danikhan632** [intel/intel-xpu-backend-for-triton#73]
I'm currently building an extension to triton (pre-hopper commit) for Apple Silicon and I have settled on a method to do that:

1. convert TritonGPU To SPIRV; seeing that this has already been implemented I don't want to have to myself if I dont have to
2. convert ".spv" to Human-readable Metal Shader language using SPIRV-CROSS to .metal
3. compile .metal to .air
4. compile .air to .metallib
5. use metal-cpp to  use .metallib with pybind11 that will get JIT compiled similiar to your usage of SYCL but with Metal

is this a good proccess to do this and how will the different LLVM versions play into this, is the intel fork of LLVM compatible with macos-arm64?
Any feedback would be great

**Comment by vlad-penkin** [comment]
Issue was reported against legacy spirv-target which is no longer supported.
