### ISSUE TITLE
[DPAS] Change index calculation to use subgroup id.

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#743]
A small handful of instructions in the Triton code to advance coordinates, including several 16-wide “vector” instructions that really ought to be uniform “scalar” instructions. 
```
        // advance btile block prefetch Y coords
        // why aren't these scalars?
        add (16|M0)              r234.0<1>:d   r234.0<1;1,0>:d   32:w               {Compacted}      //  ALU pipe: int; $304
        add (16|M0)              r233.0<1>:d   r233.0<1;1,0>:d   32:w               {Compacted}      //  ALU pipe: int; $305
        // advance atile block prefetch X coords
(W)     add (1|M0)               r4.15<1>:d    r4.15<0;1,0>:d    32:w                                //  ALU pipe: int; $301
(W)     add (1|M0)               r235.2<1>:d   r235.2<0;1,0>:d   32:w               {Compacted}      //  ALU pipe: int; $302
        // advance atile block read X coord
(W)     add (1|M0)               r4.14<1>:d    r4.14<0;1,0>:d    32:w                                //  ALU pipe: int; $303
        // advance btile block read Y coords
(W)     add (1|M0)               r235.1<1>:d   r235.1<0;1,0>:d   32:w                                //  ALU pipe: int; $306
(W)     add (1|M0)               r235.0<1>:d   r235.0<0;1,0>:d   32:w               {Compacted}      //  ALU pipe: int; $307
        // advance loop counter
(W)     add (1|M0)               r4.0<1>:d     r4.0<0;1,0>:d     32:w               {Compacted}      //  ALU pipe: int; $308
```

The 16-wide "vector" instructions are performing loop reduction to advance coordinates for the DPAS operations. 
They can be lowered to an uniform value (`add (1|M0)`) by IGC if IGC can deduce it to be uniform.
The initial value of the coordinates depends on the subgroup id. 
In Triton, we currently get the subgroup id by `get_local_id / sub_group_size`, which IGC couldn’t deduce it to be uniformed, as it depends on local id.
Instead of  `get_local_id / sub_group_size`, we can directly obtain subgroup id, which IGC can deduce it to be uniformed.
When using subgroup id directly, it should be lowered to an uniform value by IGC.

**Comment by etiotto** [comment]
We need more context here so that once we make the required Triton changes we know how to verify the Triton kernel is lowered to the expected assembly instructions.

**Comment by whitneywhtsang** [comment]
> We need more context here so that once we make the required Triton changes we know how to verify the Triton kernel is lowered to the expected assembly instructions.

Once we make the required Triton change, we should see `add (1|M0)` instead of `add (16|M0)` for all loop reductions.

**Comment by etiotto** [comment]
Noting that PR #749 will resolve this issue *but* the TritonGEN dialect implementation of the operator that gets us the subgroup ID should lower to an OpenCL function rather than a SPIRV builtin for consistency with other operations in the dialect.
