### ISSUE TITLE
[GEMM Performance]  gemm perf with other data types and shape get to 90% of XeTLA

### ISSUE THREAD

**Issue by Dewei-Wang-sh** [intel/intel-xpu-backend-for-triton#772]
in Iteration 2, for gemm 4096x4096x4096xf16, we can get ~95% of oneDNN.
now we want to extend the gemm to more data types and shapes.
we use 08-experimental-block-pointer.benchmark.py as our test case.
data types: fp16, bf16
shapes: (m=n=k)[256, 512 ... 4096]
 - #910
 - #911 
 - #926 
 - #927 
 - #988 
 - #989 
 - #1104 
 - #1105

**Comment by vlad-penkin** [comment]
@Dewei-Wang-sh  to split the ticket into the smaller ones
