### ISSUE TITLE
Document and generalize script to reproduce IGC problems

### ISSUE THREAD

**Issue by etiotto** [intel/intel-xpu-backend-for-triton#782]

**Comment by kballeda** [comment]
@whitneywhtsang  Please share other than matmul and dot do we have any other IGC regressions.

**Comment by whitneywhtsang** [comment]
> @whitneywhtsang Please share other than matmul and dot do we have any other IGC regressions.

We also had regressions with test_convert2d before. We would like to have generalize script to create reproducer for IGC.

**Comment by vlad-penkin** [comment]
@kballeda what is the current ticket status, ETA to complete it?

**Comment by kballeda** [comment]
@vlad-penkin Early next week, Thanks

**Comment by kballeda** [comment]
@etiotto  Implemented a version which I need to get it reviewed from you. I have setup a meeting on the same. In my implementation generic template C++/L0/SYCL launcher program created  this is common for all the use cases. The only input that you need to provide is an input file consisting of information about kernel arguments, types and input data. 

If you want to create a matmul based reproducer you just need to provide the input file with following information.
Tokens - Array, Var, SM, GID has special meaning similarly data type, input data file and input/output types of arguments representing 0/1. I will share this more in the meeting. 

`Array, half, ./data/a.bin, 0
Array, half, ./data/b.bin, 0
Array, float, ./data/th.bin, 1
Var, int, 128, 0
Var, int, 256, 0
Var, int, 32, 0
Var, int, 32, 0
Var, int, 256, 0
Var, int, 256, 0
SM, int, 32768, 0
GDIM, 1, 1, 1, 8, 32`

**Comment by vlad-penkin** [comment]
@ienkovich and @alexbaden can you look at the implementation too?

**Comment by etiotto** [comment]
@kballeda we need the code to create the reproducer you showed us in a call. Do you have it somewhere ?

**Comment by alexbaden** [comment]
Closing in favor of #1471 and #1472
