### ISSUE TITLE
[DPAS]: Fix conversion tests involving DPAS layout conversions

### ISSUE THREAD

**Issue by etiotto** [intel/intel-xpu-backend-for-triton#793]
PR https://github.com/intel/intel-xpu-backend-for-triton/pull/731 fixes the compilation pipeline (see `compiler.py` in that PR) and exposes missing support for layout conversions.  

Some of the test that we now skip are `tt.dot` tests (e.g. `test_convert1d`).  Previously the DPAS layout was removed causing some of the tests skipped in that PR to lower the `tt.dot` operation to a loop (with DMAs in it).

**Comment by ienkovich** [comment]
List of tests skipped with DPAS layout:
* test_reduce_layouts
* test_store_op
* test_convert1d

**Comment by chengjunlu** [comment]
The DPAS layout is related to the same root cause: https://github.com/intel/intel-xpu-backend-for-triton/issues/781#issuecomment-2031170352

I'd like to fix it in the local XPU and then upstream the refactoring to the Triton later.

**Comment by ienkovich** [comment]
> The test cases has been enabled from 2/8/24. Is it a regression?
> 

I don't know if the test ever worked correctly, `TritonGPURemoveLayoutConversionsPass` could remove the layout conversion  
from the test, or layout could be modified by other passes. So we cannot be sure if it is a regression and when it started if it is.

**Comment by chengjunlu** [comment]
Two PRs has been created to fix the issues in unit test.
https://github.com/intel/intel-xpu-backend-for-triton/pull/804
https://github.com/intel/intel-xpu-backend-for-triton/pull/833
