### ISSUE TITLE
[UPSTREAM]: Upstream change in `lib/Dialect/TritonGPU/IR/Dialect.cpp`

### ISSUE THREAD

**Issue by etiotto** [intel/intel-xpu-backend-for-triton#816]
Upstream this change:

![image](https://github.com/intel/intel-xpu-backend-for-triton/assets/56368199/e82ea15c-1e14-4f2d-b8d2-af5e5ea74990)

**Comment by Dewei-Wang-sh** [comment]
[[BACKEND] support getWarpsPerCTA of dotOperandEncodingAttr ](https://github.com/openai/triton/pull/3593)
