### ISSUE TITLE
`tl.math.sqrt_rn(x)` runs incorrectly on XPU

### ISSUE THREAD

**Issue by ESI-SYD** [intel/intel-xpu-backend-for-triton#847]
`tl.math.sqrt_rn(x)` runs incorrectly on XPU, seems there is no precise `sqrt_rn` implemention in [libsycl-spir64-unknown-unknown.bc](https://github.com/intel/intel-xpu-backend-for-triton/blob/llvm-target/third_party/intel/backend/lib/libsycl-spir64-unknown-unknown.bc).
Remove
```python
   if expr_prec == 'tl.math.sqrt_rn(x)':
        pytest.skip("FIXME: Fail accuracy")
```
Run
```bash
python3 -m pytest --device xpu python/test/unit/language/test_core.py::test_precise_math
```

**Comment by etiotto** [comment]
The Intel  math library doesn't contain the API named `__imf_sqrtf_rn`, therefore we cannot at the moment lower the Triton `PreciseDivFOp` to that library function and we lower it instead to `__imf_sqrtf` which does not yield a result with the higher precision that is required.
