### ISSUE TITLE
Track UT failures in conda based runtime environment

### ISSUE THREAD

**Issue by leshikus** [intel/intel-xpu-backend-for-triton#866]
This is umbrella issue for test failures for triton + conda basekit run. Feel free to add issues for particular tests.

(a link to exclude list TBD)

(a link to tutorial excludes TBD)

**Comment by vlad-penkin** [comment]
@leshikus is this umbrella ticket for UT test failures? We track UT and E2E issues separately.

**Comment by leshikus** [comment]
@vlad-penkin this is for UT
