### ISSUE TITLE
[Performance] Setup a benchmark tool for Triton kernel and monitoring the performance changes of PR in CI.

### ISSUE THREAD

**Issue by chengjunlu** [intel/intel-xpu-backend-for-triton#879]
In order to support the performance tasks, we need a Triton benchmark to test the kernel performances.
And to add the benchmark test to the CI to monitoring the performance changes of each PR.
The benchmark test can be an optional action not to blocking the PR merge.

**Comment by ESI-SYD** [comment]
We setup a [repo](https://github.com/ESI-SYD/ipex-extension-example) as a relatively independent xetla version's implementation(easy to call via python module in intel-triton). softmax's kernel have been added in [PR](https://github.com/intel/intel-xpu-backend-for-triton/pull/877)
Then we just need to add related xetla kernels into  `tutorials test` in  `build-test` in CI.
For enhancement, considered to enable history performance tracking, maybe we can lavage dashboard

**Comment by tdeng5** [comment]
Enable the infrastructure to do performance testing. Add softmax first, then adding more OPs.
