### ISSUE TITLE
[Performance] Optimize the memory accessing thru un-structed pointer with the Intel 2D load/store in Triton.

### ISSUE THREAD

**Issue by chengjunlu** [intel/intel-xpu-backend-for-triton#880]
To optimize the memory accessing thru the un-structed pointer with the Intel 2D in Triton kernel, we need to analysis the pointer's athematic operation and its value layout.
If the memory accessing meet the Intel 2D load/store, we can re-writer the pointer's athematic operation with the `tt.make_tensor_ptr` and `tt.advance`.

It can not only optimize memory accessing but also reduce the integra computations on pointer's athematic operation.

**Comment by mfrancepillois** [comment]
The investigation is still ongoing. We are investigating the most efficient and robust way of raising the unstructured pointers into structured pointers.

**Comment by mfrancepillois** [comment]
The investigation has been complete and a roadmap for a pass has been drawn up. This pass is inspired by the triton-shared `Triton-to-Structured` pass. @victor-eds has taken on this task and is designing the pass.

**Comment by victor-eds** [comment]
Working on a pass. Related PRs:

- #1390 
- #1395 
- #1396

**Comment by victor-eds** [comment]
Created followup issues. Initial pass merged.
