### ISSUE TITLE
Skip lists: Remove implicit pytest.skip() in UT, migrate to pytest-select configurations

### ISSUE THREAD

**Issue by vlad-penkin** [intel/intel-xpu-backend-for-triton#882]
This ticket consists of two task groups:
- Skip lists feature implementation and it's integration in local UT test runner script and CI workflows
- Actual tests code clean up and skip tests configuration creation

PR for first task group is 
- #876

**Comment by AshburnLee** [comment]
There are two items in the description, and the 1st one is merged, so I think I need to solve the 2nd one, right?

"Actual tests code clean up and skip tests configuration creation"
1. "tests code clean up": Are you sure that we remove "pytest.skip()" in all test scripts? I thought we are not supposed to modified the source code.
2. "skip tests configuration": Is this configuration like a "pytest.ini" or "pytest.ini.toml"?

**Comment by AshburnLee** [comment]
As discussed with Vlad, close this one, and put the request into https://github.com/intel/intel-xpu-backend-for-triton/issues/1434
