### ISSUE TITLE
Merge OpenAI Triton till April 26th

### ISSUE THREAD

**Issue by vlad-penkin** [intel/intel-xpu-backend-for-triton#884]
It is essential to keep up to date with OpenAI Triton, to get the latest features, and reduce the difficulty to upstream our changes to OpenAI Triton.

This ticket is continuation of:
- #554 
- #208

**Comment by whitneywhtsang** [comment]
Moved up from Mar 27 to Apr 9 Triton version from OpenAI. [[#785](https://github.com/intel/intel-xpu-backend-for-triton/pull/785), [#803](https://github.com/intel/intel-xpu-backend-for-triton/pull/803), [#837](https://github.com/intel/intel-xpu-backend-for-triton/pull/837), [#839](https://github.com/intel/intel-xpu-backend-for-triton/pull/839), [#846](https://github.com/intel/intel-xpu-backend-for-triton/pull/846), [#849](https://github.com/intel/intel-xpu-backend-for-triton/pull/849), [#850](https://github.com/intel/intel-xpu-backend-for-triton/pull/850), [#851](https://github.com/intel/intel-xpu-backend-for-triton/pull/851), [#857](https://github.com/intel/intel-xpu-backend-for-triton/pull/857), [intel/llvm#13172](https://github.com/intel/llvm/pull/13172), [intel/llvm#13355](https://github.com/intel/llvm/pull/13355)]

**Comment by whitneywhtsang** [comment]
Moved up from Apr 9 to Apr 18 Triton version from OpenAI. \[https://github.com/intel/intel-xpu-backend-for-triton/pull/895, https://github.com/intel/intel-xpu-backend-for-triton/pull/896, https://github.com/intel/intel-xpu-backend-for-triton/pull/904, https://github.com/intel/intel-xpu-backend-for-triton/pull/919, https://github.com/intel/intel-xpu-backend-for-triton/pull/921 ]
