### ISSUE TITLE
` /usr/bin/ld: cannot find -lz` when building the backend

### ISSUE THREAD

**Issue by fcharras** [intel/intel-xpu-backend-for-triton#90]
I'd like to try the compile bundle from there https://github.com/intel/intel-xpu-backend-for-triton/pull/83 but the very last step (building triton) fails with

` /usr/bin/ld: cannot find -lz`

a solution is suggested here https://github.com/intel/intel-xpu-backend-for-triton/wiki/Possible-Build-Bugs#1-usrbinld-cannot-find--lz but I'm not root on the system so I can't install this package.

I also have zlib install in the conda environment, or I tried to extract the package and use `LD_LIBRARY_PATH` to point to other locations, it doesn't help.

Is there a way to do without system zlib ?

**Comment by retonym** [comment]
You can explicitly set zlib path with patch.
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 7dd62d1a3..d71a33362 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -203,6 +203,8 @@ set(TRITON_BINARY_DIR "${CMAKE_CURRENT_BINARY_DIR}")
 get_property(dialect_libs GLOBAL PROPERTY MLIR_DIALECT_LIBS)
 get_property(conversion_libs GLOBAL PROPERTY MLIR_CONVERSION_LIBS)
 
+find_package(ZLIB)
+
 if(TRITON_BUILD_PYTHON_MODULE)
   add_library(triton SHARED ${PYTHON_SRC})
   set(TRITON_LIBRARIES
@@ -235,11 +237,11 @@ if(TRITON_BUILD_PYTHON_MODULE)
       ${TRITON_LIBRARIES}
     )
   elseif(APPLE)
-    target_link_libraries(triton ${LLVM_LIBRARIES} z
+    target_link_libraries(triton ${LLVM_LIBRARIES} ZLIB::ZLIB
       ${TRITON_LIBRARIES}
     )
   else()
-    target_link_libraries(triton ${LLVM_LIBRARIES} z
+    target_link_libraries(triton ${LLVM_LIBRARIES} ZLIB::ZLIB
       ${TRITON_LIBRARIES}
     )
     # TODO: Figure out which target is sufficient to fix errors; triton is
```

Also `export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}`

**Comment by vlad-penkin** [comment]
@fcharras can we close this ticket?

**Comment by fcharras** [comment]
Yes, to be honest I gave up trying to build myself as a curious external early tester. but I'm looking forward binary releases (see https://github.com/intel/intel-xpu-backend-for-triton/issues/275 ) ;-) .
