### ISSUE TITLE
[PyTorch Upstream] Can not import `fast_dividef` from `triton.language.extra.intel.libdevice`

### ISSUE THREAD

**Issue by etaf** [intel/intel-xpu-backend-for-triton#901]
We are reusing stock Pytorch Inductor UT. In test case test/inductor/test_triton_kernels.py, we find the cuda code: `from triton.language.extra.cuda.libdevice import fast_dividef`.
Then we tried to do the same thing with `from triton.language.extra.intel.libdevice import fast_dividef` but failed.

**Comment by whitneywhtsang** [comment]
@etaf Please verify if the problem is resolved in the latest Triton.

**Comment by etaf** [comment]
Verified, @whitneywhtsang thanks for your help ！
