### ISSUE TITLE
[#0 GEMM Performance] get 1st round of gemm perf data of different shape

### ISSUE THREAD

**Issue by Dewei-Wang-sh** [intel/intel-xpu-backend-for-triton#910]
gemm shape:
NxNxNxf16 for N in range(1024, 4096, step 128)
5120x5120x4096xf16 
4x4096x512xf16
after we got the perf data, for the ones we got low perf, we should open new issues to track.

**Comment by ESI-SYD** [comment]
![image](https://github.com/intel/intel-xpu-backend-for-triton/assets/76785525/6cdd6674-a160-441f-9315-b6f9c3842949)


https://github.com/Dewei-Wang-sh/intel-xpu-backend-for-triton/commits/dev-all/

**Comment by whitneywhtsang** [comment]
Can we collect the same table with zero initialized A and B?

**Comment by ESI-SYD** [comment]
> Can we collect the same table with zero initialized A and B?

![image](https://github.com/intel/intel-xpu-backend-for-triton/assets/76785525/d64977b1-b801-43e8-b31e-8eb68917767a)
