### ISSUE TITLE
[#0 Attention Performance] get xetla's attention perf data and tiling strategy 

### ISSUE THREAD

**Issue by Dewei-Wang-sh** [intel/intel-xpu-backend-for-triton#912]
at this iteration, we want to focus on the following shapes.
Batch x Head x N_CTX x HeadDim x causal
1x2x1024x32 false
1x2x1024x32 true
4x48x1024x64 false
4x48x1024x64 true

**Comment by quintinwang5** [comment]
The preformance data have been updated in the [table](https://intel.sharepoint.com/:x:/r/sites/IAGSDPDMLT-NNC/_layouts/15/Doc.aspx?sourcedoc=%7BC0809A6F-F3FB-4E66-A622-66C4F2407051%7D&file=triton_kernal_benchmark_results.xlsx&wdLOR=cCA218892-8440-4837-89B9-588FB58CFD16&action=default&mobileredirect=true&isSPOFile=1&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yNDAzMjgyMTIwMCIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D). And tile strategies have been confirmed for these shapes.

**Comment by quintinwang5** [comment]
For these cases, `head_size <= 64`. The policy is:
``` c++
struct fmha_policy_64x128x64 : fmha_policy_base {
  static constexpr uint32_t kBr = 64;
  static constexpr uint32_t kSgBr = 16;
  static constexpr uint32_t kBc = 128;
  static constexpr uint32_t kSgBc = 64;
  static constexpr uint32_t kHm = 64;
  static constexpr uint32_t kSgHm = 32;
  static constexpr uint32_t thread_num = (kBr / kSgBr) * (kBc / kSgBc);
};
```
