### ISSUE TITLE
[#1 Attention Performance] raise non-block pointer to block pointer

### ISSUE THREAD

**Issue by Dewei-Wang-sh** [intel/intel-xpu-backend-for-triton#913]
in the test python/tutorial/06-fused-attention.py, we have non block pointer operation
```bash
    m_ptrs = M + off_hz * N_CTX + offs_m
    tl.store(m_ptrs, m_i)
```
however, we can raise it to block pointer for this simple pattern.
```bash
M_block_ptr = tl.make_block_ptr(
    base=M + qvk_offset,
    shape=(N_CTX),
    strides=(1),
    offsets=(start_m * BLOCK_M),
    block_shape=(BLOCK_M),
    order=(0),
 )
tl.store(M_block_ptr, m_i)
```
an analysis and rewriter pass is needed to do this.

**Comment by quintinwang5** [comment]
This can be changed in the tutorial as a workaround to unblock the process.

**Comment by Dewei-Wang-sh** [comment]
the store is for backward, now we can workaround it
