### ISSUE TITLE
Matmul kernel scratch space exceeds HW support limit

### ISSUE THREAD

**Issue by pengtu** [intel/intel-xpu-backend-for-triton#940]
The Triton tutorial 03-matrix-multiplication.py starts to fail after a recent software update to oneAPI 2024 with 'total scratch space exceeds HW supported limit".

ocloc -spirv_input -file matmul_kernel.spv -device pvc
Compilation from IR - skipping loading of FCL

error: total scratch space exceeds HW supported limit for kernel matmul_kernel_0d1d2d3de4de5de6de7c8de9c10de11c: 338752 bytes (max permitted PTSS 262144 bytes)
error: backend compiler failed build.

Build failed with error code: -11.

This occurs when Triton falls back to elementwise 'fma' instead of the 'dpas' with sub-matrix operands and result.  IGC's analysis shows that:

2000 loads
barrier
number of stores
barrier
200 loads
--> start of fma calculations

Possible solutions/workarounds in Triton of complexity from low to high are:

- Use large register file mode.
- Reduce the work group (CTA) size by increasing the number of work groups (CTAs).  However, Triton programmers can explicitly set the CTA size, which is outside of Triton compiler control.
- Generate different execution sequence when 'dpas' is unavailable, so it doesn't load 2000 elements before starting the fma operations to consume them
- Change warp size to 16 for kernels with large register pressure, which might be difficult to do without generating two versions of the kernel up front.  If Triton default to warp size 16, then we get it for free.

Generating different execution sequence when 'dpas' is not available for certain GPU architecture, or certain data types are not supported by 'dpas'.  We may want to generate 'loop' to perform 'fma' for each row/column operation to replace the 'dpas' scheme of loading all the elements into registers.

More investigation is needed for a general solution.

**Comment by etiotto** [comment]
Currently we are using large GRF mode when the kernel contains too many spills. The tutorial in question compiles and runs correctly:
```
 jovyan@jupyter-etiotto  /home/etiotto/intel-xpu-backend-for-triton/python/tutorials   etiotto/nfc_rewrite_tensor_ptr ? ⍟24  python 03-matrix-multiplication.py                                                                                          ✔  10179  18:25:51 
(I): Detected 13888 spills, recompiling the kernel using large GRF mode
(I): Kernel has now 0 spills
(I): Detected 8768 spills, recompiling the kernel using large GRF mode
(I): Kernel has now 0 spills
triton_output_with_fp16_inputs=tensor([[ 12.5781,  14.3203,  -2.5781,  ...,   1.4473,  13.2656, -21.2656],
        [ 17.9688, -57.6562,   9.9688,  ...,  -6.9219,  20.2656,  24.0781],
        [-29.9844, -11.1094,  -9.3438,  ..., -42.4375, -55.2812, -36.5938],
        ...,
        [ -9.6406,  22.7344,   5.8633,  ...,   7.1055,  22.2656,  11.6406],
        [-24.3125,   2.1738, -17.9844,  ..., -17.2344,  15.8203,  -7.0195],
        [ 18.5156, -15.4766, -24.4062,  ...,   7.1484, -20.0156, -10.5859]],
       device='xpu:0', dtype=torch.float16)
torch_output_with_fp16_inputs=tensor([[ 12.5781,  14.3203,  -2.5781,  ...,   1.4473,  13.2656, -21.2656],
        [ 17.9688, -57.6562,   9.9688,  ...,  -6.9219,  20.2656,  24.0781],
        [-29.9844, -11.1094,  -9.3438,  ..., -42.4375, -55.2812, -36.5938],
        ...,
        [ -9.6406,  22.7344,   5.8633,  ...,   7.1055,  22.2656,  11.6406],
        [-24.3125,   2.1738, -17.9844,  ..., -17.2344,  15.8203,  -7.0195],
        [ 18.5156, -15.4766, -24.4062,  ...,   7.1484, -20.0156, -10.5859]],
       device='xpu:0', dtype=torch.float16)
✅ Triton and Torch match
```
