### ISSUE TITLE
[Performance] Support 2D block load column major matrix for GEMM operand B .

### ISSUE THREAD

**Issue by LiyangLingIntel** [intel/intel-xpu-backend-for-triton#965]
Address comment https://github.com/intel/intel-xpu-backend-for-triton/pull/941#discussion_r1577061727. Current `RewriteTensorPointer` Pass only support row major tensor.
For flash attention case, we need column major tensor as the B operand of dot.

**Comment by chengjunlu** [comment]
In the `triton. ops. flash_attention`, the K matrix is implemented as column major.

**Comment by chengjunlu** [comment]
The changes are going to be submitted in these steps:
1. Add a pass to mark the `tt.load` op with the information about the column major, row major.
2. Support the lowering `tt.load` for the column major matrix with 2D block load.
3. Modify the rewrite block pointer pass to skip the column major block pointer.

Note: only support the dot layout for DPAS for now.

**Comment by etiotto** [comment]
Helping with productization of (1).

**Comment by chengjunlu** [comment]
Re-open this as 2 remaining tasks haven't be finished in this issue.
