### ISSUE TITLE
[Performance] To use the large 2D load size to load the DPAS operands A and B.

### ISSUE THREAD

**Issue by chengjunlu** [intel/intel-xpu-backend-for-triton#969]
To use the dense stride instead of warp stride in tiling the tt.dot operation. So that we can use packed 2D load/store to load the operands A and B.

Here is the difference of dense stride and warp stride in load 2d:
https://github.com/intel/intel-xpu-backend-for-triton/blob/3541627120d23258baac9d633754b02940d3cf57/lib/Conversion/TritonGPUToLLVM/LoadStoreOpToLLVM.cpp#L609

**Comment by LiyangLingIntel** [comment]
This issue is duplicated with https://github.com/intel/intel-xpu-backend-for-triton/issues/1323
