### ISSUE TITLE
[UT] Capture runtime env in reports -  oneAPI, Driver versions, GPU Device Name, wheel's and triton test suite commit id's, python version

### ISSUE THREAD

**Issue by vlad-penkin** [intel/intel-xpu-backend-for-triton#979]
**Requirements**

# Capture runtime env parameter in reports:  

1. oneAPI version 
2. Diver components (igc and level-zero) versions
3. Agama Driver base version number 
4. GPU device name
5. Commit id used from which Triton wheel was built
6. Commit id for tests
7. Triton version
8. Pytorch version
9. IPEX version
10. Python version

# Implementation approach

This is an enhancement for [scripts/test-triton.sh](https://github.com/intel/intel-xpu-backend-for-triton/blob/llvm-target/scripts/test-triton.sh) UT runner script.

Runtime information capture should be implemented in the [scripts/pytest-utils.sh](https://github.com/intel/intel-xpu-backend-for-triton/blob/llvm-target/scripts/pytest-utils.sh) script and use GPU env runtime capture script implemented through:
- #1036 

For each runtime env parameter new txt file in the reports folder should be created.

# Notes on how to get these information

## oneAPI version 

echo $CMPLR_ROOT >cmplr_version.txt
echo $MKLROOT >mkl_version.txt

## Driver version

```
apt info libigc1 | grep -oP 'Version: \K[^~]+' >libigc1_version.txt
apt info intel-level-zero-gpu  | grep -oP 'Version: \K[^~]+' >level-zero_version.txt
```

## GPU

` xpumcli discovery | grep "Device Name" | sed -n 's/.*Device Name: \(.*\)\s*|/\1/p' >gpu.txt`

**Comment by pbchekin** [comment]
Methods to identity GPU (depending on which tool is available):

```
xpumcli discovery --json | jq -r '.device_list[0].device_name'
xpu-smi discovery --json | jq -r '.device_list[0].device_name'
clinfo --json | jq -r '.devices[].online[].CL_DEVICE_NAME'
```

Both methods should produce the same result, for exmaple:

```
Intel(R) Data Center GPU Max 1100
```

As the last resort (if all the tools above are not present):
```
lspci | grep Display
```

Note that the last method produces slightly different result:

```
ad:00.0 Display controller: Intel Corporation Ponte Vecchio XT (1 Tile) [Data Center GPU Max 1100] (rev 2f)
```

**Comment by AshburnLee** [comment]
Hi, as for "Commit id for tests", what does "tests" in the runtime environment refer to?

**Comment by vlad-penkin** [comment]
@AshburnLee it's possible to use nightly wheel and up to date main branch and / or special branch with different sommit ids

**Comment by AshburnLee** [comment]
Pavel has approved the PR, only need Vlad to approve & merge the PR to close this issue.
