### ISSUE TITLE
Add A770 to nightly unit tests

### ISSUE THREAD

**Issue by alexbaden** [intel/intel-xpu-backend-for-triton#984]
With the exception of #983 , all other unit tests now pass on A770. We should be able to use the skiplist to ignore the failing `test_dot` tests and get a clean pass of the rest. Given the lack of A770 hardware, this test should be nightly for now - we can always revert if serious regressions occur. The ability to trigger it ondemand for specific PRs would be nice, but I am not sure if this is easily supported.

**Comment by pbchekin** [comment]
> Blocked by infrastructure capacity, no A770 with ReBAR.

This is now solved. To continue with the nightly workflow we need a way to skip tutorials that hang, see #1081.

**Comment by pbchekin** [comment]
We are running CI daily: https://github.com/intel/intel-xpu-backend-for-triton/actions/workflows/build-test.yml?query=actor%3Aglados-intel+a770.
Runs are still red: need to add a skip list for A770.
