### ISSUE TITLE
Add PVC skiplist for Rolling Driver

### ISSUE THREAD

**Issue by vlad-penkin** [intel/intel-xpu-backend-for-triton#985]

**Comment by AshburnLee** [comment]
From what I understanding, PVC skip list should be a .txt file which will be deselected during test in Pytest, so we need a "test_xxx.py". but there seems no "test_ .py" file for driver testing. "test_driver.py" looks like the one, but I could not find PVC or Rolling or LTS related expressions.
Did I misunderstand this request? @vlad-penkin

**Comment by vlad-penkin** [comment]
@AshburnLee see clarifications below:
- All ~12K unit tests for xpu device are in scope - https://github.com/intel/intel-xpu-backend-for-triton/blob/5231b4df4c45cbac4ea8a989ae3ae8a6d026c569/scripts/test-triton.sh#L126
- LTS and Rolling drivers for given HW architecture have different features and bugs, for each combination a separate skip lis is required

**Comment by AshburnLee** [comment]
That's been helpful, thanks @vlad-penkin

**Comment by AshburnLee** [comment]
My approach to getting skip list is different from Pavel‘s and Pavel has left comment about this, we'll discuss about it.

**Comment by AshburnLee** [comment]
Pavel gave approval for PR#1093, need your approval @vlad-penkin.
BTW, PR#1196 is not target to this issue.

**Comment by AshburnLee** [comment]
Automation script https://github.com/intel/intel-xpu-backend-for-triton/pull/1196 is not in the scope of this issue

**Comment by AshburnLee** [comment]
Close this one as it has fixed and already approved by one reviewer but still waiting the other reviewer's approval.
