### ISSUE TITLE
Add PVC skiplist for the LTS Driver

### ISSUE THREAD

**Issue by vlad-penkin** [intel/intel-xpu-backend-for-triton#986]

**Comment by AshburnLee** [comment]
My approach to getting skip list is different from Pavel‘s and Pavel has left comment about this, we'll discuss about it.

**Comment by AshburnLee** [comment]
Automation script https://github.com/intel/intel-xpu-backend-for-triton/pull/1196 is not in the scope of this issue

**Comment by AshburnLee** [comment]
Close this one as the fix is approved by one reviewer but still waiting the other reviewer's approval.
