### ISSUE TITLE
[test-triton.sh] Add an option to unskip all pytest.skip() calls 

### ISSUE THREAD

**Issue by vlad-penkin** [intel/intel-xpu-backend-for-triton#987]
# Implementation approach

1. Create a temporary copy of the [python/test](https://github.com/intel/intel-xpu-backend-for-triton/tree/llvm-target/python/test) folder
2. Replace all `pytest.skip()` calls by `pass` by developing a script which use python `ast` module and make changes to the temporary copy
3. Run UT on a temporary copy
4. Unskipped run may cause slowness / hangs like behavior, a special watcher needs to be implemented. Recommended approach is to use pytest-timeout

**Comment by AshburnLee** [comment]
1. [x] Create a temporary copy of the folder
2. [x] Replace all pytest.skip() calls by pass by developing a script which use python ast module and make changes to the temporary copy
3. [] Run UT on a temporary copy
4. [] Unskipped run may cause slowness / hangs like behavior, a special watcher needs to be implemented. Recommended approach is to use pytest-timeout

**Comment by AshburnLee** [comment]
- [x] Create a temporary copy of the folder
- [x] Replace all pytest.skip() calls by pass by developing a script which use python ast module and make changes to the temporary copy
- [x] Run UT on a temporary copy
- [x] Unskipped run may cause slowness / hangs like behavior, a special watcher needs to be implemented. Recommended approach is to use pytest-timeout
- [ ] respond to reviews

**Comment by AshburnLee** [comment]
https://github.com/intel/intel-xpu-backend-for-triton/pull/1196 is not target for this issue

**Comment by vlad-penkin** [comment]
@AshburnLee let's implement unskips via `conftest.py`. Such approach will not require any source code manipulations / changes.

To unskip the tests, we can add the following code in  `conftest.py`:

```
import pytest


def pytest_configure(config):

    def unskip(reason=None, allow_module_level=False):
        pass

    skip_f = pytest.skip
    pytest.skip = unskip
    config._skip_f = skip_f


def pytest_unconfigure(config):
    pytest.skip = config._skip_f

```

To run `pytest` with custom 'conftest.py' we can use ` --confcutdir=<path_to_folder_with_conftest.py>`  `pytest` parameter.

**Comment by AshburnLee** [comment]
That's a better solution, let me try.

**Comment by AshburnLee** [comment]
@vlad-penkin I tried your way, we can do that this way.
Only `--confcutdir` is not used like you described. `--confcutdir` allows you to specify a directory where pytest will stop searching upwards for configuration files. 
So I think `conftest.py` & `--confcutdir` are two different things that is not supposed to used together.

`conftest.py` will always take effect to test scripts in the current dir & all the sub-dir. 
So Here is my improved implementation: ...

**Comment by AshburnLee** [comment]
@pbchekin I also supported this on CI, please have a look at [.github/workflows/build-test.yml](https://github.com/intel/intel-xpu-backend-for-triton/pull/1345/files#diff-063ca77e012f959eba648db60e6868875fd1e70e5f5ac081193d848f8d61ef32)
Thanks~

**Comment by AshburnLee** [comment]
Update:

Progress: Task starts on 6/11, review starts on 6/14, (lasted 4 workdays)
Risk: `pytest-timeout` works not fully as expected, spent 1.5 workday experiment on it.

**Comment by AshburnLee** [comment]
Update:

Risk: unskip mode and skip mode(default) have different number of total test cases, (passed and xfail)

**Comment by AshburnLee** [comment]
Conclusion:
In unskip mode, some un-skipped cases cause core-dump, which terminates the Pytest session and results in the current session stopped at NOT 100%, so there are cases that will not be executed. That is the root cause.

I got fix commit in the PR, it is validated locally, now this issue has been fixed.

**Comment by AshburnLee** [comment]
Update: 
- Done, the requirement has been met.
- core-dump cases are the same for LTS & Rolling.

**Comment by pbchekin** [comment]
> * core-dump cases are the same for LTS & Rolling. uploaded here https://wiki.ith.intel.com/pages/viewpage.action?pageId=3615102092

We don't need the list of failed tests in (private) wiki. Just run the workflow and check the "Upload test reports" checkbox.
