### ISSUE TITLE
[#4 GEMM Performance] compare gemm perf to XeTLA using the same benchmark methodology

### ISSUE THREAD

**Issue by Dewei-Wang-sh** [intel/intel-xpu-backend-for-triton#988]
data types: fp16
shapes: (m=n=k)[1024, 4096, step 128]
the pytorch use oneDNN library by default, yet we want to compare to XeTLA.

**Comment by ESI-SYD** [comment]
We have collected initially data, will investigate perf gap of triton peak data between public triton and previous private [branch](https://github.com/Dewei-Wang-sh/intel-xpu-backend-for-triton/tree/dev-all) 

**FYI:**
Collecting `xetla` data: [bgemm.zip](https://github.com/intel/intel-xpu-backend-for-triton/files/15260105/bgemm.zip)
```
git clone https://github.com/intel-innersource/libraries.gpu.xetla.git
cd libraries.gpu.xetla
git apply bgemm.diff
source tools/scripts/env.sh
mkdir build && cd build
cmake ..
make -j
examples_cm_esimd/bgemm_performance/bgemm_performance
```
Collecting `Triton` data:
```
git clone -b yudong/bgemm https://github.com/intel/intel-xpu-backend-for-triton.git
cd python/tutorials 
source run.sh
bash collect.sh
```

**Comment by ESI-SYD** [comment]
![image](https://github.com/intel/intel-xpu-backend-for-triton/assets/76785525/bc0dc078-ee70-4de5-9453-0945a754ee49)

**Comment by ESI-SYD** [comment]
Refreshed with Triton autotune and Xetla flush cache:

![image](https://github.com/intel/intel-xpu-backend-for-triton/assets/76785525/523b73fa-3313-46a4-94fb-2023778d359b)

**Comment by vlad-penkin** [comment]
Add information for scripts location / batch
