### ISSUE TITLE
[#5 GEMM Performance] gemm perf of certain shapes below 90% of XeTLA

### ISSUE THREAD

**Issue by Dewei-Wang-sh** [intel/intel-xpu-backend-for-triton#989]
dive into the gemm cases that below 90% of XeTLA

**Comment by ESI-SYD** [comment]
https://github.com/intel/intel-xpu-backend-for-triton/issues/988#issuecomment-2104442644

shapes need to future check:
256
512
768
1280
1792
2048
2560
2816
3584

**Comment by Dewei-Wang-sh** [comment]
now we should transfer the shapes the same as cutlass

Shape(m*k*n):  
4096*4096*4096, 
8192*8192*8192
1024*28672*8192
3072*4096*3072
